# generated by Vaked from agentfield-swe.vaked:runtime agent-field — do not edit
#
# Expected-output fixture (no compiler exists yet) — see ./README.md and
# docs/language/0012-lowering.md §4 (the Nix spine). Edits belong in the source
# .vaked file, not here.
{
  description = "agent-field — generated by Vaked";

  inputs = {
    # nixpkgs is emitted pinned to the toolchain's baseline rev (0012 §4.1): an
    # explicit rev, never a moving channel ref. The 40-hex value below is a
    # disclosed placeholder (all-`b` = "baseline"; see ./README.md); the
    # committed flake.lock (produced at first build) records the real resolution.
    nixpkgs.url = "github:NixOS/nixpkgs/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";

    # index repoCorpus — sources (unpinned; flake.lock records the resolved rev).
    # 0012 §4.2: each index source becomes a flake input.
    repoCorpus-src-vaked-base = { url = "github:peterlodri-sec/vaked-base"; flake = false; };
  };

  outputs = { self, nixpkgs, ... }@inputs:
    let
      # runtime agent-field — systems = ["x86_64-linux"]
      systems = [ "x86_64-linux" ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f system);
    in
    {
      # nixosModules.<runtime> — wires the OTP/Zig daemons and references the
      # gen/ artifacts as installed files (0012 §4.3).
      nixosModules.agent-field = import ./nixos/agent-field.nix {
        # NixOS module fixture is described in 0012 §4.3; not emitted as a
        # separate file in this fixture set (interface only).
        inherit self;
      };

      packages = forAllSystems (system:
        let pkgs = nixpkgs.legacyPackages.${system};
        in {
          # engine zigDaemon (fiber transcriptMiner: engine = zigDaemon) — built Zig pkg.
          zigDaemon = pkgs.callPackage ./pkgs/zigDaemon.nix { };

        });

      apps = forAllSystems (system:
        let pkgs = nixpkgs.legacyPackages.${system};
        in {
          # surface fieldView (mode = raylib) — launcher app.
          # 0012 §7: surface launcher body is DEFERRED (no-op today). The slot
          # exists so the registry test stays honest, but the mapping (raylib
          # host integration) is not yet specified. The deferred body is derived
          # from NOTHING but the surface decl name: a stub that exits non-zero
          # with the standard deferral message — no real launcher is wired, and
          # it does not route through any engine/fiber package.
          fieldView = {
            type = "app";
            program = "${pkgs.writeShellScript "fieldView-launcher-deferred" ''
              echo "vaked: surface launcher lowering deferred (0012 §7)" >&2
              exit 1
            ''}";
          };
        });

      devShells = forAllSystems (system:
        let pkgs = nixpkgs.legacyPackages.${system};
        in {
          default = pkgs.mkShell {
            # toolchains the runtime needs: zig (engines).
            packages = [ pkgs.zig ];
          };
        });
    };
}
