"""vakedc.lower — the 0012 lowering pass: validated graph -> artifacts.
This module implements `docs/language/0012-lowering.md` (the normative spec). It
turns a *validated* typed semantic graph (the output of :mod:`vakedc.check`) into
the boring, inspectable artifacts Vaked owns plus the Nix spine that wires them,
together with a decl-level provenance manifest.
Purity / totality / hermeticity (0012 §2). Every emitter here is a **pure,
total, hermetic** function of ``(graph, nodes)``:
* No IO of any kind (no file reads/writes, no sockets, no subprocesses), no
wall-clock, no randomness, no environment/locale/hostname. The only IO in
the whole pipeline is the CLI write layer in :mod:`vakedc.__main__`, which
writes the ``Files`` this module returns. (0012 §2.3, §3.2.1)
* Deterministic: the same graph yields byte-identical artifacts. All ordering
is by a stable graph-derived key — declaration source order for top-level
decls, the fixed structural layout order for the flake spine, lexicographic
order for the provenance ``artifacts`` map. No hash-map iteration order.
(0012 §2.1, §3.2.2)
* No graph mutation, no cross-emitter state, no re-checking. (0012 §3.2.3-.5)
Emitter interface (0012 §3.1)::
emit : (graph, nodes) -> (files, provenance_entries)
files : dict[str path -> str | bytes] (rooted at the out tree)
provenance_entries : list[ProvEntry] (one per artifact/region)
Registry + selection (0012 §3.3/§3.4):
* ``nix.spine`` ALWAYS runs (every runtime lowers to a flake + NixOS module).
* ``docs.runtime`` runs on presence of the ``runtime`` node (unconditional).
* Direct emitters are selected by declared ``emit`` targets / fiber presence:
- a ``fiber`` selects ``zig.daemoncfg`` (a fiber has no ``emit`` field; it
is selected by presence under the runtime, 0012 §3.4 note);
- an ``index`` whose ``emit`` contains ``catalog.jsonl`` selects
``catalog.jsonl``;
- an ``index`` whose ``emit`` contains ``nix.derivation`` selects
``crabcc.index`` (the derivation lives in the spine, but it contributes
a distinct provenance entry, 0012 §5.3a).
* Deferred targets (``ebpf.policy`` / ``otel.config`` / ``systemd.units`` /
``surface.launcher``) are inert registry slots that emit nothing (0012 §7).
The surface launcher still surfaces in the spine as the §7 deferred no-op
*stub app* (``apps.<system>.<surface>``), derived from nothing but the
surface decl name.
inputsHash — the per-region projection (0012 §6.2). ``inputsHash`` is
``"sha256-" + sha256(canonical_projection_json).hexdigest()`` where the
*projection* is the emitter's resolved inputs for that region. The canonical
projection JSON is produced by :func:`_canonical_projection_json` (sorted keys,
compact separators, ``ensure_ascii=False``, no trailing newline). Per-region
projection definitions:
==================== =============================================================
Region (provenance) Projection (what the hash keys — "what the region was
projected from", 0012 §6.2)
==================== =============================================================
spine nixosModules the ``runtime`` node projection (its name + ``systems``).
spine inputs.<idx> the pinned source-index node projection (its resolved
identity + the ``trust = pinned`` digest).
spine packages.crabcc the ``index`` node projection (the index whose ``emit``
contains ``nix.derivation``).
spine packages.<eng> the RESOLVED ENGINE identity + pin (NOT the fiber node):
``{"engine": <name>, "package": "packages.<name>"}``. Its
owning decl is the ``fiber`` that references the engine,
but the hash keys the engine the fiber resolved to
(0012 §6.2: same decl, different projection).
spine apps.<surface> the ``surface`` node projection.
docs.runtime header the ``runtime`` node projection (same as nixosModules).
docs.runtime section the section's source node projection (each index /
stream / fiber / surface / parallel node).
catalog.jsonl the ``index`` node projection (the catalog's source index).
zig.daemoncfg the ``fiber`` node projection (the fiber the config runs).
==================== =============================================================
A node's projection is its kind/name plus the *canonicalized* graph props
(:func:`_node_projection`). Because the projection is a pure function of the
(immutable) graph node — or of the resolved engine identity — two regions that
project from the same node/engine carry the *same* ``inputsHash``, while two
regions that attribute to the same ``decl`` but project from different inputs
(the ``fiber`` config vs the ``engine`` package) carry *different* hashes —
exactly the 0012 §6.2 property.
"""
from __future__ import annotations
import hashlib
import ipaddress
import json
import posixpath
from dataclasses import dataclass, field as dc_field
from . import parser as P
from .graph import Graph, GraphNode
NIXPKGS_BASELINE_REV = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
_HEADER_FMT = "generated by Vaked from {file}:{decl} — do not edit"
def _header_file(source_file: str) -> str:
"""The source-file name as it appears in the §6.1 generated header: the
*basename* (``operator-field.vaked``), never the full path the graph happens
to be keyed by. The header names the source file; the manifest's
``sourceFile``/``span.file`` keep the caller-given path (0012 §6.2)."""
return posixpath.basename(source_file.replace("\\", "/"))
def _header(source_file: str, decl: str) -> str:
return _HEADER_FMT.format(file=_header_file(source_file), decl=decl)
@dataclass
class ProvEntry:
"""One provenance entry per emitted artifact or region (0012 §6.2).
``region`` is optional: absent ⇒ the entry covers the whole artifact.
``inputs_projection`` is the canonical projection object the ``inputsHash``
is computed over (kept here so the driver can serialize the manifest with a
real, reproducible hash — §2.1).
"""
artifact: str # artifact path (relative to output root)
region: "str | None"
source_file: str
decl: str # "<kind> <name>"
span: object # vakedc.graph.Span
emitter: str # registry target that produced it
inputs_projection: object # JSON-able projection (hashed for inputsHash)
def _canonical_value(v):
"""Recursively canonicalize a JSON-able value: dict keys sorted, list order
preserved (source order is meaningful). Mirrors emit._canon_value so a node's
projection is stable regardless of prop insertion order."""
if isinstance(v, dict):
return {k: _canonical_value(v[k]) for k in sorted(v.keys())}
if isinstance(v, list):
return [_canonical_value(x) for x in v]
return v
def _canonical_projection_json(projection) -> str:
"""The canonical JSON string a projection is hashed over: sorted keys,
compact separators, ``ensure_ascii=False``, no trailing newline. Deterministic
(§2.1)."""
return json.dumps(_canonical_value(projection),
separators=(",", ":"), ensure_ascii=False, sort_keys=True)
def inputs_hash(projection) -> str:
"""``"sha256-" + sha256(canonical_projection_json).hexdigest()`` (0012 §6.2)."""
canonical = _canonical_projection_json(projection)
digest = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
return "sha256-" + digest
def _node_projection(node) -> dict:
"""A node's projection: its kind + name + canonicalized props. A pure
function of the (immutable) graph node, so re-lowering an unchanged graph
yields the same hash (§2.1)."""
return {
"kind": node.kind,
"name": node.name,
"props": _canonical_value(node.props),
}
def _engine_projection(engine_name: str) -> dict:
"""The resolved-engine projection for a fiber's ``packages.<engine>`` region
(0012 §6.2). Keyed by the engine the fiber resolved to (its identity + the
flake attribute name the build resolves to a store path), NOT the fiber node
— so this region's hash differs from the fiber-config region's even though
both attribute to the same ``fiber`` decl."""
return {
"engine": engine_name,
"package": "packages." + engine_name,
}
def _children_of(graph, parent_id):
"""Direct ``contains`` children of a node, in source order (the resolver
appends edges in declaration order, and we never reorder).
Delegates to :meth:`Graph.children`, which serves this from an O(E)
adjacency index built once at edge-add time — O(deg) per parent instead of
the former O(E) full edge scan per parent. The index preserves edge
insertion order, so the returned child order is byte-for-byte identical to
the historical full-scan order."""
return graph.children(parent_id, "contains")
def _by_kind(nodes, kind):
return [n for n in nodes if n.kind == kind]
def _ref(prop):
"""The dotted ref string of a ``{"ref": "..."}`` prop value, else None."""
if isinstance(prop, dict) and "ref" in prop and "args" not in prop \
and "record" not in prop:
return prop["ref"]
return None
def _lit(prop):
"""The literal value of a ``{"lit": ..., "value": ...}`` prop, else None."""
if isinstance(prop, dict) and "lit" in prop:
return prop.get("value")
return None
def _str_list(prop):
"""A list of string-literal values from a list prop (e.g. ``views``,
``systems``, ``formats``)."""
out = []
if isinstance(prop, list):
for x in prop:
lv = _lit(x)
if lv is not None:
out.append(lv)
return out
def _app_call(prop):
"""If ``prop`` is an application ``f(args...)`` (``github("x")`` /
``raw.github("a","b")``), return ``(ref, [arg-literals])`` else None."""
if isinstance(prop, dict) and "ref" in prop and "args" in prop:
args = [_lit(a) for a in prop["args"]]
return prop["ref"], args
return None
def _record_entries(prop):
"""The ``[{"assign","op","value"}]`` entries of a record/record-app prop
(e.g. ``trust = pinned { commit = ...; sha256 = ... }``), as a dict
``name -> value-literal``. Preserves nothing but the scalar values we read."""
out = {}
rec = None
if isinstance(prop, dict):
rec = prop.get("record")
if isinstance(rec, list):
for e in rec:
if isinstance(e, dict) and "assign" in e:
out[e["assign"]] = _lit(e.get("value"))
return out
@dataclass
class _RuntimeView:
runtime: object
indexes: list = dc_field(default_factory=list)
streams: list = dc_field(default_factory=list)
fibers: list = dc_field(default_factory=list)
surfaces: list = dc_field(default_factory=list)
parallels: list = dc_field(default_factory=list)
services: list = dc_field(default_factory=list)
secrets: list = dc_field(default_factory=list)
host_resources: list = dc_field(default_factory=list)
ingresses: list = dc_field(default_factory=list)
containers: list = dc_field(default_factory=list)
memories: list = dc_field(default_factory=list)
workflows: list = dc_field(default_factory=list)
networks: list = dc_field(default_factory=list)
hosts: list = dc_field(default_factory=list)
meshes: list = dc_field(default_factory=list)
def _runtime_view(graph) -> "_RuntimeView | None":
runtimes = [n for n in graph.nodes_sorted() if n.kind == "runtime"]
if not runtimes:
return None
runtime = runtimes[0]
children = _children_of(graph, runtime.id)
return _RuntimeView(
runtime=runtime,
indexes=_by_kind(children, "index"),
streams=_by_kind(children, "stream"),
fibers=_by_kind(children, "fiber"),
surfaces=_by_kind(children, "surface"),
parallels=_by_kind(children, "parallel"),
services=_by_kind(children, "service"),
secrets=_by_kind(children, "secret"),
host_resources=_by_kind(children, "hostResource"),
ingresses=_by_kind(children, "ingress"),
containers=_by_kind(children, "container"),
memories=_by_kind(children, "memory"),
workflows=_by_kind(children, "workflow"),
networks=_by_kind(children, "network"),
hosts=_by_kind(children, "host"),
meshes=_by_kind(children, "mesh"),
)
def _index_emit_targets(index_node) -> list:
"""The dotted ``emit`` target refs of an index node (e.g.
``["catalog.jsonl", "catalog.sqlite", "nix.derivation"]``)."""
out = []
emit = index_node.props.get("emit")
if isinstance(emit, list):
for x in emit:
r = _ref(x)
if r is not None:
out.append(r)
return out
def _index_is_pinned(index_node) -> bool:
"""True when the index declares ``trust = pinned { … }`` (0012 §4.2)."""
trust = index_node.props.get("trust")
if isinstance(trust, dict) and trust.get("ref") == "pinned":
return True
return False
def _fiber_engine_name(fiber_node) -> "str | None":
return _ref(fiber_node.props.get("engine"))
def _nix_source_slug(dotted: str) -> str:
"""``github("owner/repo")`` -> a deterministic input-name slug + the
``github:owner/repo`` url. Slug = the repo's last path segment, with
``.``/``_`` normalized to ``-`` so it is a valid Nix attr fragment."""
repo = dotted.rsplit("/", 1)[-1]
slug = repo.replace(".", "-").replace("_", "-")
return slug
def emit_nix_spine(graph, nodes):
"""Emit ``flake.nix`` (0012 §4). ALWAYS runs. ``nodes`` is the whole runtime
sub-tree. The flake outputs are a pure function of the runtime node and its
children; the surface launcher is the §7 deferred no-op stub."""
rv = _runtime_view(graph)
if rv is None:
return {}, []
runtime = rv.runtime
sf = graph.source_file
rt_name = runtime.name
systems = _str_list(runtime.props.get("systems"))
systems_nix = " ".join('"%s"' % s for s in systems)
lines = []
lines.append("# " + _header(sf, "runtime " + rt_name))
lines.append("#")
lines.append("# Expected-output fixture (no compiler exists yet) — see ./README.md and")
lines.append("# docs/language/0012-lowering.md §4 (the Nix spine). Edits belong in the source")
lines.append("# .vaked file, not here.")
lines.append("{")
lines.append(' description = "%s — generated by Vaked";' % rt_name)
lines.append("")
lines.append(" inputs = {")
lines.append(" # nixpkgs is emitted pinned to the toolchain's baseline rev (0012 §4.1): an")
lines.append(" # explicit rev, never a moving channel ref. The 40-hex value below is a")
lines.append(' # disclosed placeholder (all-`b` = "baseline"; see ./README.md); the')
lines.append(" # committed flake.lock (produced at first build) records the real resolution.")
lines.append(' nixpkgs.url = "github:NixOS/nixpkgs/%s";' % NIXPKGS_BASELINE_REV)
for idx in rv.indexes:
src = idx.props.get("source")
if _index_is_pinned(idx):
call = _app_call(src)
owner = call[1][0] if call and call[1] else ""
lines.append("")
lines.append(" # index %s — trust = pinned { commit, sha256 } (0012 §4.2):" % idx.name)
lines.append(" # commit pins the rev; sha256 is recorded as the lock entry's narHash so the")
lines.append(" # build verifies the fetch. raw.github(...) => flake = false.")
lines.append(" %s-src = {" % idx.name)
lines.append(' url = "github:%s/<commit>"; # trust.pinned.commit' % owner)
lines.append(" flake = false;")
lines.append(" };")
else:
sources = src if isinstance(src, list) else ([src] if src else [])
lines.append("")
lines.append(" # index %s — sources (unpinned; flake.lock records the resolved rev)." % idx.name)
lines.append(" # 0012 §4.2: each index source becomes a flake input.")
for s in sources:
call = _app_call(s)
if call is None:
continue
owner_repo = call[1][0] if call[1] else ""
slug = _nix_source_slug(owner_repo)
lines.append(' %s-src-%s = { url = "github:%s"; flake = false; };'
% (idx.name, slug, owner_repo))
lines.append(" };")
lines.append("")
lines.append(" outputs = { self, nixpkgs, ... }@inputs:")
lines.append(" let")
lines.append(" # runtime %s — systems = [%s]"
% (rt_name, ", ".join('"%s"' % s for s in systems)))
lines.append(" systems = [ %s ];" % systems_nix)
lines.append(" forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f system);")
lines.append(" in")
lines.append(" {")
lines.append(" # nixosModules.<runtime> — wires the OTP/Zig daemons and references the")
lines.append(" # gen/ artifacts as installed files (0012 §4.3).")
lines.append(" nixosModules.%s = import ./nixos/%s.nix {"
% (_nix_attr_key(rt_name), rt_name))
lines.append(" # NixOS module fixture is described in 0012 §4.3; not emitted as a")
lines.append(" # separate file in this fixture set (interface only).")
lines.append(" inherit self;")
lines.append(" };")
lines.append("")
lines.append(" packages = forAllSystems (system:")
lines.append(" let pkgs = nixpkgs.legacyPackages.${system};")
lines.append(" in {")
seen_engines = set()
for fib in rv.fibers:
eng = _fiber_engine_name(fib)
if eng is None or eng in seen_engines:
continue
seen_engines.add(eng)
lines.append(" # engine %s (fiber %s: engine = %s) — built Zig pkg."
% (eng, fib.name, eng))
lines.append(" %s = pkgs.callPackage ./pkgs/%s.nix { };"
% (_nix_attr_key(eng), eng))
lines.append("")
for idx in rv.indexes:
targets = _index_emit_targets(idx)
if "nix.derivation" not in targets:
continue
normalize = _ref(idx.props.get("normalize"))
cat_targets = [t for t in targets if t.startswith("catalog.")]
emit_flags = " ".join("--emit " + t.split(".", 1)[1] for t in cat_targets)
lines.append(" # index %s, emit ∋ nix.derivation (0012 §5.3a) — CrabCC index" % idx.name)
lines.append(" # derivation; runs crabcc at build time over the pinned sources with")
lines.append(" # normalize = %s." % normalize)
lines.append(" %s = pkgs.stdenv.mkDerivation {"
% _nix_attr_key(idx.name + "-crabcc-index"))
lines.append(' pname = "%s-crabcc-index";' % idx.name)
lines.append(' version = "0";')
lines.append(" srcs = [")
sources = idx.props.get("source")
sources = sources if isinstance(sources, list) else ([sources] if sources else [])
for s in sources:
call = _app_call(s)
if call is None:
continue
owner_repo = call[1][0] if call[1] else ""
slug = _nix_source_slug(owner_repo)
lines.append(" inputs.%s-src-%s" % (idx.name, slug))
lines.append(" ];")
lines.append(" nativeBuildInputs = [ pkgs.crabcc ];")
lines.append(" buildPhase = ''")
norm_arg = normalize.split(".", 1)[1] if normalize and "." in normalize else normalize
lines.append(" # normalize = %s ; emit = %s"
% (normalize, ", ".join(cat_targets)))
lines.append(" crabcc index build --normalize %s \\" % norm_arg)
lines.append(" %s \\" % emit_flags)
lines.append(" --out $out")
lines.append(" '';")
lines.append(" };")
lines.append(" });")
lines.append("")
lines.append(" apps = forAllSystems (system:")
lines.append(" let pkgs = nixpkgs.legacyPackages.${system};")
lines.append(" in {")
for surf in rv.surfaces:
mode = _ref(surf.props.get("mode"))
lines.append(" # surface %s (mode = %s) — launcher app." % (surf.name, mode))
lines.append(" # 0012 §7: surface launcher body is DEFERRED (no-op today). The slot")
lines.append(" # exists so the registry test stays honest, but the mapping (raylib")
lines.append(" # host integration) is not yet specified. The deferred body is derived")
lines.append(" # from NOTHING but the surface decl name: a stub that exits non-zero")
lines.append(" # with the standard deferral message — no real launcher is wired, and")
lines.append(" # it does not route through any engine/fiber package.")
lines.append(" %s = {" % _nix_attr_key(surf.name))
lines.append(' type = "app";')
lines.append(' program = "${pkgs.writeShellScript "%s-launcher-deferred" \'\''
% surf.name)
lines.append(' echo "vaked: surface launcher lowering deferred (0012 §7)" >&2')
lines.append(" exit 1")
lines.append(" ''}\";")
lines.append(" };")
lines.append(" });")
lines.append("")
lines.append(" devShells = forAllSystems (system:")
lines.append(" let pkgs = nixpkgs.legacyPackages.${system};")
lines.append(" in {")
lines.append(" default = pkgs.mkShell {")
tool_comment_parts = []
tool_pkgs = []
if seen_engines:
tool_comment_parts.append("zig (engines)")
tool_pkgs.append("pkgs.zig")
if any("nix.derivation" in _index_emit_targets(i) for i in rv.indexes):
tool_comment_parts.append("crabcc (index)")
tool_pkgs.append("pkgs.crabcc")
lines.append(" # toolchains the runtime needs: %s." % ", ".join(tool_comment_parts))
lines.append(" packages = [ %s ];" % " ".join(tool_pkgs))
lines.append(" };")
lines.append(" });")
lines.append(" };")
lines.append("}")
text = "\n".join(lines) + "\n"
files = {"flake.nix": text}
entries = []
entries.append(ProvEntry(
artifact="flake.nix",
region="nixosModules." + rt_name,
source_file=sf,
decl="runtime " + rt_name,
span=runtime.provenance.span,
emitter="nix.spine",
inputs_projection=_node_projection(runtime),
))
for idx in rv.indexes:
if not _index_is_pinned(idx):
continue
entries.append(ProvEntry(
artifact="flake.nix",
region="inputs." + idx.name + "-src",
source_file=sf,
decl="index " + idx.name,
span=idx.provenance.span,
emitter="nix.spine",
inputs_projection=_node_projection(idx),
))
for idx in rv.indexes:
if "nix.derivation" not in _index_emit_targets(idx):
continue
entries.append(ProvEntry(
artifact="flake.nix",
region="packages." + idx.name + "-crabcc-index",
source_file=sf,
decl="index " + idx.name,
span=idx.provenance.span,
emitter="crabcc.index",
inputs_projection=_node_projection(idx),
))
seen = set()
for fib in rv.fibers:
eng = _fiber_engine_name(fib)
if eng is None or eng in seen:
continue
seen.add(eng)
entries.append(ProvEntry(
artifact="flake.nix",
region="packages." + eng,
source_file=sf,
decl="fiber " + fib.name,
span=fib.provenance.span,
emitter="nix.spine",
inputs_projection=_engine_projection(eng),
))
for surf in rv.surfaces:
entries.append(ProvEntry(
artifact="flake.nix",
region="apps." + surf.name,
source_file=sf,
decl="surface " + surf.name,
span=surf.provenance.span,
emitter="nix.spine",
inputs_projection=_node_projection(surf),
))
return files, entries
def _md_code(s) -> str:
return "`%s`" % s
def _index_source_render(idx) -> str:
"""Render an index's source(s) for the RUNTIME.md Indexes table."""
src = idx.props.get("source")
parts = []
if isinstance(src, list):
for s in src:
call = _app_call(s)
if call is not None:
ref, args = call
parts.append("%s(%s)" % (ref, ", ".join('"%s"' % a for a in args)))
else:
call = _app_call(src)
if call is not None:
ref, args = call
parts.append("%s(%s)" % (ref, ", ".join('"%s"' % a for a in args)))
return ", ".join(_md_code(p) for p in parts)
def emit_docs_runtime(graph, nodes):
"""Emit ``gen/RUNTIME.md`` (0012 §5.1). Section order is fixed; ordering
within each section is source order of the decls. No timestamps."""
rv = _runtime_view(graph)
if rv is None:
return {}, []
runtime = rv.runtime
sf = graph.source_file
rt_name = runtime.name
systems = _str_list(runtime.props.get("systems"))
L = []
L.append("<!-- " + _header(sf, "runtime " + rt_name) + " -->")
L.append("")
L.append("# Runtime: %s" % rt_name)
L.append("")
L.append("Generated from `%s`. This document is a rendering of the"
% _header_file(sf))
L.append("`runtime %s` declaration — see" % rt_name)
L.append("[`docs/language/0012-lowering.md`](../../../../docs/language/0012-lowering.md)")
L.append("§5.1. Do not edit; regenerate from source.")
L.append("")
L.append("- **Systems:** %s" % ", ".join(_md_code(s) for s in systems))
L.append("")
L.append("## Indexes")
L.append("")
L.append("| Index | Source(s) | Normalize / Chunk | Trust | Emit |")
L.append("|-------|-----------|-------------------|-------|------|")
for idx in rv.indexes:
normalize = _ref(idx.props.get("normalize"))
norm_cell = _md_code(normalize) if normalize else "—"
if _index_is_pinned(idx):
rec = _record_entries(idx.props.get("trust"))
commit = rec.get("commit")
trust_cell = "`pinned` (commit `%s`)" % commit
else:
trust_cell = "—"
targets = _index_emit_targets(idx)
emit_cell = ", ".join(_md_code(t) for t in targets) if targets else "—"
L.append("| %s | %s | %s | %s | %s |"
% (_md_code(idx.name), _index_source_render(idx), norm_cell,
trust_cell, emit_cell))
L.append("")
L.append("## Streams")
L.append("")
L.append("| Stream | Source | Type | Retention / FPS |")
L.append("|--------|--------|------|-----------------|")
for st in rv.streams:
source = _ref(st.props.get("source"))
typ = _ref(st.props.get("type"))
retention = _lit(st.props.get("retention"))
fps = _lit(st.props.get("fps"))
if retention is not None:
rf_cell = "retention `%s`" % retention
elif fps is not None:
rf_cell = "fps `%s`" % fps
else:
rf_cell = "—"
L.append("| %s | %s | %s | %s |"
% (_md_code(st.name), _md_code(source), _md_code(typ), rf_cell))
L.append("")
L.append("## Fibers")
L.append("")
L.append("| Fiber | Engine | Input | Output | Policy |")
L.append("|-------|--------|-------|--------|--------|")
for fib in rv.fibers:
eng = _fiber_engine_name(fib)
inp = _ref(fib.props.get("input"))
out = _ref(fib.props.get("output"))
policy = _render_policy(fib)
L.append("| %s | %s | %s | %s | %s |"
% (_md_code(fib.name), _md_code(eng), _md_code(inp),
_md_code(out), policy))
L.append("")
L.append("## Surfaces")
L.append("")
L.append("| Surface | Mode | FPS | Input | Views |")
L.append("|---------|------|-----|-------|-------|")
for surf in rv.surfaces:
mode = _ref(surf.props.get("mode"))
fps = _lit(surf.props.get("fps"))
inputs_cell = _render_ref_list(surf.props.get("input"))
views = _str_list(surf.props.get("views"))
views_cell = ", ".join(_md_code(v) for v in views)
L.append("| %s | %s | %s | %s | %s |"
% (_md_code(surf.name), _md_code(mode), _md_code(fps),
inputs_cell, views_cell))
L.append("")
L.append("## Parallel groups")
L.append("")
L.append("| Group | Fibers | Strategy | Supervisor |")
L.append("|-------|--------|----------|------------|")
for par in rv.parallels:
members = _render_bare_ref_list(par.props.get("fibers"))
strategy = _lit(par.props.get("strategy"))
supervisor = _ref(par.props.get("supervisor"))
L.append("| %s | %s | %s | %s |"
% (_md_code(par.name), members, _md_code(strategy),
_md_code(supervisor)))
L.append("")
L.append("## Capability grants")
L.append("")
if rv.meshes:
L.append("Declared principal grant-sets (0011 §4.4, 0012 §5.1), attenuated per `mesh`.")
L.append("Read-only principals cannot acquire write/publish grants they were not given:")
L.append("")
for m in rv.meshes:
L.append("### mesh `%s`" % m.name)
L.append("")
L.append("| Principal | Role | Capabilities |")
L.append("|-----------|------|--------------|")
for nd in _by_kind(_children_of(graph, m.id), "node"):
role = _lit(nd.props.get("role"))
role_cell = _md_code(role) if role is not None else "—"
caps_cell = _render_ref_list(nd.props.get("capabilities")) or "—"
L.append("| %s | %s | %s |"
% (_md_code(nd.name), role_cell, caps_cell))
L.append("")
L.append("The implied daemon-channel uses follow from the stream sources:")
else:
L.append("No `mesh` or `capability` declarations in this runtime, so there are no declared")
L.append("principal grant-sets (0012 §5.1). The implied daemon-channel uses follow from the")
L.append("stream sources:")
L.append("")
L.append("| Principal / consumer | Used channel | Implied membrane |")
L.append("|----------------------|--------------|------------------|")
for st in rv.streams:
source = _ref(st.props.get("source"))
membrane = _implied_membrane(source)
L.append("| %s | %s | %s |"
% ("`stream %s`" % st.name, _md_code(source), membrane))
for fib in rv.fibers:
out = _ref(fib.props.get("output"))
if out is not None and out.startswith("artifacts."):
L.append("| %s | artifact capture | `filesystem` (fs-snapshotd) |"
% ("`fiber %s` (`output = %s`)" % (fib.name, out)))
L.append("")
L.append("> Membranes per [`docs/context/PROJECT_CONTEXT.md`](../../../../docs/context/PROJECT_CONTEXT.md)")
L.append("> and the daemon roster in [`docs/runtime/README.md`](../../../../docs/runtime/README.md).")
L.append("> eBPF policy manifests / OTel config / systemd units / surface launcher are")
L.append("> deferred targets (0012 §7).")
text = "\n".join(L) + "\n"
files = {"gen/RUNTIME.md": text}
entries = []
entries.append(ProvEntry(
artifact="gen/RUNTIME.md", region="header", source_file=sf,
decl="runtime " + rt_name, span=runtime.provenance.span,
emitter="docs.runtime", inputs_projection=_node_projection(runtime)))
for idx in rv.indexes:
entries.append(ProvEntry(
artifact="gen/RUNTIME.md", region="indexes/" + idx.name,
source_file=sf, decl="index " + idx.name, span=idx.provenance.span,
emitter="docs.runtime", inputs_projection=_node_projection(idx)))
for st in rv.streams:
entries.append(ProvEntry(
artifact="gen/RUNTIME.md", region="streams/" + st.name,
source_file=sf, decl="stream " + st.name, span=st.provenance.span,
emitter="docs.runtime", inputs_projection=_node_projection(st)))
for fib in rv.fibers:
entries.append(ProvEntry(
artifact="gen/RUNTIME.md", region="fibers/" + fib.name,
source_file=sf, decl="fiber " + fib.name, span=fib.provenance.span,
emitter="docs.runtime", inputs_projection=_node_projection(fib)))
for surf in rv.surfaces:
entries.append(ProvEntry(
artifact="gen/RUNTIME.md", region="surfaces/" + surf.name,
source_file=sf, decl="surface " + surf.name, span=surf.provenance.span,
emitter="docs.runtime", inputs_projection=_node_projection(surf)))
for par in rv.parallels:
entries.append(ProvEntry(
artifact="gen/RUNTIME.md", region="parallel/" + par.name,
source_file=sf, decl="parallel " + par.name, span=par.provenance.span,
emitter="docs.runtime", inputs_projection=_node_projection(par)))
for m in rv.meshes:
entries.append(ProvEntry(
artifact="gen/RUNTIME.md", region="meshes/" + m.name,
source_file=sf, decl="mesh " + m.name, span=m.provenance.span,
emitter="docs.runtime", inputs_projection=_node_projection(m)))
return files, entries
def _render_policy(fiber) -> str:
"""Render a fiber's ``policy { … }`` sub-block summary for RUNTIME.md.
The policy fields are projected from the fiber node's ``policy`` prop (a
``{"record": […]}`` value), in source order — e.g. ``strip_metadata = true``,
``max_pixels = "4K"``, ``formats = ["png", "webp"]``. The prop is attached by
:func:`enrich_graph` (the bare ``policy { … }`` config-block statement that
the prototype resolver leaves off the node; see that function)."""
pol = _fiber_policy_fields(fiber)
parts = []
for key, val in pol:
if isinstance(val, bool):
parts.append("%s = %s" % (key, "true" if val else "false"))
elif isinstance(val, list):
parts.append("%s = [%s]" % (key, ", ".join('"%s"' % v for v in val)))
else:
parts.append('%s = "%s"' % (key, val))
return "`" + "`, `".join(parts) + "`" if parts else "—"
def _fiber_policy_fields(fiber):
"""Project a fiber's policy fields in source order as ``[(name, value)]``.
Reads the fiber node's ``policy`` prop (a ``{"record": [...]}`` value attached
by :func:`enrich_graph`). Each entry projects its scalar value (bools,
strings, string lists)."""
out = []
pol = fiber.props.get("policy")
rec = pol.get("record") if isinstance(pol, dict) else None
if not isinstance(rec, list):
return out
for e in rec:
if not (isinstance(e, dict) and "assign" in e):
continue
name = e["assign"]
val = _scalar_prop(e.get("value"))
out.append((name, val))
return out
def _render_ref_list(prop) -> str:
"""Render a list of refs (``input = [stream.ebpfEvents, graph.workflow, …]``)
as comma-joined code spans."""
parts = []
if isinstance(prop, list):
for x in prop:
r = _ref(x)
if r is not None:
parts.append(r)
else:
r = _ref(prop)
if r is not None:
parts.append(r)
return ", ".join(_md_code(p) for p in parts)
def _render_bare_ref_list(prop) -> str:
return _render_ref_list(prop)
def _implied_membrane(source: "str | None") -> str:
"""The implied membrane string for a stream source channel (0012 §5.1)."""
if source is None:
return "—"
if source.startswith("agentGuardd."):
return "`ebpf` (agent-guardd)"
if source.startswith("agentpipe."):
return "`media` capture"
return "—"
def _stream_for_fiber_input(graph, rv, fiber):
"""Follow ``fiber.input`` to its in-runtime stream node (if any)."""
inp = _ref(fiber.props.get("input"))
if inp is None:
return None, inp
target_name = inp.split(".")[-1]
for st in rv.streams:
if st.name == target_name:
return st, inp
return None, inp
def emit_zig_daemoncfg(graph, nodes):
"""Emit one ``gen/zig/<fiber>.json`` per fiber (0012 §5.2). Key order is the
fixed schema order (NOT sorted); ``_generated`` is always first; an absent
optional field is omitted entirely (never ``null``)."""
rv = _runtime_view(graph)
if rv is None:
return {}, []
sf = graph.source_file
files = {}
entries = []
for fib in nodes:
cfg = _zig_config_for_fiber(graph, rv, fib, sf)
text = _emit_zig_json(cfg)
path = "gen/zig/%s.json" % fib.name
files[path] = text
entries.append(ProvEntry(
artifact=path, region=None, source_file=sf,
decl="fiber " + fib.name, span=fib.provenance.span,
emitter="zig.daemoncfg", inputs_projection=_node_projection(fib)))
return files, entries
def _zig_config_for_fiber(graph, rv, fib, sf):
"""Build the ordered config object for a fiber (0012 §5.2 table row order).
Returns a list of ``(key, value)`` pairs in canonical key order, with absent
optionals omitted. Nested objects are themselves ordered ``[(k, v)]`` lists,
tagged so the JSON emitter preserves order."""
eng = _fiber_engine_name(fib)
st, inp_ref = _stream_for_fiber_input(graph, rv, fib)
pairs = []
pairs.append(("_generated", _header(sf, "fiber " + fib.name)))
if eng is not None:
pairs.append(("engine", eng))
pairs.append(("engine_package", "packages." + eng))
input_pairs = []
if st is not None:
input_pairs.append(("stream", st.name))
st_source = _ref(st.props.get("source"))
if st_source is not None:
input_pairs.append(("source", st_source))
st_type = _ref(st.props.get("type"))
if st_type is not None:
input_pairs.append(("type", st_type))
st_fps = _lit(st.props.get("fps"))
if st_fps is not None:
input_pairs.append(("fps", _coerce_number(st_fps)))
if input_pairs:
pairs.append(("input", _Ordered(input_pairs)))
out_ref = _ref(fib.props.get("output"))
if out_ref is not None:
pairs.append(("output", _Ordered([("target", out_ref)])))
policy_pairs = _zig_policy_pairs(graph, fib)
if policy_pairs:
pairs.append(("policy", _Ordered(policy_pairs)))
budget = fib.props.get("budget")
if budget is not None:
pairs.append(("budget", _scalar_prop(budget)))
observe = fib.props.get("observe")
pairs.append(("observe", _scalar_prop(observe) if observe is not None else False))
return _Ordered(pairs)
def _zig_policy_pairs(graph, fib):
"""Project a fiber's ``policy { … }`` block into ordered ``(k, v)`` pairs.
Reads the fiber node's ``policy`` prop — a ``{"record": [{"assign","op",
"value"}, …]}`` value attached by :func:`enrich_graph` (the bare ``policy {
… }`` config-block App that the resolver leaves off the node otherwise). The
record preserves the source order of the fields, which is the §5.2 emission
order; each entry projects its scalar value (bools, strings, string lists)."""
pairs = []
for name, raw_value in _fiber_policy_fields(fib):
pairs.append((name, raw_value))
return pairs
def _coerce_number(value):
"""A numeric literal stored as a string ("10") becomes an int/float for JSON
(10), matching the §5.2 fixture (`"fps": 10`, not `"10"`)."""
if isinstance(value, str):
try:
if "." in value or "e" in value or "E" in value:
return float(value)
return int(value)
except ValueError:
return value
return value
def _scalar_prop(raw):
"""Project a recorded prop value to its scalar JSON value.
Handles ``{"lit": kind, "value": v}`` (numbers coerced), ``{"ref": r}``
(rendered as the dotted string), list props (recursively), and bare bools."""
if isinstance(raw, bool):
return raw
if isinstance(raw, dict):
if "lit" in raw:
kind = raw.get("lit")
val = raw.get("value")
if kind == "number":
return _coerce_number(val)
if kind == "bool" or kind == "boolean":
if isinstance(val, str):
return val == "true"
return bool(val)
return val
r = _ref(raw)
if r is not None:
return r
if isinstance(raw, list):
return [_scalar_prop(x) for x in raw]
return raw
class _Ordered:
"""A marker wrapping an ordered ``[(key, value)]`` list so the JSON emitter
preserves the canonical key order (0012 §5.2: key order is fixed schema order,
NOT sorted)."""
__slots__ = ("pairs",)
def __init__(self, pairs):
self.pairs = pairs
def _emit_zig_json(obj, indent=0) -> str:
"""Serialize an ``_Ordered`` config to the §5.2 JSON layout exactly.
Layout rules (matching gen/zig/mediaCompress.json byte-for-byte):
* 2-space indent, one member per line for objects;
* a one-line array for scalar lists (``["png", "webp"]``);
* ``: `` after keys, ``,`` line-trailing between members;
* trailing newline at end of file (added by the caller via this returning
the document body + "\\n")."""
body = _emit_zig_value(obj, 0)
return body + "\n"
def _emit_zig_value(val, level) -> str:
pad = " " * level
pad_in = " " * (level + 1)
if isinstance(val, _Ordered):
if not val.pairs:
return "{}"
lines = ["{"]
for i, (k, v) in enumerate(val.pairs):
comma = "," if i < len(val.pairs) - 1 else ""
lines.append("%s%s: %s%s"
% (pad_in, json.dumps(k, ensure_ascii=False),
_emit_zig_value(v, level + 1), comma))
lines.append(pad + "}")
return "\n".join(lines)
if isinstance(val, list):
inner = ", ".join(_emit_zig_value(x, level + 1) for x in val)
return "[%s]" % inner
return json.dumps(val, ensure_ascii=False)
_CATALOG_PLACEHOLDER_ROWS = {
"zigCorpus": [
("Sobeston/zig.guide", "chapter-1/hello-world.md",
"# Hello World\n\nCreate a file `hello.zig` and run it with `zig run hello.zig`."),
("zigimg/zigimg", "README.md",
"# zigimg\n\nZig library for reading and writing images in a variety of formats."),
],
}
def _catalog_row_id(owner_repo: str, n: int) -> str:
"""Deterministic placeholder row id: ``<repo-slug>#NNNN``."""
repo = owner_repo.rsplit("/", 1)[-1]
return "%s#%04d" % (repo, n)
def emit_catalog_jsonl(graph, nodes):
"""Emit ``gen/catalog/<index>.jsonl`` per index with ``emit ∋ catalog.jsonl``
(0012 §5.3b). Line 1 is the ``_generated`` header object (so the file stays
valid JSONL); subsequent lines are one JSON object per indexed item."""
sf = graph.source_file
files = {}
entries = []
for idx in nodes:
lines = []
header = {"_generated": _header(sf, "index " + idx.name)}
lines.append(json.dumps(header, separators=(",", ":"), ensure_ascii=False))
rows = _CATALOG_PLACEHOLDER_ROWS.get(idx.name, [])
per_repo = {}
for owner_repo, path, text in rows:
repo = owner_repo.rsplit("/", 1)[-1]
n = per_repo.get(repo, 0) + 1
per_repo[repo] = n
obj = {
"id": _catalog_row_id(owner_repo, n),
"source": "github:" + owner_repo,
"path": path,
"chunk": 0,
"text": text,
}
lines.append(json.dumps(obj, separators=(",", ":"), ensure_ascii=False))
text = "\n".join(lines) + "\n"
path = "gen/catalog/%s.jsonl" % idx.name
files[path] = text
entries.append(ProvEntry(
artifact=path, region=None, source_file=sf,
decl="index " + idx.name, span=idx.provenance.span,
emitter="catalog.jsonl", inputs_projection=_node_projection(idx)))
return files, entries
def _module_header(sf: str, decl: str, summary: str) -> list[str]:
L = ["# " + _header(sf, decl), "#"]
L.append("# " + summary)
L.append("# NixOS module fragment imported by nixosModules.<runtime> (0012 §4.3).")
return L
def _nix_literal(vprop: object) -> str | None:
"""Render a value-prop literal as Nix: string→quoted, bool→true/false,
number→bare, other scalars→quoted. None if ``vprop`` is not a literal."""
if not (isinstance(vprop, dict) and "lit" in vprop):
return None
kind = vprop.get("lit")
val = vprop.get("value")
if kind == "string":
return '"%s"' % val
if kind == "bool":
return "true" if str(val).lower() == "true" else "false"
if kind == "number":
return str(val)
return '"%s"' % val
def _bind_parts(prop: object) -> tuple[str, str, str | None] | None:
"""Decompose a Bind call value-prop (``loopback(...)`` / ``bind(...)``) into
``(addr, host_port, container_port)``; container_port is None for non-OCI
forms. Ports are the raw string literals. None if not a Bind call."""
call = _app_call(prop)
if call is None:
return None
ref, args = call
if ref == "loopback":
if len(args) == 1:
return ("127.0.0.1", args[0], None)
if len(args) == 2:
return ("127.0.0.1", args[0], args[1])
return None
if ref == "bind" and len(args) == 2:
return (args[0], args[1], None)
return None
def _render_bind(prop: object) -> str | None:
"""A Bind rendered as the joined ``host:port`` (or OCI ``host:hp:cp``) string
(ingress upstream, container ports). None if ``prop`` is not a Bind."""
parts = _bind_parts(prop)
if parts is None:
return None
addr, host_port, container_port = parts
if container_port is not None:
return "%s:%s:%s" % (addr, host_port, container_port)
return "%s:%s" % (addr, host_port)
def _secret_sops_name(secret_node: GraphNode) -> str | None:
"""The sops attribute key of a `secret` node: its `name` field literal."""
return _lit(secret_node.props.get("name"))
def _host_resource_dsn(hr_node: GraphNode) -> str | None:
"""The connection URL a ``hostResource.X.dsn`` lowers to (postgresql today;
a fixed per-kind template with `name` substituted — 0012 §2.4 projection)."""
kind = _lit(hr_node.props.get("kind"))
name = _lit(hr_node.props.get("name"))
if kind == "postgresql":
return "postgresql:///%s?host=/run/postgresql" % name
return None
def _accessor_nix(rv: "_RuntimeView", ref_dotted: str) -> str | None:
"""Render a 3-part accessor ref (``secret.X.path`` / ``hostResource.X.dsn``)
to its Nix expression, resolving X against the runtime's decls (the checker
has already proven X exists). None if not such a ref."""
parts = ref_dotted.split(".")
if len(parts) != 3:
return None
head, name, field = parts
if head == "secret" and field == "path":
for s in rv.secrets:
if s.name == name:
return 'config.sops.secrets."%s".path' % (_secret_sops_name(s) or name)
if head == "hostResource" and field == "dsn":
for hr in rv.host_resources:
if hr.name == name:
dsn = _host_resource_dsn(hr)
return '"%s"' % dsn if dsn is not None else None
return None
def _record_value_props(prop: object) -> list[tuple[str, object]]:
"""``[(name, value-prop)]`` of a config-block record prop, source order,
preserving ref/app values (unlike ``_record_entries`` which keeps literals)."""
out = []
rec = prop.get("record") if isinstance(prop, dict) else None
if isinstance(rec, list):
for e in rec:
if isinstance(e, dict) and "assign" in e:
out.append((e["assign"], e.get("value")))
return out
def _render_setting(rv: "_RuntimeView", vprop: object) -> str:
"""Render a service-option / value-prop to Nix: an accessor ref
(secret.X.path / hostResource.X.dsn) or a literal; other refs pass through."""
ref = _ref(vprop)
if ref is not None:
acc = _accessor_nix(rv, ref)
return acc if acc is not None else ref
lit = _nix_literal(vprop)
return lit if lit is not None else "null"
_SECRET_SOPS_OPTIONS = ("owner", "mode") # fixed emission order
def emit_sops_secrets(graph: Graph, nodes: list[GraphNode]) -> tuple[dict[str, str], list[ProvEntry]]:
"""One ``gen/nixos/sops.nix`` declaring every ``secret`` node's
``sops.secrets."<name>"`` entry (#2). owner/mode emitted only when present."""
if not nodes:
return {}, []
sf = graph.source_file
L = _module_header(sf, "secret " + nodes[0].name,
"sops-managed runtime secrets.")
L.append("{ config, ... }:")
L.append("{")
for sec in nodes:
name = _secret_sops_name(sec)
if name is None:
continue
L.append(' sops.secrets."%s" = {' % name)
for opt in _SECRET_SOPS_OPTIONS:
val = _lit(sec.props.get(opt))
if val is not None:
L.append(' %s = "%s";' % (opt, val))
L.append(" };")
L.append("}")
files = {"gen/nixos/sops.nix": "\n".join(L) + "\n"}
entries = [ProvEntry(
artifact="gen/nixos/sops.nix",
region='sops.secrets."%s"' % (_secret_sops_name(s) or s.name),
source_file=sf, decl="secret " + s.name, span=s.provenance.span,
emitter="sops.secrets", inputs_projection=_node_projection(s))
for s in nodes]
return files, entries
def emit_host_resources(graph: Graph, nodes: list[GraphNode]) -> tuple[dict[str, str], list[ProvEntry]]:
"""One ``gen/nixos/host-resources.nix`` provisioning the box's shared DBs
(#5). postgresql with create != false → services.postgresql.ensure*."""
pg = [hr for hr in nodes
if _lit(hr.props.get("kind")) == "postgresql"
and _lit(hr.props.get("create")) is not False]
if not pg:
return {}, []
sf = graph.source_file
L = _module_header(sf, "hostResource " + nodes[0].name,
"host-managed resources (shared services.postgresql).")
L.append("{ ... }:")
L.append("{")
L.append(" services.postgresql.ensureDatabases = [ %s ];"
% " ".join('"%s"' % _lit(hr.props.get("name")) for hr in pg))
L.append(" services.postgresql.ensureUsers = [")
for hr in pg:
L.append(' { name = "%s"; ensureDBOwnership = true; }'
% _lit(hr.props.get("name")))
L.append(" ];")
L.append("}")
files = {"gen/nixos/host-resources.nix": "\n".join(L) + "\n"}
entries = [ProvEntry(
artifact="gen/nixos/host-resources.nix",
region="services.postgresql/" + hr.name,
source_file=sf, decl="hostResource " + hr.name, span=hr.provenance.span,
emitter="host.resources", inputs_projection=_node_projection(hr))
for hr in pg]
return files, entries
def emit_nixos_service(graph: Graph, nodes: list[GraphNode]) -> tuple[dict[str, str], list[ProvEntry]]:
"""One ``gen/nixos/services.nix`` declaring every ``service`` node as
``services.<name> = { enable; package; [createPostgresqlDatabase;] settings
{ [HOSTNAME/PORT;] <options> } }`` (#1)."""
if not nodes:
return {}, []
rv = _runtime_view(graph)
sf = graph.source_file
L = _module_header(sf, "service " + nodes[0].name,
"nixpkgs-packaged systemd services.")
L.append("{ config, pkgs, ... }:")
L.append("{")
for svc in nodes:
L.append(" services.%s = {" % svc.name)
L.append(" enable = true;")
pkg = _ref(svc.props.get("package"))
if pkg is not None:
L.append(" package = %s;" % pkg)
db = _ref(svc.props.get("database"))
if db is not None:
L.append(" createPostgresqlDatabase = true;")
user = _lit(svc.props.get("user"))
if user is not None:
L.append(' user = "%s";' % user)
state_dir = _lit(svc.props.get("stateDir"))
if state_dir is not None:
L.append(' stateDir = "%s";' % state_dir)
bind = _bind_parts(svc.props.get("bind"))
opt_entries = _record_value_props(svc.props.get("options"))
if bind is not None or opt_entries:
L.append(" settings = {")
if bind is not None:
addr, host_port, _cp = bind
L.append(' HOSTNAME = "%s";' % addr)
L.append(" PORT = %s;" % host_port)
for name, vprop in opt_entries:
L.append(" %s = %s;" % (name, _render_setting(rv, vprop)))
L.append(" };")
L.append(" };")
L.append("}")
files = {"gen/nixos/services.nix": "\n".join(L) + "\n"}
entries = [ProvEntry(
artifact="gen/nixos/services.nix", region="services." + svc.name,
source_file=sf, decl="service " + svc.name, span=svc.provenance.span,
emitter="nixos.service", inputs_projection=_node_projection(svc))
for svc in nodes]
return files, entries
def _render_upstream(prop: object) -> str | None:
"""An ingress `upstream` (Bind | String): the string literal verbatim, or a
Bind rendered host:port."""
lit = _lit(prop)
if lit is not None:
return lit
return _render_bind(prop)
def emit_caddy_ingress(graph: Graph, nodes: list[GraphNode]) -> tuple[dict[str, str], list[ProvEntry]]:
"""One ``gen/caddy/ingress.nix`` — a Caddy virtualHost per ``ingress`` node
(#4): ``import <tls>`` (if any) + ``reverse_proxy <upstream>`` + raw
extraConfig."""
if not nodes:
return {}, []
sf = graph.source_file
L = _module_header(sf, "ingress " + nodes[0].name,
"Caddy HTTP reverse-proxy virtual hosts.")
L.append("{ ... }:")
L.append("{")
for ing in nodes:
domain = _lit(ing.props.get("domain"))
upstream = _render_upstream(ing.props.get("upstream"))
tls = _lit(ing.props.get("tls"))
extra = _lit(ing.props.get("extraConfig"))
L.append(' services.caddy.virtualHosts."%s".extraConfig = \'\'' % domain)
if tls is not None:
L.append(" import %s" % tls)
L.append(" reverse_proxy %s" % upstream)
if extra is not None:
for raw_line in extra.splitlines():
L.append(" " + raw_line)
L.append(" '';")
L.append("}")
files = {"gen/caddy/ingress.nix": "\n".join(L) + "\n"}
entries = [ProvEntry(
artifact="gen/caddy/ingress.nix",
region='virtualHosts."%s"' % (_lit(ing.props.get("domain")) or ing.name),
source_file=sf, decl="ingress " + ing.name, span=ing.provenance.span,
emitter="caddy.ingress", inputs_projection=_node_projection(ing))
for ing in nodes]
return files, entries
_BYTES_SUFFIX_TO_DOCKER = {"GB": "g", "MB": "m", "KB": "k", "B": ""}
def _render_memory_flag(mem_prop: object) -> str | None:
"""``memory = 2GB`` → ``--memory=2g`` (Bytes literal, suffix→Docker form)."""
val = _lit(mem_prop)
if val is None:
return None
s = str(val).strip()
for suffix, docker in _BYTES_SUFFIX_TO_DOCKER.items():
if suffix and s.endswith(suffix):
return "--memory=%s%s" % (s[: -len(suffix)].strip(), docker)
return "--memory=%s" % s
def _container_extra_options(c: GraphNode) -> list[str]:
"""extraOptions Docker flags in fixed order: --memory, --network,
--health-cmd, then the author's extraOptions verbatim."""
opts = []
mem = _render_memory_flag(c.props.get("memory"))
if mem is not None:
opts.append(mem)
network = _lit(c.props.get("network"))
if network is not None:
opts.append("--network=%s" % network)
health = _lit(c.props.get("healthCmd"))
if health is not None:
opts.append("--health-cmd=%s" % health)
opts.extend(_str_list(c.props.get("extraOptions")))
return opts
def _nix_str_array(values: list[str]) -> str:
return "[ %s ]" % " ".join('"%s"' % v for v in values)
def emit_oci_containers(graph: Graph, nodes: list[GraphNode]) -> tuple[dict[str, str], list[ProvEntry]]:
"""One ``gen/nixos/oci-containers.nix`` collecting every ``container`` node
into ``virtualisation.oci-containers.containers`` (#6).
memory/network/healthCmd synthesize into extraOptions Docker flags."""
if not nodes:
return {}, []
rv = _runtime_view(graph)
sf = graph.source_file
L = _module_header(sf, "container " + nodes[0].name,
"OCI/Docker containers (memory/network/healthCmd → extraOptions).")
L.append("{ config, ... }:")
L.append("{")
L.append(" virtualisation.oci-containers.containers = {")
for c in nodes:
L.append(" %s = {" % c.name)
L.append(" image = %s;" % _nix_literal(c.props.get("image")))
ports = c.props.get("ports")
if isinstance(ports, list) and ports:
L.append(" ports = %s;"
% _nix_str_array([_render_bind(p) for p in ports]))
env = _record_value_props(c.props.get("environment"))
if env:
L.append(" environment = {")
for k, vprop in env:
L.append(" %s = %s;" % (k, _render_setting(rv, vprop)))
L.append(" };")
ef = c.props.get("environmentFiles")
if isinstance(ef, list) and ef:
paths = [_accessor_nix(rv, _ref(x)) or (_ref(x) or "") for x in ef]
L.append(" environmentFiles = [ %s ];" % " ".join(paths))
vols = _str_list(c.props.get("volumes"))
if vols:
L.append(" volumes = %s;" % _nix_str_array(vols))
extra = _container_extra_options(c)
if extra:
L.append(" extraOptions = %s;" % _nix_str_array(extra))
L.append(" };")
L.append(" };")
L.append("}")
files = {"gen/nixos/oci-containers.nix": "\n".join(L) + "\n"}
entries = [ProvEntry(
artifact="gen/nixos/oci-containers.nix",
region="oci-containers.containers." + c.name,
source_file=sf, decl="container " + c.name, span=c.provenance.span,
emitter="oci.containers", inputs_projection=_node_projection(c))
for c in nodes]
return files, entries
def emit_deferred(graph, nodes):
"""A deferred target's emitter (ebpf.policy / otel.config / systemd.units /
surface.launcher). Produces NOTHING today — an explicit, documented no-op,
not an error (0012 §2.2, §3.2.5, §7). The surface launcher's spine stub is
emitted by :func:`emit_nix_spine`, not here."""
return {}, []
_CONFIG_BLOCK_FIELDS = {
"fiber": frozenset(("policy",)),
"service": frozenset(("options",)), # service options { … } (#1)
"container": frozenset(("environment",)), # container environment { … } (#6)
}
def _config_block_name(app) -> "str | None":
"""The field name of a bare config-block App (``policy { … }``): a single
dotted ref with a ``record`` body and no call args. Returns the ref's single
segment, or ``None`` if ``app`` is not a bare config block."""
if not isinstance(app, P.App):
return None
if app.args is not None or app.record is None:
return None
parts = app.ref.parts
if len(parts) != 1:
return None
return parts[0]
def enrich_graph(graph, items) -> None:
"""Attach dropped config sub-blocks (e.g. a fiber's ``policy { … }``) to
their graph nodes, in place. Pure (no IO/clock/randomness); idempotent; adds
no nodes/edges. Run by the lowering driver after resolve, before lower()."""
from .resolve import _value_to_props # local import: avoid a cycle at import
index = {}
for _n in graph.nodes:
if _n.provenance is None:
continue
_h = _n.id.find("#")
if _h != -1:
index.setdefault(_n.id[_h:], _n)
def walk(decl, chain):
node = index.get("#" + "/".join(chain))
if node is not None:
allowed = _CONFIG_BLOCK_FIELDS.get(decl.kind, frozenset())
for st in decl.body:
name = _config_block_name(st)
if name is not None and name in allowed and name not in node.props:
node.props[name] = _value_to_props(st)
for st in decl.body:
if isinstance(st, P.Decl):
walk(st, chain + [st.name])
for it in items:
if isinstance(it, P.Decl):
walk(it, [it.name])
def _eventd_log_path(rv) -> str:
"""The per-runtime hash-chained log path (eventd design §"Daemon shape")."""
return "var/lib/%s/eventd/log.jsonl" % rv.runtime.name
def emit_eventd_config(graph, nodes):
"""Emit ``gen/eventd.json`` — the per-runtime log location + boot contract
(#18: "per-runtime log path as a 0012 lowering output"). Selected when the
runtime declares any memory/workflow (the log's in-language consumers)."""
rv = _runtime_view(graph)
if rv is None:
return {}, []
sf = graph.source_file
rt = rv.runtime
cfg = _Ordered([
("_generated", _header(sf, "runtime " + rt.name)),
("log", _eventd_log_path(rv)),
("format", "jsonl-hashchain-v1"),
("verify_on_boot", True),
("writer", "agent-supervisord"),
])
path = "gen/eventd.json"
files = {path: _emit_zig_json(cfg)}
entries = [ProvEntry(
artifact=path, region=None, source_file=sf,
decl="runtime " + rt.name, span=rt.provenance.span,
emitter="eventd.config", inputs_projection=_node_projection(rt))]
return files, entries
def emit_memory_store(graph, nodes):
"""Emit one ``gen/memory/<name>.json`` per memory decl (#24, 0014): the
store config memoryd / agent-supervisord loads — mined source, distiller,
fold partition (scope), retention, recall artifacts, and the eventd log
the entries ride on."""
rv = _runtime_view(graph)
if rv is None:
return {}, []
sf = graph.source_file
files = {}
entries = []
for mem in nodes:
pairs = [("_generated", _header(sf, "memory " + mem.name))]
src_prop = mem.props.get("source")
if isinstance(src_prop, list):
srcs = [_ref(x) for x in src_prop if _ref(x) is not None]
if srcs:
pairs.append(("source", srcs))
else:
src = _ref(src_prop)
if src is not None:
pairs.append(("source", src))
schema_ref = _ref(mem.props.get("schema"))
if schema_ref is not None:
pairs.append(("schema", schema_ref)) # binds entry type T (0014)
mine = _ref(mem.props.get("mine"))
if mine is not None:
pairs.append(("mine", mine))
scope = _lit(mem.props.get("scope"))
pairs.append(("scope", scope if scope is not None else "agent"))
retention = _lit(mem.props.get("retention"))
if retention is not None:
pairs.append(("retention", retention))
emit_targets = []
emit_prop = mem.props.get("emit")
if isinstance(emit_prop, list):
emit_targets = [_ref(x) for x in emit_prop if _ref(x) is not None]
if emit_targets:
pairs.append(("emit", emit_targets))
pairs.append(("log", _eventd_log_path(rv)))
path = "gen/memory/%s.json" % mem.name
files[path] = _emit_zig_json(_Ordered(pairs))
entries.append(ProvEntry(
artifact=path, region=None, source_file=sf,
decl="memory " + mem.name, span=mem.provenance.span,
emitter="memory.store", inputs_projection=_node_projection(mem)))
return files, entries
def _otp_slug(name: str) -> str:
"""A runtime name as a legal Erlang module atom prefix — strictly
``[a-z][a-z0-9_]*``. Explicit ASCII ranges, NOT str.isalnum(): Python's
test is Unicode-aware (Arabic-Indic digits etc. pass it), and a non-ASCII
module name is rejected by erlc. 'v' prefixed when not starting with a
letter (module name MUST match filename — OTP rule)."""
s = "".join(c if ("a" <= c <= "z" or "0" <= c <= "9") else "_"
for c in name.lower())
if not s or not ("a" <= s[0] <= "z"):
s = "v" + s
return s
def _otp_members(rv, par):
"""The resolved members of a parallel group's `fibers` list, in declared
order: (name, kind, config) — fibers carry their gen/zig config path,
surfaces have none (launcher deferred, 0012 §7). Members are in-runtime
decls (closed-world checked), so unresolved names are simply skipped."""
fibers = {f.name for f in rv.fibers}
surfaces = {s.name for s in rv.surfaces}
out = []
members = par.props.get("fibers")
if isinstance(members, list):
for m in members:
name = _ref(m)
if name is None:
continue
if name in fibers:
out.append((name, "fiber", "gen/zig/%s.json" % name))
elif name in surfaces:
out.append((name, "surface", None))
return out
_OTP_WORKER_BODY = """-module(vaked_fiber_worker).
-behaviour(gen_server).
-export([start_link/1]).
-export([init/1, handle_call/3, handle_cast/2, handle_info/2]).
-define(TICK_MS, 5000).
start_link(#{name := Name} = Args) ->
gen_server:start_link({local, Name}, ?MODULE, Args, []).
init(#{name := Name, kind := Kind} = Args) ->
logger:info("vaked ~p ~p up (placeholder; daemon port pending)",
[Kind, Name]),
erlang:send_after(?TICK_MS, self(), tick),
{ok, Args}.
handle_call(_Req, _From, State) ->
{reply, ok, State}.
handle_cast(_Msg, State) ->
{noreply, State}.
handle_info(tick, #{name := Name} = State) ->
logger:debug("vaked heartbeat ~p", [Name]),
erlang:send_after(?TICK_MS, self(), tick),
{noreply, State}.
"""
def emit_otp_supervision(graph, nodes):
"""Emit the OTP supervision tree (#19, Track C; design:
docs/superpowers/specs/2026-06-12-otp-supervision-lowering-design.md):
one ``gen/otp/<runtime_slug>_sup.erl`` supervisor (child spec per member
of each ``parallel … supervisor = otp`` group, declared order —
byte-determinism only, no restart-coupling claim) plus the generic
placeholder worker ``gen/otp/vaked_fiber_worker.erl``.
v0 strategy mapping: ``"supervised-dag"`` (and anything else) lowers to
``one_for_one`` — downstream consistency is RFC 0004's job
(stale_dependency pausing); eager per-chain ``rest_for_one`` is the
edge-aware follow-up."""
rv = _runtime_view(graph)
if rv is None:
return {}, []
sf = graph.source_file
rt = rv.runtime
slug = _otp_slug(rt.name)
child_blocks = []
entries = []
sup_path = "gen/otp/%s_sup.erl" % slug
seen = set() # OTP rejects duplicate child ids at boot; first wins
for par in nodes:
for name, kind, config in _otp_members(rv, par):
if name in seen:
continue
seen.add(name)
cfg = '"%s"' % config if config is not None else "none"
child_blocks.append(
" #{id => '%s',\n"
" start => {vaked_fiber_worker, start_link,\n"
" [#{name => '%s', kind => %s,\n"
" config => %s}]},\n"
" restart => permanent, shutdown => 5000,\n"
" type => worker,\n"
" modules => [vaked_fiber_worker]}"
% (name, name, kind, cfg))
entries.append(ProvEntry(
artifact=sup_path, region="parallel/" + par.name, source_file=sf,
decl="parallel " + par.name, span=par.provenance.span,
emitter="otp.supervision",
inputs_projection=_node_projection(par)))
sup_text = "\n".join([
"%% " + _header(sf, "runtime " + rt.name),
"%%",
"%% otp.supervision (0012 3.4; Track C #19). v0 strategy: one_for_one -",
"%% downstream consistency is RFC 0004's job (stale_dependency pausing);",
"%% eager per-chain rest_for_one is the edge-aware follow-up (design",
"%% 2026-06-12-otp-supervision-lowering-design.md).",
"-module(%s_sup)." % slug,
"-behaviour(supervisor).",
"",
"-export([start_link/0, init/1]).",
"",
"start_link() ->",
" supervisor:start_link({local, ?MODULE}, ?MODULE, []).",
"",
"init([]) ->",
" SupFlags = #{strategy => one_for_one, intensity => 3,"
" period => 10},",
" Children = [",
",\n".join(child_blocks),
" ],",
" {ok, {SupFlags, Children}}.",
"",
])
worker_path = "gen/otp/vaked_fiber_worker.erl"
worker_text = "\n".join([
"%% " + _header(sf, "runtime " + rt.name),
"%%",
"%% Generic placeholder worker: heartbeats until the member's Zig",
"%% daemon port replaces it. Deliberately does NOT write eventd (the",
"%% canonical-hash byte contract stays with the Python oracle; the",
"%% daemon owns the single writer, RFC 0004).",
_OTP_WORKER_BODY,
])
files = {sup_path: sup_text, worker_path: worker_text}
entries.append(ProvEntry(
artifact=worker_path, region=None, source_file=sf,
decl="runtime " + rt.name, span=rt.provenance.span,
emitter="otp.supervision", inputs_projection=_node_projection(rt)))
return files, entries
def _budget_prop(prop):
"""The Budget auxiliary type admits BOTH forms — a ref to a `budget` decl
(``budget = budget.swe`` → emitted as the ref string) and an inline budget
record (``budget = { tokens = 10 … }`` → emitted as an ordered object).
Dropping either form would boot the supervisor without declared limits."""
r = _ref(prop)
if r is not None:
return r
rec = prop.get("record") if isinstance(prop, dict) else None
if isinstance(rec, list):
pairs = []
for e in rec:
if isinstance(e, dict) and "assign" in e:
v = e.get("value")
lit = _lit(v)
if lit is None:
continue
if isinstance(v, dict) and v.get("lit") == "number":
lit = _coerce_number(lit)
pairs.append((e["assign"], lit))
if pairs:
return _Ordered(pairs)
return None
def _workflow_projection(wf, steps, edges) -> dict:
"""The provenance inputs projection for a workflow artifact: the artifact
depends on the workflow record AND its step nodes AND the routes_to edges
(they produce `steps`/`edges`/`depth`), so all of them key the inputsHash —
editing a step's agent or rewiring the DAG must change the hash."""
proj = _node_projection(wf)
proj["steps"] = [_node_projection(s) for s in steps]
proj["edges"] = [{"from": a, "to": b} for a, b in edges]
return proj
def _workflow_steps_edges(graph, wf):
"""(steps, edges) of a workflow node: its `node` children in declaration
order and the routes_to edges among them as (from_name, to_name) pairs."""
steps = [n for n in _children_of(graph, wf.id) if n.kind == "node"]
ids = {n.id: n.name for n in steps}
edges = [(ids[e.source], ids[e.target])
for e in graph.edges
if e.label == "routes_to" and e.source in ids and e.target in ids]
return steps, edges
def _workflow_depth(steps, edges) -> int:
"""Critical path counted in steps (same semantics as the 0015 checker;
lower runs only on a checked graph, so the edge set is a DAG)."""
succ = {s.name: [] for s in steps}
for a, b in edges:
succ[a].append(b)
memo = {}
def depth(name):
if name not in memo:
memo[name] = 1 + max((depth(n) for n in succ[name]), default=0)
return memo[name]
return max((depth(s.name) for s in steps), default=0)
def emit_workflow_spec(graph, nodes):
"""Emit one ``gen/workflow/<name>.json`` per workflow decl (#27, 0015):
the AOT spec agent-supervisord loads at boot — trigger, budget, the step
roster (agent / input / output / retries), the DAG edges, the precomputed
critical-path depth (0013 Pass 1 output), and the eventd log the run's
step events append to (RFC 0004)."""
rv = _runtime_view(graph)
if rv is None:
return {}, []
sf = graph.source_file
files = {}
entries = []
for wf in nodes:
steps, edges = _workflow_steps_edges(graph, wf)
pairs = [("_generated", _header(sf, "workflow " + wf.name))]
on = _lit(wf.props.get("on"))
if on is not None:
pairs.append(("on", on))
budget = _budget_prop(wf.props.get("budget"))
if budget is not None:
pairs.append(("budget", budget))
max_depth = _lit(wf.props.get("maxDepth"))
if max_depth is not None:
pairs.append(("maxDepth", _coerce_number(max_depth)))
step_objs = []
for st in steps:
sp = [("name", st.name)]
agent = _ref(st.props.get("agent"))
if agent is not None:
sp.append(("agent", agent))
for fld in ("input", "output"):
r = _ref(st.props.get(fld))
if r is not None:
sp.append((fld, r))
retries = _lit(st.props.get("retries"))
if retries is not None:
sp.append(("retries", _coerce_number(retries)))
sbudget = _budget_prop(st.props.get("budget"))
if sbudget is not None:
sp.append(("budget", sbudget))
step_objs.append(_Ordered(sp))
pairs.append(("steps", step_objs))
pairs.append(("edges", [_Ordered([("from", a), ("to", b)])
for a, b in edges]))
pairs.append(("depth", _workflow_depth(steps, edges)))
pairs.append(("log", _eventd_log_path(rv)))
path = "gen/workflow/%s.json" % wf.name
files[path] = _emit_zig_json(_Ordered(pairs))
entries.append(ProvEntry(
artifact=path, region=None, source_file=sf,
decl="workflow " + wf.name, span=wf.provenance.span,
emitter="workflow.spec",
inputs_projection=_workflow_projection(wf, steps, edges)))
return files, entries
def _nix_str(s: str) -> str:
"""A safe Nix double-quoted string literal: neutralizes the three
sequences that are active inside `"..."` — backslash (first), `"`, and
`${` antiquotation — so host-controlled values can never inject Nix
(the issue #7 splice class). Backslash MUST be escaped before the others."""
return '"' + (s.replace("\\", "\\\\")
.replace('"', '\\"')
.replace("${", "\\${")) + '"'
def _is_nix_bare_ident(s: str) -> bool:
"""True iff ``s`` is a Nix *bare* attribute identifier
(``[A-Za-z_][A-Za-z0-9_'-]*``) — emittable as an attrpath segment with no
quoting and no nesting."""
if not s:
return False
c0 = s[0]
if not (c0.isascii() and (c0.isalpha() or c0 == "_")):
return False
return all(c.isascii() and (c.isalnum() or c in "_'-") for c in s[1:])
def _nix_attr_key(name: str) -> str:
"""Render ``name`` as a SINGLE Nix attribute key (0012; #7 lowering half).
A bare Nix identifier is emitted verbatim; anything else — most importantly a
dotted ref like ``pkgs.umami`` that would otherwise splice into a NESTED
attrpath (`pkgs.umami = …` ≡ `pkgs = { umami = …; }`, the #7 worked-example
bug) — is emitted as a quoted string key, so it stays exactly one attribute
and the emitted Nix is structurally well-formed regardless of the name. The
checker (#8/branch-B) is the place a dangling/dotted ref should be rejected;
this keeps the lowerer from minting invalid Nix in the meantime."""
return name if _is_nix_bare_ident(name) else _nix_str(name)
def emit_colmena_hive(graph, nodes):
"""Emit ``gen/colmena/hive.nix`` (#51): one colmena node per `host` decl,
so `colmena apply` deploys the runtime's nixosModules to its declared
boxes — the declare -> check -> lower -> deploy loop. Presence-gated.
Mapping per host decl: `deploy = "ssh://user@addr"` -> deployment.
targetHost "user@addr"; `deploy = "local"` (or absent) -> local
deployment. The node imports the runtime's NixOS module by the same
interface-only path the spine declares (0012 §4.3); `meta.nixpkgs` uses
`<nixpkgs>` in this standalone form — the flake remains the pinned entry
point (documented in the header)."""
rv = _runtime_view(graph)
if rv is None:
return {}, []
sf = graph.source_file
rt = rv.runtime
lines = []
lines.append("# %s" % _header(sf, "runtime " + rt.name))
lines.append("#")
lines.append("# colmena hive (#51): `colmena apply` deploys nixosModules.%s"
% rt.name)
lines.append("# to the declared hosts. Standalone form pins nothing itself —")
lines.append("# the flake (the spine) is the pinned entry point; <nixpkgs>")
lines.append("# here is the documented interface-only escape (0012 §4.3).")
lines.append("{")
lines.append(" meta = {")
lines.append(" nixpkgs = <nixpkgs>;")
lines.append(" };")
lines.append("")
entries = []
for i, h in enumerate(nodes):
if i:
lines.append("") # blank line BETWEEN nodes only
system = _lit(h.props.get("system")) or ""
deploy = _lit(h.props.get("deploy"))
lines.append(" %s = { ... }: {" % _nix_str(h.name))
if deploy is None or deploy == "local":
lines.append(" deployment.allowLocalDeployment = true;")
lines.append(" deployment.targetHost = null;")
else:
target = deploy[6:] if deploy.startswith("ssh://") else deploy
lines.append(" deployment.targetHost = %s;" % _nix_str(target))
lines.append(" nixpkgs.system = %s;" % _nix_str(system))
lines.append(" # interface-only module path, exactly as the spine")
lines.append(" # declares nixosModules.%s (0012 §4.3)." % rt.name)
lines.append(" imports = [ ../../nixos/%s.nix ];" % rt.name)
lines.append(" };")
entries.append(ProvEntry(
artifact="gen/colmena/hive.nix", region="host/" + h.name,
source_file=sf, decl="host " + h.name, span=h.provenance.span,
emitter="colmena.hive", inputs_projection=_node_projection(h)))
lines.append("}")
files = {"gen/colmena/hive.nix": "\n".join(lines) + "\n"}
return files, entries
def _principal_network_grant(graph, principal):
"""The `network.<grant>` a mesh ``node <principal>`` holds, if any — its
position in the builtin `network` lattice (none < loopback < lan < egress).
Best effort: returns e.g. ``"network.loopback"`` or None."""
if not principal:
return None
for n in graph.nodes_sorted():
if n.kind == "node" and n.name == principal:
caps = n.props.get("capabilities")
if isinstance(caps, list):
for c in caps:
r = _ref(c)
if r is not None and r.split(".", 1)[0] == "network":
return r
return None
def _host_cidr(host: str) -> "str | None":
"""The single-host CIDR for a bare ``host`` literal, family-aware: ``/32``
for IPv4, ``/128`` for IPv6. A host already carrying a ``/prefix`` is kept
verbatim. Returns None for a host that is neither a valid IP literal nor an
explicit CIDR — a non-IP destination is not attestable at the packet layer
(decide() denies it), so it must not be widened into a subnet."""
if "/" in host:
try:
ipaddress.ip_network(host, strict=False)
except ValueError:
return None
return host
try:
ip = ipaddress.ip_address(host)
except ValueError:
return None
return "%s/%d" % (host, 128 if ip.version == 6 else 32)
def _egress_rule(call):
"""One allow-rule from an ``egress(host, port)`` app-call → an ordered dict
``{proto, host, cidr, port}``. The host is pinned to a single-address CIDR
(``/32`` IPv4, ``/128`` IPv6) so an allow rule never widens into a subnet.
Returns None for a malformed call (non-string host, non-numeric port, or a
host that is neither a valid IP literal nor an explicit CIDR)."""
if call is None:
return None
ref, args = call
if ref != "egress" or len(args) < 2:
return None
host = args[0]
if not isinstance(host, str):
return None
try:
port = int(args[1])
except (TypeError, ValueError):
return None
cidr = _host_cidr(host)
if cidr is None:
return None
return {"proto": "tcp", "host": host, "cidr": cidr, "port": port}
def emit_ebpf_policy(graph, nodes):
"""Emit ``gen/ebpf.policy.json`` — the compiled egress policy agent-guardd
loads (0012 §7, now realized). One ``membranes[]`` entry per ``network``
decl: deny-by-default posture + the host:port allow-set, tagged with the
principal and its ``network.<grant>`` lattice position. One provenance entry
per membrane (``region`` = the membrane name)."""
sf = graph.source_file
rv = _runtime_view(graph)
rt_name = rv.runtime.name if rv is not None else ""
membranes = []
entries = []
for net in nodes:
principal = _lit(net.props.get("principal"))
default = _lit(net.props.get("default")) or "deny"
allow = []
allow_prop = net.props.get("allow")
if isinstance(allow_prop, list):
for item in allow_prop:
rule = _egress_rule(_app_call(item))
if rule is not None:
allow.append(rule)
membrane = {
"membrane": net.name,
"principal": principal,
"grant": _principal_network_grant(graph, principal),
"default": default,
"allow": allow,
}
observe = _ref(net.props.get("observe"))
if observe is not None:
membrane["observe"] = observe
membranes.append(membrane)
entries.append(ProvEntry(
artifact="gen/ebpf.policy.json", region=net.name, source_file=sf,
decl="network " + net.name, span=net.provenance.span,
emitter="ebpf.policy", inputs_projection=_node_projection(net)))
doc = {
"_generated": _header(sf, "runtime " + rt_name),
"version": 1,
"runtime": rt_name,
"membranes": membranes,
}
text = json.dumps(doc, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
return {"gen/ebpf.policy.json": text}, entries
@dataclass
class _Registered:
target: str
emitter: object
deferred: bool = False
REGISTRY = {
"nix.spine": _Registered("nix.spine", emit_nix_spine),
"docs.runtime": _Registered("docs.runtime", emit_docs_runtime),
"catalog.jsonl": _Registered("catalog.jsonl", emit_catalog_jsonl),
"catalog.sqlite": _Registered("catalog.sqlite", emit_deferred, deferred=True),
"crabcc.index": _Registered("crabcc.index", emit_nix_spine), # folded into spine
"zig.daemoncfg": _Registered("zig.daemoncfg", emit_zig_daemoncfg),
"sops.secrets": _Registered("sops.secrets", emit_sops_secrets),
"nixos.service": _Registered("nixos.service", emit_nixos_service),
"host.resources": _Registered("host.resources", emit_host_resources),
"caddy.ingress": _Registered("caddy.ingress", emit_caddy_ingress),
"oci.containers": _Registered("oci.containers", emit_oci_containers),
"eventd.config": _Registered("eventd.config", emit_eventd_config),
"memory.store": _Registered("memory.store", emit_memory_store),
"workflow.spec": _Registered("workflow.spec", emit_workflow_spec),
"otp.supervision": _Registered("otp.supervision", emit_otp_supervision),
"colmena.hive": _Registered("colmena.hive", emit_colmena_hive),
"ebpf.policy": _Registered("ebpf.policy", emit_ebpf_policy),
"otel.config": _Registered("otel.config", emit_deferred, deferred=True),
"systemd.units": _Registered("systemd.units", emit_deferred, deferred=True),
"shell.cmd": _Registered("shell.cmd", emit_shell),
"surface.launcher": _Registered("surface.launcher", emit_deferred, deferred=True),
}
@dataclass
class LowerResult:
files: dict # path -> str | bytes
provenance: dict # the provenance.json document (JSON-able)
entries: list # the flat list of ProvEntry (debug/tests)
def lower(graph, items=None) -> LowerResult:
"""Lower a *validated* graph to artifacts + a provenance manifest (0012).
Pure: no IO, no clock, no randomness (the caller writes ``result.files``).
When ``items`` (the parsed AST the graph was built from) is supplied, the
driver-side :func:`enrich_graph` pass runs first to recover load-bearing
config sub-blocks (a fiber's ``policy { … }``) the minimal resolver drops;
this is in-memory only and never touches ``vakedc parse``'s graph JSON. The
per-target emitters themselves remain pure functions of ``(graph, nodes)``.
Selection is entirely a read of the graph (0012 §3.3):
* ``nix.spine`` ALWAYS (the crabcc index derivation is folded in);
* ``docs.runtime`` on presence of the runtime node;
* ``zig.daemoncfg`` for each fiber;
* ``catalog.jsonl`` for each index whose ``emit`` contains ``catalog.jsonl``;
* ``crabcc.index`` provenance for each index whose ``emit`` contains
``nix.derivation`` (emitted inside the spine);
* deferred targets emit nothing.
"""
if items is not None:
enrich_graph(graph, items)
rv = _runtime_view(graph)
files = {}
all_entries = []
def _run(target, nodes):
reg = REGISTRY[target]
f, ents = reg.emitter(graph, nodes)
for path, content in f.items():
files[path] = content
all_entries.extend(ents)
if rv is None:
return LowerResult(files={}, provenance={
"version": 1, "source": graph.source_file, "artifacts": {},
}, entries=[])
_run("nix.spine", [rv.runtime])
_run("docs.runtime", [rv.runtime])
if rv.fibers:
_run("zig.daemoncfg", rv.fibers)
jsonl_indexes = [i for i in rv.indexes
if "catalog.jsonl" in _index_emit_targets(i)]
if jsonl_indexes:
_run("catalog.jsonl", jsonl_indexes)
if rv.secrets:
_run("sops.secrets", rv.secrets)
if rv.host_resources:
_run("host.resources", rv.host_resources)
if rv.services:
_run("nixos.service", rv.services)
if rv.ingresses:
_run("caddy.ingress", rv.ingresses)
if rv.containers:
_run("oci.containers", rv.containers)
otp_parallels = [p for p in rv.parallels
if _ref(p.props.get("supervisor")) == "otp"]
if otp_parallels:
_run("otp.supervision", otp_parallels)
if rv.workflows:
_run("workflow.spec", rv.workflows)
if rv.memories:
_run("memory.store", rv.memories)
if rv.memories or rv.workflows:
_run("eventd.config", [rv.runtime])
if rv.networks:
_run("ebpf.policy", rv.networks)
if rv.hosts:
_run("colmena.hive", rv.hosts)
provenance = _build_provenance(graph, all_entries)
return LowerResult(files=files, provenance=provenance, entries=all_entries)
def _build_provenance(graph, entries) -> dict:
"""Assemble the provenance.json document (0012 §6.2).
The ``artifacts`` map is keyed lexicographically by artifact path (Unicode
code point / byte order for ASCII paths). The per-artifact ``[Entry]`` list
preserves the emitter's emission order (the contributing-decl / structural
layout order each emitter already produced). ``inputsHash`` is computed here
from each entry's projection — a real, reproducible sha256 (§2.1)."""
artifacts = {}
for ent in entries:
artifacts.setdefault(ent.artifact, []).append(ent)
out_artifacts = {}
for path in sorted(artifacts.keys()):
out_entries = []
for ent in artifacts[path]:
entry = {}
if ent.region is not None:
entry["region"] = ent.region
entry["sourceFile"] = ent.source_file
entry["decl"] = ent.decl
sp = ent.span
entry["span"] = {
"file": ent.source_file,
"byteStart": sp.byteStart,
"byteEnd": sp.byteEnd,
"line": sp.line,
"col": sp.col,
}
entry["emitter"] = ent.emitter
entry["inputsHash"] = inputs_hash(ent.inputs_projection)
out_entries.append(entry)
out_artifacts[path] = out_entries
return {
"version": 1,
"source": graph.source_file,
"artifacts": out_artifacts,
}
_SPAN_KEY = "span"
def _json_scalar(v) -> str:
return json.dumps(v, ensure_ascii=False)
def _json_inline(v) -> str:
"""A value rendered on one line with ``", "`` / ``": "`` spacing (used for the
``span`` object): ``{ "file": "x", "byteStart": 27 }`` / ``[1, 2]``."""
if isinstance(v, dict):
if not v:
return "{}"
inner = ", ".join('%s: %s' % (_json_scalar(k), _json_inline(val))
for k, val in v.items())
return "{ %s }" % inner
if isinstance(v, list):
if not v:
return "[]"
return "[%s]" % ", ".join(_json_inline(x) for x in v)
return _json_scalar(v)
def _json_pretty(v, level) -> str:
"""Pretty-print ``v`` at a 2-space indent, but render any ``span`` object
inline. Object keys keep insertion order (the §6.2 field order each entry was
built in); list items keep order (emission order)."""
pad = " " * level
pad_in = " " * (level + 1)
if isinstance(v, dict):
if not v:
return "{}"
parts = []
for k, val in v.items():
if k == _SPAN_KEY:
rendered = _json_inline(val)
else:
rendered = _json_pretty(val, level + 1)
parts.append("%s%s: %s" % (pad_in, _json_scalar(k), rendered))
return "{\n" + ",\n".join(parts) + "\n" + pad + "}"
if isinstance(v, list):
if not v:
return "[]"
parts = [pad_in + _json_pretty(x, level + 1) for x in v]
return "[\n" + ",\n".join(parts) + "\n" + pad + "]"
return _json_scalar(v)
def provenance_json_text(provenance_doc) -> str:
"""Serialize a provenance document (from :func:`_build_provenance`) to the
exact §6.2 fixture bytes: 2-space indent, inline ``span`` objects, trailing
newline. Pure and deterministic — the same document always serializes
identically (the manifest is itself a reproducible artifact, §2.1)."""
return _json_pretty(provenance_doc, 0) + "\n"