//! Orchestration: dispatch the label / changelog / milestone-sync modes.

use anyhow::{Result, anyhow};
use tracing::{debug, info, warn};

use crate::agent::{ask, build_runner};
use crate::config::{Config, Mode};
use crate::consts::OPT_OUT_LABEL;
use crate::github::{fetch_commits_since_tag, fetch_issue_meta, fetch_pr_diff, fetch_pr_meta};
use crate::goals::parse_goals_phases;
use crate::output::{MilestoneSpec, TaggerOutput, noop_json};
use crate::parse::parse_output;
use crate::prompts::{
    RepoContext, build_changelog_prompt, build_label_issue_prompt, build_label_pr_prompt,
    build_milestone_sync_prompt,
};

fn load_context() -> RepoContext {
    // Prefer the pre-distilled snapshot (~650 chars vs 10K for full files).
    // Snapshot is regenerated by .github/workflows/context-snapshot.yml on
    // every push that touches GOALS.md, TIMELINE.md, or events.jsonl.
    // Falls back to full files if snapshot is absent (e.g. first run).
    let (goals_md, timeline_md) =
        match std::fs::read_to_string("vaked-agents/ci/shared/context-snapshot.md") {
            Ok(snap) if !snap.trim().is_empty() => (snap, String::new()),
            _ => (
                std::fs::read_to_string("GOALS.md").unwrap_or_default(),
                std::fs::read_to_string("docs/context/TIMELINE.md").unwrap_or_default(),
            ),
        };
    RepoContext {
        goals_md,
        timeline_md,
        labels_yml: std::fs::read_to_string(".github/labels.yml").unwrap_or_default(),
    }
}

pub(crate) async fn run() -> Result<()> {
    let cfg = Config::from_env()?;

    match cfg.mode.clone() {
        Mode::MilestoneSync => run_milestone_sync(&cfg).await,
        Mode::Changelog => run_changelog(&cfg).await,
        Mode::Label => run_label(&cfg).await,
        Mode::All => {
            // Milestone sync first (idempotent), then label if we have a target.
            run_milestone_sync(&cfg).await?;
            if cfg.pr_number.is_some() || cfg.issue_number.is_some() {
                run_label(&cfg).await?;
            }
            Ok(())
        }
    }
}

async fn run_label(cfg: &Config) -> Result<()> {
    let api_key = cfg.api_key.as_deref()
        .ok_or_else(|| anyhow!("no OPENROUTER_API_KEY — set it to enable labeling"))?;

    let prompt = if let Some(issue) = cfg.issue_number {
        // Context files and issue meta are independent — overlap them.
        let cfg2 = cfg.clone();
        let (ctx_res, meta_res) = tokio::join!(
            tokio::task::spawn_blocking(load_context),
            tokio::task::spawn_blocking(move || fetch_issue_meta(&cfg2, issue)),
        );
        let ctx = ctx_res?;
        let meta = meta_res??;
        if meta.labels.iter().any(|l| l == OPT_OUT_LABEL) {
            info!("'{OPT_OUT_LABEL}' on issue — skipping");
            println!("{}", noop_json());
            return Ok(());
        }
        build_label_issue_prompt(&meta, &ctx)
    } else if let Some(pr) = cfg.pr_number {
        // Context files, PR meta (network), and PR diff (local git) are all
        // independent — fire them all at once.
        let cfg2 = cfg.clone();
        let cfg3 = cfg.clone();
        let (ctx_res, meta_res, diff_res) = tokio::join!(
            tokio::task::spawn_blocking(load_context),
            tokio::task::spawn_blocking(move || fetch_pr_meta(&cfg2, pr)),
            tokio::task::spawn_blocking(move || fetch_pr_diff(&cfg3, pr)),
        );
        let ctx = ctx_res?;
        let meta = meta_res??;
        let diff = diff_res?;
        if meta.labels.iter().any(|l| l == OPT_OUT_LABEL) {
            info!("'{OPT_OUT_LABEL}' on PR — skipping");
            println!("{}", noop_json());
            return Ok(());
        }
        build_label_pr_prompt(&meta, &diff, &ctx)
    } else {
        return Err(anyhow!("label mode requires PR_NUMBER or ISSUE_NUMBER"));
    };

    if cfg.dry_run {
        debug!("dry-run: would send label prompt ({} chars)", prompt.len());
        println!("{}", noop_json());
        return Ok(());
    }

    let runner = build_runner(cfg, api_key)?;
    let raw = ask(&runner, prompt).await?;
    let output = parse_output(&raw);
    println!("{}", serde_json::to_string(&output)?);
    Ok(())
}

async fn run_changelog(cfg: &Config) -> Result<()> {
    let api_key = cfg.api_key.as_deref()
        .ok_or_else(|| anyhow!("no OPENROUTER_API_KEY — set it to enable changelog mode"))?;

    // File reads and git/network fetches are independent — overlap them.
    let (ctx_res, commits) = tokio::join!(
        tokio::task::spawn_blocking(load_context),
        fetch_commits_since_tag(&cfg.repo),
    );
    let ctx = ctx_res?;
    let prompt = build_changelog_prompt(&commits, &ctx);

    if cfg.dry_run {
        debug!("dry-run: would send changelog prompt ({} chars)", prompt.len());
        println!("{}", noop_json());
        return Ok(());
    }

    let runner = build_runner(cfg, api_key)?;
    let raw = ask(&runner, prompt).await?;
    let output = parse_output(&raw);
    println!("{}", serde_json::to_string(&output)?);
    Ok(())
}

async fn run_milestone_sync(cfg: &Config) -> Result<()> {
    // Milestone sync is cheap: try a quick LLM pass to let it read GOALS.md
    // and extract phases with descriptions. Fall back to regex parsing in Rust.
    let ctx = load_context();
    let milestones = if let Some(api_key) = &cfg.api_key {
        if !cfg.dry_run {
            let runner = build_runner(cfg, api_key)?;
            let raw = ask(&runner, build_milestone_sync_prompt(&ctx)).await?;
            let out = parse_output(&raw);
            if !out.milestones_to_upsert.is_empty() {
                out.milestones_to_upsert
            } else {
                extract_milestones_from_file()
            }
        } else {
            extract_milestones_from_file()
        }
    } else {
        extract_milestones_from_file()
    };

    let output = TaggerOutput {
        milestones_to_upsert: milestones,
        ..Default::default()
    };
    println!("{}", serde_json::to_string(&output)?);
    Ok(())
}

fn extract_milestones_from_file() -> Vec<MilestoneSpec> {
    let goals_md = std::fs::read_to_string("GOALS.md").unwrap_or_default();
    if goals_md.is_empty() {
        warn!("GOALS.md not found — returning empty milestone list");
        return Vec::new();
    }
    parse_goals_phases(&goals_md)
}
