/* l1_syscall_guard.c — eBPF syscall guard for Ralph (L1) process.
 *
 * Compile: clang -O2 -target bpf -c l1_syscall_guard.c -o l1_syscall_guard.o
 * Load:    bpftool prog load l1_syscall_guard.o /sys/fs/bpf/l1_syscall_guard
 * Attach:  bpftool cgroup attach /sys/fs/cgroup/<l1-cgroup> cgroup/syscall pinned
 *         /sys/fs/bpf/l1_syscall_guard
 *
 * This program attaches to a cgroup that contains only the ralphd (L1) process.
 * It enforces the allowed syscall profile and denies dangerous syscalls.
 * Generated by meta-ralphd (L2) — see meta-ralphd/ebpf.py
 */

#include <linux/bpf.h>
#include <linux/filter.h>
#include <linux/seccomp.h>
#include <linux/audit.h>
#include <linux/sched.h>

#define ALLOW  SECCOMP_RET_ALLOW
#define DENY   SECCOMP_RET_KILL_THREAD

/* Allowed syscalls (x86_64) — Ralph's capability profile:
 *   file reads, network I/O, process lifecycle, stdlib alloc
 */
static const long ALLOWED[] = {
    0,   // read
    1,   // write
    2,   // open
    3,   // close
    4,   // stat
    5,   // fstat
    8,   // lseek
    9,   // mmap
    10,  // mprotect
    11,  // munmap
    12,  // brk
    17,  // pread64
    18,  // pwrite64
    21,  // access
    35,  // nanosleep
    39,  // getpid
    40,  // sendfile
    41,  // socket
    42,  // connect
    44,  // sendto
    45,  // recvfrom
    46,  // sendmsg
    47,  // recvmsg
    56,  // clone
    59,  // execve
    60,  // exit
    61,  // wait4
    72,  // fcntl
    78,  // getdents
    79,  // getcwd
    89,  // readlink
    92,  // writev
    96,  // gettid
    102, // getuid
    110, // getppid
    137, // statfs
    138, // fstatfs
    217, // getdents64
    231, // exit_group
    257, // openat
    262, // newfstatat
    318, // getrandom
    332, // statx
};

/* Denied syscalls — explicit block list */
static const long DENIED[] = {
    101,  // ptrace
    169,  // reboot
    175,  // init_module
    176,  // delete_module
    167,  // swapon
    168,  // swapoff
};

/* Gossip packet signature verification guard.
 * Called from cgroup/syscall context when write() targets a gossip socket.
 * Verifies the outgoing packet's Ed25519 signature before allowing send.
 *
 * For the Python reference, this check is done in userspace.
 * For the Zig production daemon, this BPF program runs in-kernel.
 */
SEC("cgroup/syscall")
int gossip_sig_guard(struct bpf_syscall_ctx *ctx) {
    long nr = ctx->syscall_nr;

    /* Fast-path: allow all permitted syscalls immediately */
    int i;
    #pragma unroll
    for (i = 0; i < sizeof(ALLOWED) / sizeof(ALLOWED[0]); i++) {
        if (nr == ALLOWED[i])
            return ALLOW;
    }

    /* Deny-list: block dangerous syscalls unconditionally */
    #pragma unroll
    for (i = 0; i < sizeof(DENIED) / sizeof(DENIED[0]); i++) {
        if (nr == DENIED[i])
            return DENY;
    }

    /* Default: deny unknown syscalls — fail-closed */
    return DENY;
}

char _license[] SEC("license") = "GPL";
