//! vaked-lower — the 0012 lowering pass: validated graph -> artifacts.
//!
//! Faithful port of `vakedc/lower.py`. Turns a *validated* typed semantic graph
//! (the output of `vakedc.check`) into the inspectable artifacts Vaked owns plus
//! the Nix spine that wires them, together with a decl-level provenance manifest.
//!
//! Purity / determinism (0012 §2): every emitter is a pure function of
//! `(graph, nodes)`. No IO, no clock, no randomness. All ordering is by a stable
//! graph-derived key (declaration source order via `edgesFrom`, the fixed
//! structural flake layout, lexicographic order for the provenance `artifacts`
//! map). The only IO is the CLI write layer (`cli/main.zig`), which writes the
//! `files` this module returns.
//!
//! SQLite is out of scope (no `catalog.sqlite` emitter — it is a deferred no-op,
//! exactly as in Python's fixture set).

const std = @import("std");
const core = @import("vaked-core");
const parse = @import("vaked-parse");
const Value = core.Value;
const Graph = core.Graph;
const GraphNode = core.GraphNode;
const Span = core.Span;
const json_canon = core.json_canon;
const ast = parse.ast;

const Alloc = std.mem.Allocator;
const Buf = std.ArrayList(u8);

// --------------------------------------------------------------------------- //
// Disclosed placeholders (values the BUILD, not lowering, would resolve).
// --------------------------------------------------------------------------- //

/// nixpkgs is emitted PINNED (0012 §4.1). The 40-hex value is a disclosed
/// placeholder standing in for the toolchain's pinned baseline rev.
const NIXPKGS_BASELINE_REV = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";

// --------------------------------------------------------------------------- //
// Generated-header sentinel (0012 §6.1). No timestamp.
// --------------------------------------------------------------------------- //

/// The source-file name as it appears in the §6.1 generated header: the
/// *basename* (`operator-field.vaked`), never the full path.
fn headerFile(alloc: Alloc, source_file: []const u8) ![]const u8 {
    // posixpath.basename(source_file.replace("\\", "/"))
    const norm = try alloc.dupe(u8, source_file);
    for (norm) |*c| {
        if (c.* == '\\') c.* = '/';
    }
    if (std.mem.lastIndexOfScalar(u8, norm, '/')) |i| return norm[i + 1 ..];
    return norm;
}

fn header(alloc: Alloc, source_file: []const u8, decl: []const u8) ![]const u8 {
    const f = try headerFile(alloc, source_file);
    return std.fmt.allocPrint(alloc, "generated by Vaked from {s}:{s} \u{2014} do not edit", .{ f, decl });
}

// --------------------------------------------------------------------------- //
// Value accessors — mirror lower.py's _ref / _lit / _str_list / _app_call /
// _record_entries, reading the JSON-shaped prop `Value`.
// --------------------------------------------------------------------------- //

/// The value of object field `key`, or null.
fn field(v: ?Value, key: []const u8) ?Value {
    const obj = v orelse return null;
    switch (obj) {
        .object => |fields| {
            for (fields) |f| {
                if (std.mem.eql(u8, f.key, key)) return f.value;
            }
            return null;
        },
        else => return null,
    }
}

fn hasField(v: Value, key: []const u8) bool {
    return field(v, key) != null;
}

fn nodeProp(node: *const GraphNode, key: []const u8) ?Value {
    return field(node.props, key);
}

/// `_ref`: the dotted ref string of a `{"ref": "..."}` prop (no `args`, no
/// `record`), else null.
fn refOf(prop: ?Value) ?[]const u8 {
    const p = prop orelse return null;
    switch (p) {
        .object => {
            if (hasField(p, "ref") and !hasField(p, "args") and !hasField(p, "record")) {
                if (field(p, "ref")) |rv| switch (rv) {
                    .string => |s| return s,
                    else => {},
                };
            }
            return null;
        },
        else => return null,
    }
}

/// `_lit`: the literal value of a `{"lit": ..., "value": ...}` prop, else null.
/// Returns the `value` Value (a string in the corpus).
fn litOf(prop: ?Value) ?Value {
    const p = prop orelse return null;
    switch (p) {
        .object => {
            if (hasField(p, "lit")) return field(p, "value");
            return null;
        },
        else => return null,
    }
}

/// `_lit` as a string (the corpus always stores lit values as strings).
fn litStr(prop: ?Value) ?[]const u8 {
    const v = litOf(prop) orelse return null;
    switch (v) {
        .string => |s| return s,
        else => return null,
    }
}

/// `_str_list`: the string-literal values of a list prop.
fn strList(alloc: Alloc, prop: ?Value) ![]const []const u8 {
    var out: std.ArrayList([]const u8) = .empty;
    const p = prop orelse return out.toOwnedSlice(alloc);
    switch (p) {
        .array => |items| {
            for (items) |x| {
                if (litStr(x)) |s| try out.append(alloc, s);
            }
        },
        else => {},
    }
    return out.toOwnedSlice(alloc);
}

const AppCall = struct { ref: []const u8, args: []const ?[]const u8 };

/// `_app_call`: if `prop` is an application `f(args...)`, return (ref, [arg-lits]).
fn appCall(alloc: Alloc, prop: ?Value) !?AppCall {
    const p = prop orelse return null;
    switch (p) {
        .object => {
            if (hasField(p, "ref") and hasField(p, "args")) {
                const ref_v = field(p, "ref").?;
                const ref_s = switch (ref_v) {
                    .string => |s| s,
                    else => return null,
                };
                var args: std.ArrayList(?[]const u8) = .empty;
                const args_v = field(p, "args").?;
                switch (args_v) {
                    .array => |items| {
                        for (items) |a| try args.append(alloc, litStr(a));
                    },
                    else => {},
                }
                return AppCall{ .ref = ref_s, .args = try args.toOwnedSlice(alloc) };
            }
            return null;
        },
        else => return null,
    }
}

const RecordEntry = struct { name: []const u8, value: ?Value };

/// `_record_entries`: the `[{"assign","op","value"}]` entries of a
/// record/record-app prop, as `name -> value-literal` pairs (preserving order).
/// The returned `value` is the *literal value* (mirroring `_lit(e.value)`).
fn recordEntries(alloc: Alloc, prop: ?Value) ![]const RecordEntry {
    var out: std.ArrayList(RecordEntry) = .empty;
    const p = prop orelse return out.toOwnedSlice(alloc);
    const rec = field(p, "record") orelse return out.toOwnedSlice(alloc);
    switch (rec) {
        .array => |items| {
            for (items) |e| {
                if (field(e, "assign")) |assign_v| {
                    const name = switch (assign_v) {
                        .string => |s| s,
                        else => continue,
                    };
                    try out.append(alloc, .{ .name = name, .value = litOf(field(e, "value")) });
                }
            }
        },
        else => {},
    }
    return out.toOwnedSlice(alloc);
}

// --------------------------------------------------------------------------- //
// Canonical projection JSON + inputsHash (0012 §6.2).
// --------------------------------------------------------------------------- //

/// The canonical projection JSON a node/engine projection is hashed over: sorted
/// keys, compact separators, ensure_ascii=False, no trailing newline. Reuses the
/// core compact writer (sorts object keys recursively).
fn canonicalProjectionJson(alloc: Alloc, projection: Value) ![]u8 {
    var buf: Buf = .empty;
    try json_canon.writeValueCompact(&buf, alloc, projection);
    return buf.toOwnedSlice(alloc);
}

fn inputsHash(alloc: Alloc, projection: Value) ![]const u8 {
    const canonical = try canonicalProjectionJson(alloc, projection);
    var digest: [32]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(canonical, &digest, .{});
    const hex = std.fmt.bytesToHex(digest, .lower);
    return std.fmt.allocPrint(alloc, "sha256-{s}", .{hex});
}

/// A node's projection: kind + name + (canonicalized) props. The compact writer
/// sorts keys at emit time, so we hand props through verbatim.
fn nodeProjection(alloc: Alloc, node: *const GraphNode) !Value {
    const fields = try alloc.dupe(Value.Field, &.{
        .{ .key = "kind", .value = .{ .string = node.kind } },
        .{ .key = "name", .value = .{ .string = node.name } },
        .{ .key = "props", .value = node.props },
    });
    return .{ .object = fields };
}

/// The resolved-engine projection for a fiber's `packages.<engine>` region.
fn engineProjection(alloc: Alloc, engine_name: []const u8) !Value {
    const pkg = try std.fmt.allocPrint(alloc, "packages.{s}", .{engine_name});
    const fields = try alloc.dupe(Value.Field, &.{
        .{ .key = "engine", .value = .{ .string = engine_name } },
        .{ .key = "package", .value = .{ .string = pkg } },
    });
    return .{ .object = fields };
}

// --------------------------------------------------------------------------- //
// Provenance entry + manifest.
// --------------------------------------------------------------------------- //

const ProvEntry = struct {
    artifact: []const u8,
    region: ?[]const u8,
    source_file: []const u8,
    decl: []const u8,
    span: Span,
    emitter: []const u8,
    inputs_projection: Value,
};

const Files = std.StringArrayHashMapUnmanaged([]const u8);

pub const LowerResult = struct {
    files: Files,
    provenance: Value,
};

// --------------------------------------------------------------------------- //
// Graph projection utilities.
// --------------------------------------------------------------------------- //

/// `_children_of`: direct `contains` children of a node, in source order. Uses
/// `edgesFrom` (O(1) memoized adjacency lookup) — output order is byte-identical
/// to the old full scan.
fn childrenOf(alloc: Alloc, graph: *Graph, parent_id: []const u8) ![]*GraphNode {
    var out: std.ArrayList(*GraphNode) = .empty;
    const edges = try graph.edgesFrom(parent_id);
    for (edges) |e| {
        if (std.mem.eql(u8, e.label, "contains")) {
            if (graph.getNode(e.to)) |child| try out.append(alloc, child);
        }
    }
    return out.toOwnedSlice(alloc);
}

fn byKind(alloc: Alloc, nodes: []*GraphNode, kind: []const u8) ![]*GraphNode {
    var out: std.ArrayList(*GraphNode) = .empty;
    for (nodes) |n| {
        if (std.mem.eql(u8, n.kind, kind)) try out.append(alloc, n);
    }
    return out.toOwnedSlice(alloc);
}

const RuntimeView = struct {
    runtime: *GraphNode,
    indexes: []*GraphNode,
    streams: []*GraphNode,
    fibers: []*GraphNode,
    surfaces: []*GraphNode,
    parallels: []*GraphNode,
};

fn runtimeView(alloc: Alloc, graph: *Graph) !?RuntimeView {
    // runtimes = [n for n in graph.nodes_sorted() if n.kind == "runtime"]; take [0].
    const sorted = try graph.nodesSorted();
    var runtime_id: ?[]const u8 = null;
    for (sorted) |n| {
        if (std.mem.eql(u8, n.kind, "runtime")) {
            runtime_id = n.id;
            break;
        }
    }
    const rid = runtime_id orelse return null;
    const runtime = graph.getNode(rid).?;
    const children = try childrenOf(alloc, graph, runtime.id);
    return RuntimeView{
        .runtime = runtime,
        .indexes = try byKind(alloc, children, "index"),
        .streams = try byKind(alloc, children, "stream"),
        .fibers = try byKind(alloc, children, "fiber"),
        .surfaces = try byKind(alloc, children, "surface"),
        .parallels = try byKind(alloc, children, "parallel"),
    };
}

/// `_index_emit_targets`: the dotted `emit` target refs of an index node.
fn indexEmitTargets(alloc: Alloc, index_node: *const GraphNode) ![]const []const u8 {
    var out: std.ArrayList([]const u8) = .empty;
    const emit = nodeProp(index_node, "emit") orelse return out.toOwnedSlice(alloc);
    switch (emit) {
        .array => |items| {
            for (items) |x| {
                if (refOf(x)) |r| try out.append(alloc, r);
            }
        },
        else => {},
    }
    return out.toOwnedSlice(alloc);
}

fn hasTarget(targets: []const []const u8, t: []const u8) bool {
    for (targets) |x| {
        if (std.mem.eql(u8, x, t)) return true;
    }
    return false;
}

/// `_index_is_pinned`: True when the index declares `trust = pinned { … }`.
fn indexIsPinned(index_node: *const GraphNode) bool {
    const trust = nodeProp(index_node, "trust") orelse return false;
    switch (trust) {
        .object => {
            if (field(trust, "ref")) |rv| switch (rv) {
                .string => |s| return std.mem.eql(u8, s, "pinned"),
                else => {},
            };
            return false;
        },
        else => return false,
    }
}

fn fiberEngineName(fiber_node: *const GraphNode) ?[]const u8 {
    return refOf(nodeProp(fiber_node, "engine"));
}

// --------------------------------------------------------------------------- //
// Emitter: nix.spine (ALWAYS) — flake.nix + the deferred surface stub.
// --------------------------------------------------------------------------- //

/// `_nix_source_slug`: the repo's last path segment, with `.`/`_` → `-`.
fn nixSourceSlug(alloc: Alloc, dotted: []const u8) ![]const u8 {
    const repo = if (std.mem.lastIndexOfScalar(u8, dotted, '/')) |i| dotted[i + 1 ..] else dotted;
    const slug = try alloc.dupe(u8, repo);
    for (slug) |*c| {
        if (c.* == '.' or c.* == '_') c.* = '-';
    }
    return slug;
}

/// Render `source` prop into a flat list of source app-calls (handles both the
/// single-app and list-of-apps shapes).
fn sourceApps(alloc: Alloc, src: ?Value) ![]const Value {
    var out: std.ArrayList(Value) = .empty;
    const s = src orelse return out.toOwnedSlice(alloc);
    switch (s) {
        .array => |items| {
            for (items) |x| try out.append(alloc, x);
        },
        else => try out.append(alloc, s),
    }
    return out.toOwnedSlice(alloc);
}

const EmitOut = struct { files: Files, entries: []const ProvEntry };

fn emitNixSpine(alloc: Alloc, graph: *Graph, rv: RuntimeView) !EmitOut {
    const runtime = rv.runtime;
    const sf = graph.source_file;
    const rt_name = runtime.name;

    const systems = try strList(alloc, nodeProp(runtime, "systems"));

    var lines: std.ArrayList([]const u8) = .empty;
    const A = struct {
        fn add(l: *std.ArrayList([]const u8), a: Alloc, s: []const u8) !void {
            try l.append(a, s);
        }
        fn addf(l: *std.ArrayList([]const u8), a: Alloc, comptime fmt: []const u8, args: anytype) !void {
            try l.append(a, try std.fmt.allocPrint(a, fmt, args));
        }
    };

    try A.addf(&lines, alloc, "# {s}", .{try header(alloc, sf, try std.fmt.allocPrint(alloc, "runtime {s}", .{rt_name}))});
    try A.add(&lines, alloc, "#");
    try A.add(&lines, alloc, "# Expected-output fixture (no compiler exists yet) \u{2014} see ./README.md and");
    try A.add(&lines, alloc, "# docs/language/0012-lowering.md \u{a7}4 (the Nix spine). Edits belong in the source");
    try A.add(&lines, alloc, "# .vaked file, not here.");
    try A.add(&lines, alloc, "{");
    try A.addf(&lines, alloc, "  description = \"{s} \u{2014} generated by Vaked\";", .{rt_name});
    try A.add(&lines, alloc, "");
    try A.add(&lines, alloc, "  inputs = {");
    try A.add(&lines, alloc, "    # nixpkgs is emitted pinned to the toolchain's baseline rev (0012 \u{a7}4.1): an");
    try A.add(&lines, alloc, "    # explicit rev, never a moving channel ref. The 40-hex value below is a");
    try A.add(&lines, alloc, "    # disclosed placeholder (all-`b` = \"baseline\"; see ./README.md); the");
    try A.add(&lines, alloc, "    # committed flake.lock (produced at first build) records the real resolution.");
    try A.addf(&lines, alloc, "    nixpkgs.url = \"github:NixOS/nixpkgs/{s}\";", .{NIXPKGS_BASELINE_REV});

    for (rv.indexes) |idx| {
        const src = nodeProp(idx, "source");
        if (indexIsPinned(idx)) {
            const call = try appCall(alloc, src);
            var owner: []const u8 = "";
            if (call) |c| {
                if (c.args.len > 0) owner = c.args[0] orelse "";
            }
            try A.add(&lines, alloc, "");
            try A.addf(&lines, alloc, "    # index {s} \u{2014} trust = pinned {{ commit, sha256 }} (0012 \u{a7}4.2):", .{idx.name});
            try A.add(&lines, alloc, "    # commit pins the rev; sha256 is recorded as the lock entry's narHash so the");
            try A.add(&lines, alloc, "    # build verifies the fetch. raw.github(...) => flake = false.");
            try A.addf(&lines, alloc, "    {s}-src = {{", .{idx.name});
            try A.addf(&lines, alloc, "      url = \"github:{s}/<commit>\"; # trust.pinned.commit", .{owner});
            try A.add(&lines, alloc, "      flake = false;");
            try A.add(&lines, alloc, "    };");
        } else {
            const sources = try sourceApps(alloc, src);
            try A.add(&lines, alloc, "");
            try A.addf(&lines, alloc, "    # index {s} \u{2014} sources (unpinned; flake.lock records the resolved rev).", .{idx.name});
            try A.add(&lines, alloc, "    # 0012 \u{a7}4.2: each index source becomes a flake input.");
            for (sources) |s| {
                const call = try appCall(alloc, s);
                if (call == null) continue;
                const owner_repo = if (call.?.args.len > 0) (call.?.args[0] orelse "") else "";
                const slug = try nixSourceSlug(alloc, owner_repo);
                try A.addf(&lines, alloc, "    {s}-src-{s} = {{ url = \"github:{s}\"; flake = false; }};", .{ idx.name, slug, owner_repo });
            }
        }
    }
    try A.add(&lines, alloc, "  };");
    try A.add(&lines, alloc, "");
    try A.add(&lines, alloc, "  outputs = { self, nixpkgs, ... }@inputs:");
    try A.add(&lines, alloc, "    let");
    {
        // "      # runtime <rt> — systems = [\"a\", \"b\"]"
        var sysq: Buf = .empty;
        for (systems, 0..) |s, i| {
            if (i != 0) try sysq.appendSlice(alloc, ", ");
            try sysq.appendSlice(alloc, try std.fmt.allocPrint(alloc, "\"{s}\"", .{s}));
        }
        try A.addf(&lines, alloc, "      # runtime {s} \u{2014} systems = [{s}]", .{ rt_name, sysq.items });
    }
    {
        // "      systems = [ \"a\" \"b\" ];"  (space-joined, no commas)
        var sysn: Buf = .empty;
        for (systems, 0..) |s, i| {
            if (i != 0) try sysn.appendSlice(alloc, " ");
            try sysn.appendSlice(alloc, try std.fmt.allocPrint(alloc, "\"{s}\"", .{s}));
        }
        try A.addf(&lines, alloc, "      systems = [ {s} ];", .{sysn.items});
    }
    try A.add(&lines, alloc, "      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f system);");
    try A.add(&lines, alloc, "    in");
    try A.add(&lines, alloc, "    {");
    try A.add(&lines, alloc, "      # nixosModules.<runtime> \u{2014} wires the OTP/Zig daemons and references the");
    try A.add(&lines, alloc, "      # gen/ artifacts as installed files (0012 \u{a7}4.3).");
    try A.addf(&lines, alloc, "      nixosModules.{s} = import ./nixos/{s}.nix {{", .{ rt_name, rt_name });
    try A.add(&lines, alloc, "        # NixOS module fixture is described in 0012 \u{a7}4.3; not emitted as a");
    try A.add(&lines, alloc, "        # separate file in this fixture set (interface only).");
    try A.add(&lines, alloc, "        inherit self;");
    try A.add(&lines, alloc, "      };");
    try A.add(&lines, alloc, "");
    try A.add(&lines, alloc, "      packages = forAllSystems (system:");
    try A.add(&lines, alloc, "        let pkgs = nixpkgs.legacyPackages.${system};");
    try A.add(&lines, alloc, "        in {");

    // packages: engines (from fibers, source order), then crabcc index derivations.
    var seen_engines: std.StringArrayHashMapUnmanaged(void) = .empty;
    for (rv.fibers) |fib| {
        const eng = fiberEngineName(fib) orelse continue;
        if (seen_engines.contains(eng)) continue;
        try seen_engines.put(alloc, eng, {});
        try A.addf(&lines, alloc, "          # engine {s} (fiber {s}: engine = {s}) \u{2014} built Zig pkg.", .{ eng, fib.name, eng });
        try A.addf(&lines, alloc, "          {s} = pkgs.callPackage ./pkgs/{s}.nix {{ }};", .{ eng, eng });
        try A.add(&lines, alloc, "");
    }
    const any_engine = seen_engines.count() > 0;

    for (rv.indexes) |idx| {
        const targets = try indexEmitTargets(alloc, idx);
        if (!hasTarget(targets, "nix.derivation")) continue;
        const normalize = refOf(nodeProp(idx, "normalize"));
        // cat_targets = [t for t in targets if t.startswith("catalog.")]
        var cat_targets: std.ArrayList([]const u8) = .empty;
        for (targets) |t| {
            if (std.mem.startsWith(u8, t, "catalog.")) try cat_targets.append(alloc, t);
        }
        // emit_flags = " ".join("--emit " + t.split(".",1)[1] ...)
        var emit_flags: Buf = .empty;
        for (cat_targets.items, 0..) |t, i| {
            if (i != 0) try emit_flags.appendSlice(alloc, " ");
            const after = afterDot(t);
            try emit_flags.appendSlice(alloc, try std.fmt.allocPrint(alloc, "--emit {s}", .{after}));
        }
        try A.addf(&lines, alloc, "          # index {s}, emit \u{220b} nix.derivation (0012 \u{a7}5.3a) \u{2014} CrabCC index", .{idx.name});
        try A.add(&lines, alloc, "          # derivation; runs crabcc at build time over the pinned sources with");
        try A.addf(&lines, alloc, "          # normalize = {s}.", .{normalize orelse ""});
        try A.addf(&lines, alloc, "          {s}-crabcc-index = pkgs.stdenv.mkDerivation {{", .{idx.name});
        try A.addf(&lines, alloc, "            pname = \"{s}-crabcc-index\";", .{idx.name});
        try A.add(&lines, alloc, "            version = \"0\";");
        try A.add(&lines, alloc, "            srcs = [");
        const sources = try sourceApps(alloc, nodeProp(idx, "source"));
        for (sources) |s| {
            const call = try appCall(alloc, s);
            if (call == null) continue;
            const owner_repo = if (call.?.args.len > 0) (call.?.args[0] orelse "") else "";
            const slug = try nixSourceSlug(alloc, owner_repo);
            try A.addf(&lines, alloc, "              inputs.{s}-src-{s}", .{ idx.name, slug });
        }
        try A.add(&lines, alloc, "            ];");
        try A.add(&lines, alloc, "            nativeBuildInputs = [ pkgs.crabcc ];");
        try A.add(&lines, alloc, "            buildPhase = ''");
        // norm_arg = normalize.split(".",1)[1] if normalize has "." else normalize
        const norm_arg: []const u8 = blk: {
            if (normalize) |n| {
                if (std.mem.indexOfScalar(u8, n, '.') != null) break :blk afterDot(n);
                break :blk n;
            }
            break :blk "";
        };
        // "# normalize = <full> ; emit = <cat_targets joined ', '>"
        var cat_join: Buf = .empty;
        for (cat_targets.items, 0..) |t, i| {
            if (i != 0) try cat_join.appendSlice(alloc, ", ");
            try cat_join.appendSlice(alloc, t);
        }
        try A.addf(&lines, alloc, "              # normalize = {s} ; emit = {s}", .{ normalize orelse "", cat_join.items });
        try A.addf(&lines, alloc, "              crabcc index build --normalize {s} \\", .{norm_arg});
        try A.addf(&lines, alloc, "                {s} \\", .{emit_flags.items});
        try A.add(&lines, alloc, "                --out $out");
        try A.add(&lines, alloc, "            '';");
        try A.add(&lines, alloc, "          };");
    }
    try A.add(&lines, alloc, "        });");
    try A.add(&lines, alloc, "");
    try A.add(&lines, alloc, "      apps = forAllSystems (system:");
    try A.add(&lines, alloc, "        let pkgs = nixpkgs.legacyPackages.${system};");
    try A.add(&lines, alloc, "        in {");
    for (rv.surfaces) |surf| {
        const mode = refOf(nodeProp(surf, "mode"));
        try A.addf(&lines, alloc, "          # surface {s} (mode = {s}) \u{2014} launcher app.", .{ surf.name, mode orelse "" });
        try A.add(&lines, alloc, "          # 0012 \u{a7}7: surface launcher body is DEFERRED (no-op today). The slot");
        try A.add(&lines, alloc, "          # exists so the registry test stays honest, but the mapping (raylib");
        try A.add(&lines, alloc, "          # host integration) is not yet specified. The deferred body is derived");
        try A.add(&lines, alloc, "          # from NOTHING but the surface decl name: a stub that exits non-zero");
        try A.add(&lines, alloc, "          # with the standard deferral message \u{2014} no real launcher is wired, and");
        try A.add(&lines, alloc, "          # it does not route through any engine/fiber package.");
        try A.addf(&lines, alloc, "          {s} = {{", .{surf.name});
        try A.add(&lines, alloc, "            type = \"app\";");
        try A.addf(&lines, alloc, "            program = \"${{pkgs.writeShellScript \"{s}-launcher-deferred\" ''", .{surf.name});
        try A.add(&lines, alloc, "              echo \"vaked: surface launcher lowering deferred (0012 \u{a7}7)\" >&2");
        try A.add(&lines, alloc, "              exit 1");
        try A.add(&lines, alloc, "            ''}\";");
        try A.add(&lines, alloc, "          };");
    }
    try A.add(&lines, alloc, "        });");
    try A.add(&lines, alloc, "");
    try A.add(&lines, alloc, "      devShells = forAllSystems (system:");
    try A.add(&lines, alloc, "        let pkgs = nixpkgs.legacyPackages.${system};");
    try A.add(&lines, alloc, "        in {");
    try A.add(&lines, alloc, "          default = pkgs.mkShell {");
    // toolchains: zig if any engine, crabcc if any nix.derivation index.
    var tool_comment: std.ArrayList([]const u8) = .empty;
    var tool_pkgs: std.ArrayList([]const u8) = .empty;
    if (any_engine) {
        try tool_comment.append(alloc, "zig (engines)");
        try tool_pkgs.append(alloc, "pkgs.zig");
    }
    var any_deriv = false;
    for (rv.indexes) |i| {
        if (hasTarget(try indexEmitTargets(alloc, i), "nix.derivation")) {
            any_deriv = true;
            break;
        }
    }
    if (any_deriv) {
        try tool_comment.append(alloc, "crabcc (index)");
        try tool_pkgs.append(alloc, "pkgs.crabcc");
    }
    {
        var tc: Buf = .empty;
        for (tool_comment.items, 0..) |t, i| {
            if (i != 0) try tc.appendSlice(alloc, ", ");
            try tc.appendSlice(alloc, t);
        }
        try A.addf(&lines, alloc, "            # toolchains the runtime needs: {s}.", .{tc.items});
    }
    {
        var tp: Buf = .empty;
        for (tool_pkgs.items, 0..) |t, i| {
            if (i != 0) try tp.appendSlice(alloc, " ");
            try tp.appendSlice(alloc, t);
        }
        try A.addf(&lines, alloc, "            packages = [ {s} ];", .{tp.items});
    }
    try A.add(&lines, alloc, "          };");
    try A.add(&lines, alloc, "        });");
    try A.add(&lines, alloc, "    };");
    try A.add(&lines, alloc, "}");

    const text = try joinLines(alloc, lines.items);
    var files: Files = .empty;
    try files.put(alloc, "flake.nix", text);

    // --- provenance entries: structural flake-output layout order (0012 §6.2) #
    var entries: std.ArrayList(ProvEntry) = .empty;
    try entries.append(alloc, .{
        .artifact = "flake.nix",
        .region = try std.fmt.allocPrint(alloc, "nixosModules.{s}", .{rt_name}),
        .source_file = sf,
        .decl = try std.fmt.allocPrint(alloc, "runtime {s}", .{rt_name}),
        .span = runtime.provenance.?.span,
        .emitter = "nix.spine",
        .inputs_projection = try nodeProjection(alloc, runtime),
    });
    for (rv.indexes) |idx| {
        if (!indexIsPinned(idx)) continue;
        try entries.append(alloc, .{
            .artifact = "flake.nix",
            .region = try std.fmt.allocPrint(alloc, "inputs.{s}-src", .{idx.name}),
            .source_file = sf,
            .decl = try std.fmt.allocPrint(alloc, "index {s}", .{idx.name}),
            .span = idx.provenance.?.span,
            .emitter = "nix.spine",
            .inputs_projection = try nodeProjection(alloc, idx),
        });
    }
    for (rv.indexes) |idx| {
        if (!hasTarget(try indexEmitTargets(alloc, idx), "nix.derivation")) continue;
        try entries.append(alloc, .{
            .artifact = "flake.nix",
            .region = try std.fmt.allocPrint(alloc, "packages.{s}-crabcc-index", .{idx.name}),
            .source_file = sf,
            .decl = try std.fmt.allocPrint(alloc, "index {s}", .{idx.name}),
            .span = idx.provenance.?.span,
            .emitter = "crabcc.index",
            .inputs_projection = try nodeProjection(alloc, idx),
        });
    }
    var seen2: std.StringArrayHashMapUnmanaged(void) = .empty;
    for (rv.fibers) |fib| {
        const eng = fiberEngineName(fib) orelse continue;
        if (seen2.contains(eng)) continue;
        try seen2.put(alloc, eng, {});
        try entries.append(alloc, .{
            .artifact = "flake.nix",
            .region = try std.fmt.allocPrint(alloc, "packages.{s}", .{eng}),
            .source_file = sf,
            .decl = try std.fmt.allocPrint(alloc, "fiber {s}", .{fib.name}),
            .span = fib.provenance.?.span,
            .emitter = "nix.spine",
            .inputs_projection = try engineProjection(alloc, eng),
        });
    }
    for (rv.surfaces) |surf| {
        try entries.append(alloc, .{
            .artifact = "flake.nix",
            .region = try std.fmt.allocPrint(alloc, "apps.{s}", .{surf.name}),
            .source_file = sf,
            .decl = try std.fmt.allocPrint(alloc, "surface {s}", .{surf.name}),
            .span = surf.provenance.?.span,
            .emitter = "nix.spine",
            .inputs_projection = try nodeProjection(alloc, surf),
        });
    }
    return .{ .files = files, .entries = try entries.toOwnedSlice(alloc) };
}

/// `s.split(".", 1)[1]` — everything after the first dot (or `s` if no dot).
fn afterDot(s: []const u8) []const u8 {
    if (std.mem.indexOfScalar(u8, s, '.')) |i| return s[i + 1 ..];
    return s;
}

/// "\n".join(lines) + "\n"
fn joinLines(alloc: Alloc, lines: []const []const u8) ![]u8 {
    var buf: Buf = .empty;
    for (lines) |l| {
        try buf.appendSlice(alloc, l);
        try buf.append(alloc, '\n');
    }
    return buf.toOwnedSlice(alloc);
}

// --------------------------------------------------------------------------- //
// Emitter: docs.runtime (ALWAYS) — gen/RUNTIME.md.
// --------------------------------------------------------------------------- //

/// "`s`"
fn mdCode(alloc: Alloc, s: []const u8) ![]const u8 {
    return std.fmt.allocPrint(alloc, "`{s}`", .{s});
}

/// Render an index's source(s) for the Indexes table: comma-joined code spans of
/// `ref("arg", ...)`.
fn indexSourceRender(alloc: Alloc, idx: *const GraphNode) ![]const u8 {
    const sources = try sourceApps(alloc, nodeProp(idx, "source"));
    var parts: std.ArrayList([]const u8) = .empty;
    for (sources) |s| {
        const call = try appCall(alloc, s);
        if (call) |c| {
            var argbuf: Buf = .empty;
            for (c.args, 0..) |a, i| {
                if (i != 0) try argbuf.appendSlice(alloc, ", ");
                try argbuf.appendSlice(alloc, try std.fmt.allocPrint(alloc, "\"{s}\"", .{a orelse ""}));
            }
            const rendered = try std.fmt.allocPrint(alloc, "{s}({s})", .{ c.ref, argbuf.items });
            try parts.append(alloc, try mdCode(alloc, rendered));
        }
    }
    return joinComma(alloc, parts.items);
}

fn joinComma(alloc: Alloc, parts: []const []const u8) ![]const u8 {
    var buf: Buf = .empty;
    for (parts, 0..) |p, i| {
        if (i != 0) try buf.appendSlice(alloc, ", ");
        try buf.appendSlice(alloc, p);
    }
    return buf.toOwnedSlice(alloc);
}

fn emitDocsRuntime(alloc: Alloc, graph: *Graph, rv: RuntimeView) !EmitOut {
    const runtime = rv.runtime;
    const sf = graph.source_file;
    const rt_name = runtime.name;
    const systems = try strList(alloc, nodeProp(runtime, "systems"));

    var lines: std.ArrayList([]const u8) = .empty;
    const A = struct {
        fn add(l: *std.ArrayList([]const u8), a: Alloc, s: []const u8) !void {
            try l.append(a, s);
        }
        fn addf(l: *std.ArrayList([]const u8), a: Alloc, comptime fmt: []const u8, args: anytype) !void {
            try l.append(a, try std.fmt.allocPrint(a, fmt, args));
        }
    };

    try A.addf(&lines, alloc, "<!-- {s} -->", .{try header(alloc, sf, try std.fmt.allocPrint(alloc, "runtime {s}", .{rt_name}))});
    try A.add(&lines, alloc, "");
    try A.addf(&lines, alloc, "# Runtime: {s}", .{rt_name});
    try A.add(&lines, alloc, "");
    try A.addf(&lines, alloc, "Generated from `{s}`. This document is a rendering of the", .{try headerFile(alloc, sf)});
    try A.addf(&lines, alloc, "`runtime {s}` declaration \u{2014} see", .{rt_name});
    try A.add(&lines, alloc, "[`docs/language/0012-lowering.md`](../../../../docs/language/0012-lowering.md)");
    try A.add(&lines, alloc, "\u{a7}5.1. Do not edit; regenerate from source.");
    try A.add(&lines, alloc, "");
    {
        var sysparts: std.ArrayList([]const u8) = .empty;
        for (systems) |s| try sysparts.append(alloc, try mdCode(alloc, s));
        try A.addf(&lines, alloc, "- **Systems:** {s}", .{try joinComma(alloc, sysparts.items)});
    }
    try A.add(&lines, alloc, "");

    // 2. Indexes
    try A.add(&lines, alloc, "## Indexes");
    try A.add(&lines, alloc, "");
    try A.add(&lines, alloc, "| Index | Source(s) | Normalize / Chunk | Trust | Emit |");
    try A.add(&lines, alloc, "|-------|-----------|-------------------|-------|------|");
    for (rv.indexes) |idx| {
        const normalize = refOf(nodeProp(idx, "normalize"));
        const norm_cell = if (normalize) |n| try mdCode(alloc, n) else "\u{2014}";
        var trust_cell: []const u8 = "\u{2014}";
        if (indexIsPinned(idx)) {
            const rec = try recordEntries(alloc, nodeProp(idx, "trust"));
            var commit: []const u8 = "";
            for (rec) |e| {
                if (std.mem.eql(u8, e.name, "commit")) {
                    if (e.value) |cv| switch (cv) {
                        .string => |s| commit = s,
                        else => {},
                    };
                }
            }
            trust_cell = try std.fmt.allocPrint(alloc, "`pinned` (commit `{s}`)", .{commit});
        }
        const targets = try indexEmitTargets(alloc, idx);
        var emit_cell: []const u8 = "\u{2014}";
        if (targets.len > 0) {
            var parts: std.ArrayList([]const u8) = .empty;
            for (targets) |t| try parts.append(alloc, try mdCode(alloc, t));
            emit_cell = try joinComma(alloc, parts.items);
        }
        try A.addf(&lines, alloc, "| {s} | {s} | {s} | {s} | {s} |", .{
            try mdCode(alloc, idx.name), try indexSourceRender(alloc, idx), norm_cell, trust_cell, emit_cell,
        });
    }
    try A.add(&lines, alloc, "");

    // 3. Streams
    try A.add(&lines, alloc, "## Streams");
    try A.add(&lines, alloc, "");
    try A.add(&lines, alloc, "| Stream | Source | Type | Retention / FPS |");
    try A.add(&lines, alloc, "|--------|--------|------|-----------------|");
    for (rv.streams) |st| {
        const source = refOf(nodeProp(st, "source"));
        const typ = refOf(nodeProp(st, "type"));
        const retention = litStr(nodeProp(st, "retention"));
        const fps = litStr(nodeProp(st, "fps"));
        var rf_cell: []const u8 = "\u{2014}";
        if (retention) |r| {
            rf_cell = try std.fmt.allocPrint(alloc, "retention `{s}`", .{r});
        } else if (fps) |f| {
            rf_cell = try std.fmt.allocPrint(alloc, "fps `{s}`", .{f});
        }
        try A.addf(&lines, alloc, "| {s} | {s} | {s} | {s} |", .{
            try mdCode(alloc, st.name), try mdCode(alloc, source orelse ""), try mdCode(alloc, typ orelse ""), rf_cell,
        });
    }
    try A.add(&lines, alloc, "");

    // 4. Fibers
    try A.add(&lines, alloc, "## Fibers");
    try A.add(&lines, alloc, "");
    try A.add(&lines, alloc, "| Fiber | Engine | Input | Output | Policy |");
    try A.add(&lines, alloc, "|-------|--------|-------|--------|--------|");
    for (rv.fibers) |fib| {
        const eng = fiberEngineName(fib);
        const inp = refOf(nodeProp(fib, "input"));
        const out = refOf(nodeProp(fib, "output"));
        const policy = try renderPolicy(alloc, fib);
        try A.addf(&lines, alloc, "| {s} | {s} | {s} | {s} | {s} |", .{
            try mdCode(alloc, fib.name), try mdCode(alloc, eng orelse ""), try mdCode(alloc, inp orelse ""), try mdCode(alloc, out orelse ""), policy,
        });
    }
    try A.add(&lines, alloc, "");

    // 5. Surfaces
    try A.add(&lines, alloc, "## Surfaces");
    try A.add(&lines, alloc, "");
    try A.add(&lines, alloc, "| Surface | Mode | FPS | Input | Views |");
    try A.add(&lines, alloc, "|---------|------|-----|-------|-------|");
    for (rv.surfaces) |surf| {
        const mode = refOf(nodeProp(surf, "mode"));
        const fps = litStr(nodeProp(surf, "fps"));
        const inputs_cell = try renderRefList(alloc, nodeProp(surf, "input"));
        const views = try strList(alloc, nodeProp(surf, "views"));
        var vparts: std.ArrayList([]const u8) = .empty;
        for (views) |v| try vparts.append(alloc, try mdCode(alloc, v));
        try A.addf(&lines, alloc, "| {s} | {s} | {s} | {s} | {s} |", .{
            try mdCode(alloc, surf.name), try mdCode(alloc, mode orelse ""), try mdCode(alloc, fps orelse ""), inputs_cell, try joinComma(alloc, vparts.items),
        });
    }
    try A.add(&lines, alloc, "");

    // 6. Parallel groups
    try A.add(&lines, alloc, "## Parallel groups");
    try A.add(&lines, alloc, "");
    try A.add(&lines, alloc, "| Group | Fibers | Strategy | Supervisor |");
    try A.add(&lines, alloc, "|-------|--------|----------|------------|");
    for (rv.parallels) |par| {
        const members = try renderRefList(alloc, nodeProp(par, "fibers"));
        const strategy = litStr(nodeProp(par, "strategy"));
        const supervisor = refOf(nodeProp(par, "supervisor"));
        try A.addf(&lines, alloc, "| {s} | {s} | {s} | {s} |", .{
            try mdCode(alloc, par.name), members, try mdCode(alloc, strategy orelse ""), try mdCode(alloc, supervisor orelse ""),
        });
    }
    try A.add(&lines, alloc, "");

    // 7. Capability grants
    try A.add(&lines, alloc, "## Capability grants");
    try A.add(&lines, alloc, "");
    try A.add(&lines, alloc, "No `mesh` or `capability` declarations in this runtime, so there are no declared");
    try A.add(&lines, alloc, "principal grant-sets (0012 \u{a7}5.1). The implied daemon-channel uses follow from the");
    try A.add(&lines, alloc, "stream sources:");
    try A.add(&lines, alloc, "");
    try A.add(&lines, alloc, "| Principal / consumer | Used channel | Implied membrane |");
    try A.add(&lines, alloc, "|----------------------|--------------|------------------|");
    for (rv.streams) |st| {
        const source = refOf(nodeProp(st, "source"));
        const membrane = impliedMembrane(source);
        try A.addf(&lines, alloc, "| {s} | {s} | {s} |", .{
            try std.fmt.allocPrint(alloc, "`stream {s}`", .{st.name}), try mdCode(alloc, source orelse ""), membrane,
        });
    }
    for (rv.fibers) |fib| {
        const out = refOf(nodeProp(fib, "output"));
        if (out != null and std.mem.startsWith(u8, out.?, "artifacts.")) {
            try A.addf(&lines, alloc, "| {s} | artifact capture | `filesystem` (fs-snapshotd) |", .{
                try std.fmt.allocPrint(alloc, "`fiber {s}` (`output = {s}`)", .{ fib.name, out.? }),
            });
        }
    }
    try A.add(&lines, alloc, "");
    try A.add(&lines, alloc, "> Membranes per [`docs/context/PROJECT_CONTEXT.md`](../../../../docs/context/PROJECT_CONTEXT.md)");
    try A.add(&lines, alloc, "> and the daemon roster in [`docs/runtime/README.md`](../../../../docs/runtime/README.md).");
    try A.add(&lines, alloc, "> eBPF policy manifests / OTel config / systemd units / surface launcher are");
    try A.add(&lines, alloc, "> deferred targets (0012 \u{a7}7).");

    const text = try joinLines(alloc, lines.items);
    var files: Files = .empty;
    try files.put(alloc, "gen/RUNTIME.md", text);

    var entries: std.ArrayList(ProvEntry) = .empty;
    try entries.append(alloc, .{
        .artifact = "gen/RUNTIME.md",
        .region = "header",
        .source_file = sf,
        .decl = try std.fmt.allocPrint(alloc, "runtime {s}", .{rt_name}),
        .span = runtime.provenance.?.span,
        .emitter = "docs.runtime",
        .inputs_projection = try nodeProjection(alloc, runtime),
    });
    try appendSectionEntries(alloc, &entries, sf, rv.indexes, "indexes/", "index");
    try appendSectionEntries(alloc, &entries, sf, rv.streams, "streams/", "stream");
    try appendSectionEntries(alloc, &entries, sf, rv.fibers, "fibers/", "fiber");
    try appendSectionEntries(alloc, &entries, sf, rv.surfaces, "surfaces/", "surface");
    try appendSectionEntries(alloc, &entries, sf, rv.parallels, "parallel/", "parallel");
    return .{ .files = files, .entries = try entries.toOwnedSlice(alloc) };
}

fn appendSectionEntries(alloc: Alloc, entries: *std.ArrayList(ProvEntry), sf: []const u8, nodes: []*GraphNode, region_prefix: []const u8, kind: []const u8) !void {
    for (nodes) |n| {
        try entries.append(alloc, .{
            .artifact = "gen/RUNTIME.md",
            .region = try std.fmt.allocPrint(alloc, "{s}{s}", .{ region_prefix, n.name }),
            .source_file = sf,
            .decl = try std.fmt.allocPrint(alloc, "{s} {s}", .{ kind, n.name }),
            .span = n.provenance.?.span,
            .emitter = "docs.runtime",
            .inputs_projection = try nodeProjection(alloc, n),
        });
    }
}

/// `_render_policy`: a fiber's `policy { … }` summary for RUNTIME.md.
fn renderPolicy(alloc: Alloc, fiber: *const GraphNode) ![]const u8 {
    const fields = try fiberPolicyFields(alloc, fiber);
    if (fields.len == 0) return "\u{2014}";
    var parts: std.ArrayList([]const u8) = .empty;
    for (fields) |kv| {
        switch (kv.value) {
            .bool => |b| try parts.append(alloc, try std.fmt.allocPrint(alloc, "{s} = {s}", .{ kv.name, if (b) "true" else "false" })),
            .array => |items| {
                var ab: Buf = .empty;
                for (items, 0..) |x, i| {
                    if (i != 0) try ab.appendSlice(alloc, ", ");
                    try ab.appendSlice(alloc, try std.fmt.allocPrint(alloc, "\"{s}\"", .{scalarStr(x)}));
                }
                try parts.append(alloc, try std.fmt.allocPrint(alloc, "{s} = [{s}]", .{ kv.name, ab.items }));
            },
            else => try parts.append(alloc, try std.fmt.allocPrint(alloc, "{s} = \"{s}\"", .{ kv.name, scalarStr(kv.value) })),
        }
    }
    // "`" + "`, `".join(parts) + "`"
    var buf: Buf = .empty;
    try buf.append(alloc, '`');
    for (parts.items, 0..) |p, i| {
        if (i != 0) try buf.appendSlice(alloc, "`, `");
        try buf.appendSlice(alloc, p);
    }
    try buf.append(alloc, '`');
    return buf.toOwnedSlice(alloc);
}

const PolicyField = struct { name: []const u8, value: Value };

/// `_fiber_policy_fields`: project a fiber's policy fields in source order as
/// `[(name, value)]`. Each value is its scalar projection.
fn fiberPolicyFields(alloc: Alloc, fiber: *const GraphNode) ![]const PolicyField {
    var out: std.ArrayList(PolicyField) = .empty;
    const pol = nodeProp(fiber, "policy") orelse return out.toOwnedSlice(alloc);
    const rec = field(pol, "record") orelse return out.toOwnedSlice(alloc);
    switch (rec) {
        .array => |items| {
            for (items) |e| {
                if (field(e, "assign")) |assign_v| {
                    const name = switch (assign_v) {
                        .string => |s| s,
                        else => continue,
                    };
                    const val = scalarProp(alloc, field(e, "value")) catch continue;
                    try out.append(alloc, .{ .name = name, .value = val });
                }
            }
        },
        else => {},
    }
    return out.toOwnedSlice(alloc);
}

/// A scalar `Value` rendered as a display string (for policy table cells).
fn scalarStr(v: Value) []const u8 {
    switch (v) {
        .string => |s| return s,
        .bool => |b| return if (b) "true" else "false",
        else => return "",
    }
}

/// `_render_ref_list`: comma-joined code spans of a list/single ref prop.
fn renderRefList(alloc: Alloc, prop: ?Value) ![]const u8 {
    var parts: std.ArrayList([]const u8) = .empty;
    const p = prop orelse return joinComma(alloc, parts.items);
    switch (p) {
        .array => |items| {
            for (items) |x| {
                if (refOf(x)) |r| try parts.append(alloc, r);
            }
        },
        else => {
            if (refOf(p)) |r| try parts.append(alloc, r);
        },
    }
    var coded: std.ArrayList([]const u8) = .empty;
    for (parts.items) |r| try coded.append(alloc, try mdCode(alloc, r));
    return joinComma(alloc, coded.items);
}

/// `_implied_membrane`: the implied membrane string for a stream source channel.
fn impliedMembrane(source: ?[]const u8) []const u8 {
    const s = source orelse return "\u{2014}";
    if (std.mem.startsWith(u8, s, "agentGuardd.")) return "`ebpf` (agent-guardd)";
    if (std.mem.startsWith(u8, s, "agentpipe.")) return "`media` capture";
    return "\u{2014}";
}

// --------------------------------------------------------------------------- //
// Emitter: zig.daemoncfg (per fiber) — gen/zig/<fiber>.json.
// --------------------------------------------------------------------------- //

/// An ordered JSON object: `[(key, value)]` preserving the §5.2 schema order.
const Ordered = struct {
    pairs: []const Pair,
    const Pair = struct { key: []const u8, value: ZVal };
};

/// A zig-config JSON value: scalar `Value`, ordered object, or array.
const ZVal = union(enum) {
    scalar: Value,
    ordered: Ordered,
    array: []const ZVal,
};

fn streamForFiberInput(rv: RuntimeView, fiber: *const GraphNode) struct { st: ?*GraphNode, inp: ?[]const u8 } {
    const inp = refOf(nodeProp(fiber, "input"));
    if (inp == null) return .{ .st = null, .inp = null };
    // last segment of dotted input
    const target_name = if (std.mem.lastIndexOfScalar(u8, inp.?, '.')) |i| inp.?[i + 1 ..] else inp.?;
    for (rv.streams) |st| {
        if (std.mem.eql(u8, st.name, target_name)) return .{ .st = st, .inp = inp };
    }
    return .{ .st = null, .inp = inp };
}

fn emitZigDaemonCfg(alloc: Alloc, graph: *Graph, rv: RuntimeView, nodes: []*GraphNode) !EmitOut {
    const sf = graph.source_file;
    var files: Files = .empty;
    var entries: std.ArrayList(ProvEntry) = .empty;
    for (nodes) |fib| {
        const cfg = try zigConfigForFiber(alloc, rv, fib, sf);
        const text = try emitZigJson(alloc, cfg);
        const path = try std.fmt.allocPrint(alloc, "gen/zig/{s}.json", .{fib.name});
        try files.put(alloc, path, text);
        try entries.append(alloc, .{
            .artifact = path,
            .region = null,
            .source_file = sf,
            .decl = try std.fmt.allocPrint(alloc, "fiber {s}", .{fib.name}),
            .span = fib.provenance.?.span,
            .emitter = "zig.daemoncfg",
            .inputs_projection = try nodeProjection(alloc, fib),
        });
    }
    return .{ .files = files, .entries = try entries.toOwnedSlice(alloc) };
}

fn zigConfigForFiber(alloc: Alloc, rv: RuntimeView, fib: *const GraphNode, sf: []const u8) !Ordered {
    const eng = fiberEngineName(fib);
    const si = streamForFiberInput(rv, fib);

    var pairs: std.ArrayList(Ordered.Pair) = .empty;
    try pairs.append(alloc, .{ .key = "_generated", .value = .{ .scalar = .{ .string = try header(alloc, sf, try std.fmt.allocPrint(alloc, "fiber {s}", .{fib.name})) } } });
    if (eng) |e| {
        try pairs.append(alloc, .{ .key = "engine", .value = .{ .scalar = .{ .string = e } } });
        try pairs.append(alloc, .{ .key = "engine_package", .value = .{ .scalar = .{ .string = try std.fmt.allocPrint(alloc, "packages.{s}", .{e}) } } });
    }

    // input { stream, source, type, fps }
    if (si.st) |st| {
        var ip: std.ArrayList(Ordered.Pair) = .empty;
        try ip.append(alloc, .{ .key = "stream", .value = .{ .scalar = .{ .string = st.name } } });
        if (refOf(nodeProp(st, "source"))) |s| try ip.append(alloc, .{ .key = "source", .value = .{ .scalar = .{ .string = s } } });
        if (refOf(nodeProp(st, "type"))) |t| try ip.append(alloc, .{ .key = "type", .value = .{ .scalar = .{ .string = t } } });
        if (litStr(nodeProp(st, "fps"))) |f| try ip.append(alloc, .{ .key = "fps", .value = .{ .scalar = coerceNumber(f) } });
        if (ip.items.len > 0) {
            try pairs.append(alloc, .{ .key = "input", .value = .{ .ordered = .{ .pairs = try ip.toOwnedSlice(alloc) } } });
        }
    }

    // output { target }
    if (refOf(nodeProp(fib, "output"))) |out_ref| {
        const op = try alloc.dupe(Ordered.Pair, &.{.{ .key = "target", .value = .{ .scalar = .{ .string = out_ref } } }});
        try pairs.append(alloc, .{ .key = "output", .value = .{ .ordered = .{ .pairs = op } } });
    }

    // policy { ... } — from the enriched policy sub-block.
    const policy_fields = try fiberPolicyFields(alloc, fib);
    if (policy_fields.len > 0) {
        var pp: std.ArrayList(Ordered.Pair) = .empty;
        for (policy_fields) |kv| {
            try pp.append(alloc, .{ .key = kv.name, .value = zvalOfScalar(alloc, kv.value) });
        }
        try pairs.append(alloc, .{ .key = "policy", .value = .{ .ordered = .{ .pairs = try pp.toOwnedSlice(alloc) } } });
    }

    // budget (optional) — omitted when absent.
    if (nodeProp(fib, "budget")) |budget| {
        try pairs.append(alloc, .{ .key = "budget", .value = .{ .scalar = try scalarProp(alloc, budget) } });
    }

    // observe (default false)
    if (nodeProp(fib, "observe")) |observe| {
        try pairs.append(alloc, .{ .key = "observe", .value = .{ .scalar = try scalarProp(alloc, observe) } });
    } else {
        try pairs.append(alloc, .{ .key = "observe", .value = .{ .scalar = .{ .bool = false } } });
    }

    return .{ .pairs = try pairs.toOwnedSlice(alloc) };
}

/// Wrap a scalar policy `Value` into a `ZVal` (lists become array of scalar ZVal).
fn zvalOfScalar(alloc: Alloc, v: Value) ZVal {
    switch (v) {
        .array => |items| {
            var out = alloc.alloc(ZVal, items.len) catch unreachable;
            for (items, 0..) |x, i| out[i] = .{ .scalar = x };
            return .{ .array = out };
        },
        else => return .{ .scalar = v },
    }
}

/// `_coerce_number`: a numeric string ("10") becomes int/float for JSON (10).
fn coerceNumber(value: []const u8) Value {
    // Float if it has '.', 'e', or 'E'; else int.
    if (std.mem.indexOfAny(u8, value, ".eE") != null) {
        if (std.fmt.parseFloat(f64, value)) |f| {
            return .{ .float = f };
        } else |_| {}
    } else {
        if (std.fmt.parseInt(i64, value, 10)) |n| {
            return .{ .int = n };
        } else |_| {}
    }
    return .{ .string = value };
}

/// `_scalar_prop`: project a recorded prop value to its scalar JSON value.
fn scalarProp(alloc: Alloc, raw: ?Value) !Value {
    const r = raw orelse return .null;
    switch (r) {
        .bool => return r,
        .object => {
            if (field(r, "lit")) |kind_v| {
                const kind = switch (kind_v) {
                    .string => |s| s,
                    else => return r,
                };
                const val = field(r, "value");
                if (std.mem.eql(u8, kind, "number")) {
                    if (val) |v| switch (v) {
                        .string => |s| return coerceNumber(s),
                        else => return v,
                    };
                    return .null;
                }
                if (std.mem.eql(u8, kind, "bool") or std.mem.eql(u8, kind, "boolean")) {
                    if (val) |v| switch (v) {
                        .string => |s| return .{ .bool = std.mem.eql(u8, s, "true") },
                        .bool => |b| return .{ .bool = b },
                        else => return .{ .bool = false },
                    };
                    return .{ .bool = false };
                }
                return val orelse .null;
            }
            if (refOf(r)) |rr| return .{ .string = rr };
            return r;
        },
        .array => |items| {
            var out = try alloc.alloc(Value, items.len);
            for (items, 0..) |x, i| out[i] = try scalarProp(alloc, x);
            return .{ .array = out };
        },
        else => return r,
    }
}

/// Serialize an `Ordered` config to the §5.2 JSON layout (2-space indent, one
/// member per line, inline scalar arrays), with a trailing newline.
fn emitZigJson(alloc: Alloc, obj: Ordered) ![]u8 {
    var buf: Buf = .empty;
    try emitZigVal(alloc, &buf, .{ .ordered = obj }, 0);
    try buf.append(alloc, '\n');
    return buf.toOwnedSlice(alloc);
}

fn emitZigVal(alloc: Alloc, buf: *Buf, val: ZVal, level: usize) WriteError!void {
    switch (val) {
        .ordered => |o| {
            if (o.pairs.len == 0) {
                try buf.appendSlice(alloc, "{}");
                return;
            }
            try buf.appendSlice(alloc, "{\n");
            for (o.pairs, 0..) |p, i| {
                try writeIndent(alloc, buf, level + 1);
                try json_canon.writeJsonString(buf, alloc, p.key);
                try buf.appendSlice(alloc, ": ");
                try emitZigVal(alloc, buf, p.value, level + 1);
                if (i != o.pairs.len - 1) try buf.append(alloc, ',');
                try buf.append(alloc, '\n');
            }
            try writeIndent(alloc, buf, level);
            try buf.append(alloc, '}');
        },
        .array => |items| {
            // one-line array of scalars
            try buf.append(alloc, '[');
            for (items, 0..) |x, i| {
                if (i != 0) try buf.appendSlice(alloc, ", ");
                try emitZigVal(alloc, buf, x, level + 1);
            }
            try buf.append(alloc, ']');
        },
        .scalar => |v| try json_canon.writeValueCompact(buf, alloc, v),
    }
}

fn writeIndent(alloc: Alloc, buf: *Buf, level: usize) !void {
    var i: usize = 0;
    while (i < level) : (i += 1) try buf.appendSlice(alloc, "  ");
}

// --------------------------------------------------------------------------- //
// Emitter: catalog.jsonl (per index w/ emit ∋ catalog.jsonl) — gen/catalog/<n>.jsonl.
// --------------------------------------------------------------------------- //

const CatalogRow = struct { owner_repo: []const u8, path: []const u8, text: []const u8 };

/// Placeholder catalog rows keyed by index name (0012 §5.3b).
fn catalogPlaceholderRows(name: []const u8) []const CatalogRow {
    if (std.mem.eql(u8, name, "zigCorpus")) {
        const rows = struct {
            const r = [_]CatalogRow{
                .{ .owner_repo = "Sobeston/zig.guide", .path = "chapter-1/hello-world.md", .text = "# Hello World\n\nCreate a file `hello.zig` and run it with `zig run hello.zig`." },
                .{ .owner_repo = "zigimg/zigimg", .path = "README.md", .text = "# zigimg\n\nZig library for reading and writing images in a variety of formats." },
            };
        };
        return &rows.r;
    }
    return &.{};
}

fn catalogRowId(alloc: Alloc, owner_repo: []const u8, n: usize) ![]const u8 {
    const repo = if (std.mem.lastIndexOfScalar(u8, owner_repo, '/')) |i| owner_repo[i + 1 ..] else owner_repo;
    return std.fmt.allocPrint(alloc, "{s}#{d:0>4}", .{ repo, n });
}

/// Compact JSON object in INSERTION order (no key sorting) — mirrors Python's
/// `json.dumps(obj, separators=(",",":"))` over an ordered dict (the catalog
/// header + rows, 0012 §5.3b). Values are scalars here, written via the core
/// compact writer.
fn writeCompactOrdered(buf: *Buf, alloc: Alloc, fields: []const Value.Field) WriteError!void {
    try buf.append(alloc, '{');
    for (fields, 0..) |f, i| {
        if (i != 0) try buf.append(alloc, ',');
        try json_canon.writeJsonString(buf, alloc, f.key);
        try buf.append(alloc, ':');
        try json_canon.writeValueCompact(buf, alloc, f.value);
    }
    try buf.append(alloc, '}');
}

fn emitCatalogJsonl(alloc: Alloc, graph: *Graph, nodes: []*GraphNode) !EmitOut {
    const sf = graph.source_file;
    var files: Files = .empty;
    var entries: std.ArrayList(ProvEntry) = .empty;
    for (nodes) |idx| {
        var lines: std.ArrayList([]const u8) = .empty;
        // header object — compact JSON: {"_generated":"..."}
        const hdr = try header(alloc, sf, try std.fmt.allocPrint(alloc, "index {s}", .{idx.name}));
        const hdr_fields = try alloc.dupe(Value.Field, &.{.{ .key = "_generated", .value = .{ .string = hdr } }});
        var hb: Buf = .empty;
        try writeCompactOrdered(&hb, alloc, hdr_fields);
        try lines.append(alloc, try hb.toOwnedSlice(alloc));

        const rows = catalogPlaceholderRows(idx.name);
        var per_repo: std.StringArrayHashMapUnmanaged(usize) = .empty;
        for (rows) |row| {
            const repo = if (std.mem.lastIndexOfScalar(u8, row.owner_repo, '/')) |i| row.owner_repo[i + 1 ..] else row.owner_repo;
            const gop = try per_repo.getOrPut(alloc, repo);
            if (!gop.found_existing) gop.value_ptr.* = 0;
            gop.value_ptr.* += 1;
            const n = gop.value_ptr.*;
            // Build the row object in the §5.3b key order: id, source, path,
            // chunk, text — emitted in INSERTION order (Python's json.dumps over
            // an ordered dict; NOT sorted).
            const id = try catalogRowId(alloc, row.owner_repo, n);
            const source = try std.fmt.allocPrint(alloc, "github:{s}", .{row.owner_repo});
            const row_fields = try alloc.dupe(Value.Field, &.{
                .{ .key = "id", .value = .{ .string = id } },
                .{ .key = "source", .value = .{ .string = source } },
                .{ .key = "path", .value = .{ .string = row.path } },
                .{ .key = "chunk", .value = .{ .int = 0 } },
                .{ .key = "text", .value = .{ .string = row.text } },
            });
            var rb: Buf = .empty;
            try writeCompactOrdered(&rb, alloc, row_fields);
            try lines.append(alloc, try rb.toOwnedSlice(alloc));
        }
        const text = try joinLines(alloc, lines.items);
        const path = try std.fmt.allocPrint(alloc, "gen/catalog/{s}.jsonl", .{idx.name});
        try files.put(alloc, path, text);
        try entries.append(alloc, .{
            .artifact = path,
            .region = null,
            .source_file = sf,
            .decl = try std.fmt.allocPrint(alloc, "index {s}", .{idx.name}),
            .span = idx.provenance.?.span,
            .emitter = "catalog.jsonl",
            .inputs_projection = try nodeProjection(alloc, idx),
        });
    }
    return .{ .files = files, .entries = try entries.toOwnedSlice(alloc) };
}

// --------------------------------------------------------------------------- //
// Graph enrichment — recover the fiber `policy { … }` sub-block.
// --------------------------------------------------------------------------- //

/// `_config_block_name`: the field name of a bare config-block App (`policy {…}`):
/// a single-segment ref with a record body and no call args. Else null.
fn configBlockName(app: ast.App) ?[]const u8 {
    if (app.args != null or app.record == null) return null;
    if (app.ref.parts.len != 1) return null;
    return app.ref.parts[0];
}

fn isConfigBlockAllowed(decl_kind: []const u8, name: []const u8) bool {
    // _CONFIG_BLOCK_FIELDS = {"fiber": {"policy"}}
    return std.mem.eql(u8, decl_kind, "fiber") and std.mem.eql(u8, name, "policy");
}

/// `_value_to_props` for the policy-block App. Mirrors `resolve.py:_value_to_props`
/// for an App: `{"ref": dotted, "record": [entries]}` (the App branch keeps the
/// `ref` — for `policy { … }` that is `"policy"`). The `ref` field is
/// load-bearing: the §6.2 projection hash is computed over it.
fn appRecordToProps(alloc: Alloc, app: ast.App) !Value {
    return exprToProps(alloc, .{ .app = app });
}

fn entriesToProps(alloc: Alloc, entries: []const ast.Entry) !Value {
    var arr = try alloc.alloc(Value, entries.len);
    for (entries, 0..) |e, i| arr[i] = try entryToProps(alloc, e);
    return .{ .array = arr };
}

fn entryToProps(alloc: Alloc, e: ast.Entry) !Value {
    switch (e) {
        .assignment => |a| {
            const fields = try alloc.dupe(Value.Field, &.{
                .{ .key = "assign", .value = .{ .string = a.target } },
                .{ .key = "op", .value = .{ .string = a.op } },
                .{ .key = "value", .value = try exprToProps(alloc, a.value) },
            });
            return .{ .object = fields };
        },
        .inherit => |ih| {
            var arr = try alloc.alloc(Value, ih.names.len);
            for (ih.names, 0..) |nm, i| arr[i] = .{ .string = nm };
            const fields = try alloc.dupe(Value.Field, &.{.{ .key = "inherit", .value = .{ .array = arr } }});
            return .{ .object = fields };
        },
    }
}

/// `_value_to_props` for an expression. Mirrors resolve.py exactly.
fn exprToProps(alloc: Alloc, v: ast.Expr) (Alloc.Error)!Value {
    switch (v) {
        .literal => |lit| {
            const fields = try alloc.dupe(Value.Field, &.{
                .{ .key = "lit", .value = .{ .string = lit.kind.lower() } },
                .{ .key = "value", .value = .{ .string = lit.value } },
            });
            return .{ .object = fields };
        },
        .list => |ll| {
            var arr = try alloc.alloc(Value, ll.items.len);
            for (ll.items, 0..) |x, i| arr[i] = try exprToProps(alloc, x);
            return .{ .array = arr };
        },
        .record => |rl| {
            const fields = try alloc.dupe(Value.Field, &.{.{ .key = "record", .value = try entriesToProps(alloc, rl.entries) }});
            return .{ .object = fields };
        },
        .app => |a| {
            var fields: std.ArrayList(Value.Field) = .empty;
            try fields.append(alloc, .{ .key = "ref", .value = .{ .string = try a.ref.dotted(alloc) } });
            if (a.args) |args| {
                var arr = try alloc.alloc(Value, args.len);
                for (args, 0..) |x, i| arr[i] = try exprToProps(alloc, x);
                try fields.append(alloc, .{ .key = "args", .value = .{ .array = arr } });
            }
            if (a.record) |rec| {
                try fields.append(alloc, .{ .key = "record", .value = try entriesToProps(alloc, rec) });
            }
            return .{ .object = try fields.toOwnedSlice(alloc) };
        },
    }
}

/// Append a `policy` prop to a node's `props` object (the node props is a
/// `Value.object`). Returns a new object Value with the field appended.
fn objectWithField(alloc: Alloc, obj: Value, key: []const u8, value: Value) !Value {
    var fields: std.ArrayList(Value.Field) = .empty;
    switch (obj) {
        .object => |existing| {
            for (existing) |f| try fields.append(alloc, f);
        },
        else => {},
    }
    try fields.append(alloc, .{ .key = key, .value = value });
    return .{ .object = try fields.toOwnedSlice(alloc) };
}

/// `_node_for_chain`: find the graph node whose id ends with the decl-name chain.
fn nodeForChain(alloc: Alloc, graph: *Graph, chain: []const []const u8) !?*GraphNode {
    const joined = try std.mem.join(alloc, "/", chain);
    const suffix = try std.fmt.allocPrint(alloc, "#{s}", .{joined});
    var it = graph.nodes.iterator();
    while (it.next()) |entry| {
        const n = entry.value_ptr;
        if (std.mem.endsWith(u8, n.id, suffix) and n.provenance != null) return n;
    }
    return null;
}

const EnrichError = error{OutOfMemory};

/// `enrich_graph`: attach dropped config sub-blocks (a fiber's `policy { … }`) to
/// their graph nodes, in place. Idempotent; adds no nodes/edges.
fn enrichGraph(alloc: Alloc, graph: *Graph, items: []const ast.Item) EnrichError!void {
    for (items) |it| {
        switch (it) {
            .decl => |d| try enrichWalk(alloc, graph, d, &.{d.name}),
            .import => {},
        }
    }
}

fn enrichWalk(alloc: Alloc, graph: *Graph, decl: ast.Decl, chain: []const []const u8) EnrichError!void {
    if (try nodeForChain(alloc, graph, chain)) |node| {
        for (decl.body) |st| {
            switch (st) {
                .app => |app| {
                    if (configBlockName(app)) |name| {
                        if (isConfigBlockAllowed(decl.kind, name) and !hasField(node.props, name)) {
                            const pv = try appRecordToProps(alloc, app);
                            node.props = try objectWithField(alloc, node.props, name, pv);
                        }
                    }
                },
                else => {},
            }
        }
    }
    for (decl.body) |st| {
        switch (st) {
            .decl => |child| {
                const new_chain = try alloc.alloc([]const u8, chain.len + 1);
                @memcpy(new_chain[0..chain.len], chain);
                new_chain[chain.len] = child.name;
                try enrichWalk(alloc, graph, child, new_chain);
            },
            else => {},
        }
    }
}

// --------------------------------------------------------------------------- //
// Provenance manifest serialization (the §6.2 fixture layout).
// --------------------------------------------------------------------------- //

/// Build the provenance.json document (0012 §6.2). The `artifacts` map is keyed
/// lexicographically by artifact path; per-artifact entries preserve emission
/// order. Returns a `Value` whose object field order is the intended pretty-print
/// order (the pretty-printer preserves insertion order, not sorting).
fn buildProvenance(alloc: Alloc, source_file: []const u8, entries: []const ProvEntry) !Value {
    // Group entries by artifact, preserving first-seen order then sort the keys.
    var artifacts: std.StringArrayHashMapUnmanaged(std.ArrayList(ProvEntry)) = .empty;
    for (entries) |ent| {
        const gop = try artifacts.getOrPut(alloc, ent.artifact);
        if (!gop.found_existing) gop.value_ptr.* = .empty;
        try gop.value_ptr.append(alloc, ent);
    }

    // Sort artifact paths lexicographically.
    const keys = try alloc.dupe([]const u8, artifacts.keys());
    std.mem.sort([]const u8, keys, {}, lessStr);

    var art_fields: std.ArrayList(Value.Field) = .empty;
    for (keys) |path| {
        const arr_entries = artifacts.get(path).?;
        var out_entries = try alloc.alloc(Value, arr_entries.items.len);
        for (arr_entries.items, 0..) |ent, i| {
            var ef: std.ArrayList(Value.Field) = .empty;
            if (ent.region) |r| try ef.append(alloc, .{ .key = "region", .value = .{ .string = r } });
            try ef.append(alloc, .{ .key = "sourceFile", .value = .{ .string = ent.source_file } });
            try ef.append(alloc, .{ .key = "decl", .value = .{ .string = ent.decl } });
            // span object (in field order file, byteStart, byteEnd, line, col).
            const span_fields = try alloc.dupe(Value.Field, &.{
                .{ .key = "file", .value = .{ .string = ent.source_file } },
                .{ .key = "byteStart", .value = .{ .int = @intCast(ent.span.byteStart) } },
                .{ .key = "byteEnd", .value = .{ .int = @intCast(ent.span.byteEnd) } },
                .{ .key = "line", .value = .{ .int = @intCast(ent.span.line) } },
                .{ .key = "col", .value = .{ .int = @intCast(ent.span.col) } },
            });
            try ef.append(alloc, .{ .key = "span", .value = .{ .object = span_fields } });
            try ef.append(alloc, .{ .key = "emitter", .value = .{ .string = ent.emitter } });
            try ef.append(alloc, .{ .key = "inputsHash", .value = .{ .string = try inputsHash(alloc, ent.inputs_projection) } });
            out_entries[i] = .{ .object = try ef.toOwnedSlice(alloc) };
        }
        try art_fields.append(alloc, .{ .key = path, .value = .{ .array = out_entries } });
    }

    const doc_fields = try alloc.dupe(Value.Field, &.{
        .{ .key = "version", .value = .{ .int = 1 } },
        .{ .key = "source", .value = .{ .string = source_file } },
        .{ .key = "artifacts", .value = .{ .object = try art_fields.toOwnedSlice(alloc) } },
    });
    return .{ .object = doc_fields };
}

fn lessStr(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.lessThan(u8, a, b);
}

const SPAN_KEY = "span";

/// Error set for the JSON serializers — `writeValueCompact` bottoms out in
/// `bufPrint` (numbers), which can return `error.NoSpaceLeft` in addition to the
/// allocator's `OutOfMemory`. Mutually-recursive fns need an explicit set.
const WriteError = error{ OutOfMemory, NoSpaceLeft };

/// A value rendered on one line with `", "` / `": "` spacing (the span object).
fn jsonInline(buf: *Buf, alloc: Alloc, v: Value) WriteError!void {
    switch (v) {
        .object => |fields| {
            if (fields.len == 0) {
                try buf.appendSlice(alloc, "{}");
                return;
            }
            try buf.appendSlice(alloc, "{ ");
            for (fields, 0..) |f, i| {
                if (i != 0) try buf.appendSlice(alloc, ", ");
                try json_canon.writeJsonString(buf, alloc, f.key);
                try buf.appendSlice(alloc, ": ");
                try jsonInline(buf, alloc, f.value);
            }
            try buf.appendSlice(alloc, " }");
        },
        .array => |items| {
            if (items.len == 0) {
                try buf.appendSlice(alloc, "[]");
                return;
            }
            try buf.append(alloc, '[');
            for (items, 0..) |x, i| {
                if (i != 0) try buf.appendSlice(alloc, ", ");
                try jsonInline(buf, alloc, x);
            }
            try buf.append(alloc, ']');
        },
        else => try jsonScalar(buf, alloc, v),
    }
}

/// A scalar JSON value (json.dumps, ensure_ascii=False).
fn jsonScalar(buf: *Buf, alloc: Alloc, v: Value) WriteError!void {
    try json_canon.writeValueCompact(buf, alloc, v);
}

/// Pretty-print `v` at a 2-space indent, but render any `span` object inline.
/// Object keys keep insertion order; list items keep order. Mirrors `_json_pretty`.
fn jsonPretty(buf: *Buf, alloc: Alloc, v: Value, level: usize) WriteError!void {
    switch (v) {
        .object => |fields| {
            if (fields.len == 0) {
                try buf.appendSlice(alloc, "{}");
                return;
            }
            try buf.appendSlice(alloc, "{\n");
            for (fields, 0..) |f, i| {
                try writeIndent(alloc, buf, level + 1);
                try json_canon.writeJsonString(buf, alloc, f.key);
                try buf.appendSlice(alloc, ": ");
                if (std.mem.eql(u8, f.key, SPAN_KEY)) {
                    try jsonInline(buf, alloc, f.value);
                } else {
                    try jsonPretty(buf, alloc, f.value, level + 1);
                }
                if (i != fields.len - 1) try buf.append(alloc, ',');
                try buf.append(alloc, '\n');
            }
            try writeIndent(alloc, buf, level);
            try buf.append(alloc, '}');
        },
        .array => |items| {
            if (items.len == 0) {
                try buf.appendSlice(alloc, "[]");
                return;
            }
            try buf.appendSlice(alloc, "[\n");
            for (items, 0..) |x, i| {
                try writeIndent(alloc, buf, level + 1);
                try jsonPretty(buf, alloc, x, level + 1);
                if (i != items.len - 1) try buf.append(alloc, ',');
                try buf.append(alloc, '\n');
            }
            try writeIndent(alloc, buf, level);
            try buf.append(alloc, ']');
        },
        else => try jsonScalar(buf, alloc, v),
    }
}

/// Serialize a provenance document to the §6.2 fixture bytes: 2-space indent,
/// inline `span` objects, trailing newline.
pub fn provenanceJsonText(alloc: Alloc, provenance_doc: Value) ![]u8 {
    var buf: Buf = .empty;
    try jsonPretty(&buf, alloc, provenance_doc, 0);
    try buf.append(alloc, '\n');
    return buf.toOwnedSlice(alloc);
}

// --------------------------------------------------------------------------- //
// The lowering driver.
// --------------------------------------------------------------------------- //

pub const LowerError = error{OutOfMemory};

/// Lower a *validated* graph to artifacts + a provenance manifest (0012). When
/// `items` is supplied, `enrichGraph` runs first (recovers the fiber policy
/// sub-block). Pure: no IO (the caller writes `result.files`).
pub fn lower(alloc: Alloc, graph: *Graph, items: ?[]const ast.Item) LowerError!LowerResult {
    if (items) |its| try enrichGraph(alloc, graph, its);

    const rv_opt = runtimeView(alloc, graph) catch return error.OutOfMemory;

    if (rv_opt == null) {
        const prov = (buildProvenance(alloc, graph.source_file, &.{})) catch return error.OutOfMemory;
        return LowerResult{ .files = .empty, .provenance = prov };
    }
    const rv = rv_opt.?;

    var files: Files = .empty;
    var all_entries: std.ArrayList(ProvEntry) = .empty;

    const Run = struct {
        fn merge(a: Alloc, dst: *Files, ents: *std.ArrayList(ProvEntry), out: EmitOut) !void {
            var it = out.files.iterator();
            while (it.next()) |e| try dst.put(a, e.key_ptr.*, e.value_ptr.*);
            for (out.entries) |x| try ents.append(a, x);
        }
    };

    // ALWAYS: the Nix spine + docs.
    Run.merge(alloc, &files, &all_entries, emitNixSpine(alloc, graph, rv) catch return error.OutOfMemory) catch return error.OutOfMemory;
    Run.merge(alloc, &files, &all_entries, emitDocsRuntime(alloc, graph, rv) catch return error.OutOfMemory) catch return error.OutOfMemory;

    // Direct: per-fiber Zig daemon configs.
    if (rv.fibers.len > 0) {
        Run.merge(alloc, &files, &all_entries, emitZigDaemonCfg(alloc, graph, rv, rv.fibers) catch return error.OutOfMemory) catch return error.OutOfMemory;
    }

    // Direct: catalog.jsonl for indexes that select it.
    var jsonl_indexes: std.ArrayList(*GraphNode) = .empty;
    for (rv.indexes) |i| {
        if (hasTarget(indexEmitTargets(alloc, i) catch return error.OutOfMemory, "catalog.jsonl")) {
            jsonl_indexes.append(alloc, i) catch return error.OutOfMemory;
        }
    }
    if (jsonl_indexes.items.len > 0) {
        Run.merge(alloc, &files, &all_entries, emitCatalogJsonl(alloc, graph, jsonl_indexes.items) catch return error.OutOfMemory) catch return error.OutOfMemory;
    }

    const provenance = buildProvenance(alloc, graph.source_file, all_entries.items) catch return error.OutOfMemory;
    return LowerResult{ .files = files, .provenance = provenance };
}

// --------------------------------------------------------------------------- //
// tests
// --------------------------------------------------------------------------- //

test "header file basename and header format" {
    const a = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(a);
    defer arena.deinit();
    const al = arena.allocator();
    try std.testing.expectEqualStrings("operator-field.vaked", try headerFile(al, "vaked/examples/operator-field.vaked"));
    const h = try header(al, "vaked/examples/operator-field.vaked", "runtime operator-field");
    try std.testing.expectEqualStrings("generated by Vaked from operator-field.vaked:runtime operator-field \u{2014} do not edit", h);
}

test "nix source slug normalizes . and _ to -" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const al = arena.allocator();
    try std.testing.expectEqualStrings("zig-guide", try nixSourceSlug(al, "Sobeston/zig.guide"));
    try std.testing.expectEqualStrings("zigimg", try nixSourceSlug(al, "zigimg/zigimg"));
}

test "coerce number int and float and passthrough" {
    try std.testing.expectEqual(@as(i64, 10), coerceNumber("10").int);
    try std.testing.expectEqual(@as(f64, 1.5), coerceNumber("1.5").float);
    try std.testing.expectEqualStrings("4K", coerceNumber("4K").string);
}

test "catalog row id zero-padded" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const al = arena.allocator();
    try std.testing.expectEqualStrings("zig.guide#0001", try catalogRowId(al, "Sobeston/zig.guide", 1));
}
