const std = @import("std");
const graph = @import("graph.zig");
const GENESIS = "7c242080";

pub fn toVaked(a: std.mem.Allocator, g: graph.Graph) ![]u8 {
    var buf = std.ArrayListUnmanaged(u8){ .items = &.{}, .capacity = 0 };
    try buf.appendSlice(a, "# generated by anti-gravity CLI\n");
    try buf.appendSlice(a, "# Genesis: 7c242080\n\n");
    for (g.nodes.items) |n| {
        try buf.appendSlice(a, "node ");
        try buf.appendSlice(a, n.name);
        try buf.appendSlice(a, "\n");
    }
    for (g.edges.items) |e| {
        try buf.appendSlice(a, "edge ");
        try buf.appendSlice(a, e.from);
        try buf.appendSlice(a, " -> ");
        try buf.appendSlice(a, e.to);
        if (e.trust > 0) {
            try buf.appendSlice(a, " trust ");
            try buf.append(a, @intCast(48 + @as(u8, @intFromFloat(e.trust * 10))));
        }
        try buf.appendSlice(a, "\n");
    }
    return buf.items;
}

pub fn sealSignature(a: std.mem.Allocator) ![]u8 {
    var digest: [32]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(GENESIS, &digest, .{});
    var hex: [64]u8 = undefined;
    const hex_chars = "0123456789abcdef";
    for (digest, 0..) |byte, i| {
        hex[i*2] = hex_chars[byte >> 4];
        hex[i*2+1] = hex_chars[byte & 0xf];
    }
    return a.dupe(u8, hex[0..]);
}
