// GENESIS_SEAL: 7c242080
//! vakedz.lower tests — byte-parity of the lowering artifact emitters against
//! the frozen, hand-authored fixture tree under `vaked/examples/lowering/`.
//!
//! That tree IS the byte golden: `tests/spec/test_vakedc_lower.py` asserts
//! `vakedc.lower.lower(build_graph(parse(operator-field.vaked)))` reproduces
//! every file in it exactly, and `tests/spec/test_lowering_fixtures.py`
//! independently re-derives the fixtures' spans, key order and header format
//! from first principles. Matching these bytes therefore matches vakedc.
//!
//! Everything below is a byte-exact embedded copy of a file in the repo (the
//! established emit_test.zig/resolve_test.zig convention) so the test stays
//! hermetic — no fixture IO from a unit test.
const std = @import("std");
const testing = std.testing;
const lib = @import("lib");
const lex = @import("lexer.zig");
const parser = @import("parser.zig");
const resolve = @import("resolve.zig");
const lower = @import("lower.zig");

fn parseItems(a: std.mem.Allocator, src: []const u8) ![]const parser.Item {
    var l = lex.Lexer.init(a, src);
    try l.run();
    try testing.expectEqual(@as(usize, 0), l.errors.items.len);
    var p = parser.Parser.init(a, l.tokens.items);
    return p.parseFile();
}

/// The exact driver order of `vakedc lower`: parse -> build_graph -> lower
/// (which runs enrich_graph first when items are supplied).
fn lowerSource(a: std.mem.Allocator, src: []const u8, filename: []const u8) !lower.LowerResult {
    const items = try parseItems(a, src);
    var res = try resolve.buildGraph(a, items, filename);
    return lower.lower(a, &res.graph, filename, items);
}

fn fileContent(result: lower.LowerResult, path: []const u8) ?[]const u8 {
    for (result.files) |f| {
        if (std.mem.eql(u8, f.path, path)) return f.content;
    }
    return null;
}

// --------------------------------------------------------------------------
// Byte-exact embedded copy of vaked/examples/operator-field.vaked (1518 bytes).
// --------------------------------------------------------------------------

const operator_field_src =
    \\use "./engines/zig.vaked"
    \\
    \\runtime "operator-field" {
    \\  systems = ["x86_64-linux", "aarch64-linux"]
    \\
    \\  # Daemon-channel namespaces declared for this runtime (RFC 0017, D3: runtime-scoped).
    \\  namespace agentGuardd {
    \\    member ringbuf
    \\  }
    \\  namespace agentpipe {
    \\    member transcripts
    \\    member screenrec
    \\  }
    \\
    \\  index zigCorpus {
    \\    source = [github("Sobeston/zig.guide"), github("C-BJ/awesome-zig"), github("raylib-zig/raylib-zig"), github("zigimg/zigimg")]
    \\
    \\    normalize = crabcc.markdown
    \\    emit = [catalog.jsonl, catalog.sqlite, nix.derivation]
    \\  }
    \\
    \\  index zigbeeFirmware {
    \\    source = raw.github("Koenkk/zigbee-OTA", "index.json")
    \\    schema = schema.zigbeeOta
    \\    trust = pinned {
    \\      commit = "<commit>"
    \\      sha256 = "<sha256>"
    \\    }
    \\  }
    \\
    \\  stream ebpfEvents {
    \\    source = agentGuardd.ringbuf
    \\    type = Event.Ebpf
    \\    retention = 24h
    \\  }
    \\
    \\  stream screenrec {
    \\    source = agentpipe.screenrec
    \\    type = Media.Frame
    \\    fps = 10
    \\  }
    \\
    \\  fiber mediaCompress {
    \\    engine = zigDaemon
    \\    input = stream.screenrec
    \\    output = artifacts.compressedMedia
    \\
    \\    policy {
    \\      strip_metadata = true
    \\      max_pixels = "4K"
    \\      formats = ["png", "webp"]
    \\    }
    \\  }
    \\
    \\  surface operatorMap {
    \\    mode = raylib
    \\    fps = 60
    \\    input = [stream.ebpfEvents, graph.workflow, graph.agentfield]
    \\    views = ["network-flows", "workflow-dag", "filesystem-diff", "mesh-topology"]
    \\  }
    \\
    \\  parallel "operator-runtime" {
    \\    fibers = [mediaCompress, operatorMap]
    \\    strategy = "supervised-dag"
    \\    supervisor = otp
    \\  }
    \\}
++ "\n";

// --------------------------------------------------------------------------
// Byte-exact embedded copy of vaked/examples/lowering/flake.nix (4578 bytes) --
// the `nix.spine` golden.
// --------------------------------------------------------------------------

const golden_flake_nix =
    \\# generated by Vaked from operator-field.vaked:runtime operator-field — do not edit
    \\#
    \\# Expected-output fixture (no compiler exists yet) — see ./README.md and
    \\# docs/language/0012-lowering.md §4 (the Nix spine). Edits belong in the source
    \\# .vaked file, not here.
    \\{
    \\  description = "operator-field — generated by Vaked";
    \\
    \\  inputs = {
    \\    # nixpkgs is emitted pinned to the toolchain's baseline rev (0012 §4.1): an
    \\    # explicit rev, never a moving channel ref. The 40-hex value below is a
    \\    # disclosed placeholder (all-`b` = "baseline"; see ./README.md); the
    \\    # committed flake.lock (produced at first build) records the real resolution.
    \\    nixpkgs.url = "github:NixOS/nixpkgs/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
    \\
    \\    # index zigCorpus — sources (unpinned; flake.lock records the resolved rev).
    \\    # 0012 §4.2: each index source becomes a flake input.
    \\    zigCorpus-src-zig-guide = { url = "github:Sobeston/zig.guide"; flake = false; };
    \\    zigCorpus-src-awesome-zig = { url = "github:C-BJ/awesome-zig"; flake = false; };
    \\    zigCorpus-src-raylib-zig = { url = "github:raylib-zig/raylib-zig"; flake = false; };
    \\    zigCorpus-src-zigimg = { url = "github:zigimg/zigimg"; flake = false; };
    \\
    \\    # index zigbeeFirmware — trust = pinned { commit, sha256 } (0012 §4.2):
    \\    # commit pins the rev; sha256 is recorded as the lock entry's narHash so the
    \\    # build verifies the fetch. raw.github(...) => flake = false.
    \\    zigbeeFirmware-src = {
    \\      url = "github:Koenkk/zigbee-OTA/<commit>"; # trust.pinned.commit
    \\      flake = false;
    \\    };
    \\  };
    \\
    \\  outputs = { self, nixpkgs, ... }@inputs:
    \\    let
    \\      # runtime operator-field — systems = ["x86_64-linux", "aarch64-linux"]
    \\      systems = [ "x86_64-linux" "aarch64-linux" ];
    \\      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f system);
    \\    in
    \\    {
    \\      # nixosModules.<runtime> — wires the OTP/Zig daemons and references the
    \\      # gen/ artifacts as installed files (0012 §4.3).
    \\      nixosModules.operator-field = import ./nixos/operator-field.nix {
    \\        # NixOS module fixture is described in 0012 §4.3; not emitted as a
    \\        # separate file in this fixture set (interface only).
    \\        inherit self;
    \\      };
    \\
    \\      packages = forAllSystems (system:
    \\        let pkgs = nixpkgs.legacyPackages.${system};
    \\        in {
    \\          # engine zigDaemon (fiber mediaCompress: engine = zigDaemon) — built Zig pkg.
    \\          zigDaemon = pkgs.callPackage ./pkgs/zigDaemon.nix { };
    \\
    \\          # index zigCorpus, emit ∋ nix.derivation (0012 §5.3a) — CrabCC index
    \\          # derivation; runs crabcc at build time over the pinned sources with
    \\          # normalize = crabcc.markdown.
    \\          zigCorpus-crabcc-index = pkgs.stdenv.mkDerivation {
    \\            pname = "zigCorpus-crabcc-index";
    \\            version = "0";
    \\            srcs = [
    \\              inputs.zigCorpus-src-zig-guide
    \\              inputs.zigCorpus-src-awesome-zig
    \\              inputs.zigCorpus-src-raylib-zig
    \\              inputs.zigCorpus-src-zigimg
    \\            ];
    \\            nativeBuildInputs = [ pkgs.crabcc ];
    \\            buildPhase = ''
    \\              # normalize = crabcc.markdown ; emit = catalog.jsonl, catalog.sqlite
    \\              crabcc index build --normalize markdown \
    \\                --emit jsonl --emit sqlite \
    \\                --out $out
    \\            '';
    \\          };
    \\        });
    \\
    \\      apps = forAllSystems (system:
    \\        let pkgs = nixpkgs.legacyPackages.${system};
    \\        in {
    \\          # surface operatorMap (mode = raylib) — launcher app.
    \\          # 0012 §7: surface launcher body is DEFERRED (no-op today). The slot
    \\          # exists so the registry test stays honest, but the mapping (raylib
    \\          # host integration) is not yet specified. The deferred body is derived
    \\          # from NOTHING but the surface decl name: a stub that exits non-zero
    \\          # with the standard deferral message — no real launcher is wired, and
    \\          # it does not route through any engine/fiber package.
    \\          operatorMap = {
    \\            type = "app";
    \\            program = "${pkgs.writeShellScript "operatorMap-launcher-deferred" ''
    \\              echo "vaked: surface launcher lowering deferred (0012 §7)" >&2
    \\              exit 1
    \\            ''}";
    \\          };
    \\        });
    \\
    \\      devShells = forAllSystems (system:
    \\        let pkgs = nixpkgs.legacyPackages.${system};
    \\        in {
    \\          default = pkgs.mkShell {
    \\            # toolchains the runtime needs: zig (engines), crabcc (index).
    \\            packages = [ pkgs.zig pkgs.crabcc ];
    \\          };
    \\        });
    \\    };
    \\}
++ "\n";

// --------------------------------------------------------------------------
// Byte-exact embedded copy of vaked/examples/lowering/gen/RUNTIME.md (2703
// bytes) -- the `docs.runtime` golden.
// --------------------------------------------------------------------------

const golden_runtime_md =
    \\<!-- generated by Vaked from operator-field.vaked:runtime operator-field — do not edit -->
    \\
    \\# Runtime: operator-field
    \\
    \\Generated from `operator-field.vaked`. This document is a rendering of the
    \\`runtime operator-field` declaration — see
    \\[`docs/language/0012-lowering.md`](../../../../docs/language/0012-lowering.md)
    \\§5.1. Do not edit; regenerate from source.
    \\
    \\- **Systems:** `x86_64-linux`, `aarch64-linux`
    \\
    \\## Indexes
    \\
    \\| Index | Source(s) | Normalize / Chunk | Trust | Emit |
    \\|-------|-----------|-------------------|-------|------|
    \\| `zigCorpus` | `github("Sobeston/zig.guide")`, `github("C-BJ/awesome-zig")`, `github("raylib-zig/raylib-zig")`, `github("zigimg/zigimg")` | `crabcc.markdown` | — | `catalog.jsonl`, `catalog.sqlite`, `nix.derivation` |
    \\| `zigbeeFirmware` | `raw.github("Koenkk/zigbee-OTA", "index.json")` | — | `pinned` (commit `<commit>`) | — |
    \\
    \\## Streams
    \\
    \\| Stream | Source | Type | Retention / FPS |
    \\|--------|--------|------|-----------------|
    \\| `ebpfEvents` | `agentGuardd.ringbuf` | `Event.Ebpf` | retention `24h` |
    \\| `screenrec` | `agentpipe.screenrec` | `Media.Frame` | fps `10` |
    \\
    \\## Fibers
    \\
    \\| Fiber | Engine | Input | Output | Policy |
    \\|-------|--------|-------|--------|--------|
    \\| `mediaCompress` | `zigDaemon` | `stream.screenrec` | `artifacts.compressedMedia` | `strip_metadata = true`, `max_pixels = "4K"`, `formats = ["png", "webp"]` |
    \\
    \\## Surfaces
    \\
    \\| Surface | Mode | FPS | Input | Views |
    \\|---------|------|-----|-------|-------|
    \\| `operatorMap` | `raylib` | `60` | `stream.ebpfEvents`, `graph.workflow`, `graph.agentfield` | `network-flows`, `workflow-dag`, `filesystem-diff`, `mesh-topology` |
    \\
    \\## Parallel groups
    \\
    \\| Group | Fibers | Strategy | Supervisor |
    \\|-------|--------|----------|------------|
    \\| `operator-runtime` | `mediaCompress`, `operatorMap` | `supervised-dag` | `otp` |
    \\
    \\## Capability grants
    \\
    \\No `mesh` or `capability` declarations in this runtime, so there are no declared
    \\principal grant-sets (0012 §5.1). The implied daemon-channel uses follow from the
    \\stream sources:
    \\
    \\| Principal / consumer | Used channel | Implied membrane |
    \\|----------------------|--------------|------------------|
    \\| `stream ebpfEvents` | `agentGuardd.ringbuf` | `ebpf` (agent-guardd) |
    \\| `stream screenrec` | `agentpipe.screenrec` | `media` capture |
    \\| `fiber mediaCompress` (`output = artifacts.compressedMedia`) | artifact capture | `filesystem` (fs-snapshotd) |
    \\
    \\> Membranes per [`docs/context/PROJECT_CONTEXT.md`](../../../../docs/context/PROJECT_CONTEXT.md)
    \\> and the daemon roster in [`docs/runtime/README.md`](../../../../docs/runtime/README.md).
    \\> eBPF policy manifests / OTel config / systemd units / surface launcher are
    \\> deferred targets (0012 §7).
++ "\n";

// The path vakedc lowers this fixture under; it is the `sourceFile`/`span.file`
// the provenance manifest records, and its BASENAME is what the generated
// header names (0012 sec 6.1).
const fixture_path = "vaked/examples/operator-field.vaked";

// Fixture-integrity guards. These goldens are hand-copied `\\` literals with
// nothing else tying them to the files they mirror, so pin each one's byte
// count (the emit_test.zig convention). CONVENTION FOR EVERY GOLDEN THIS PORT
// ADDS: embed the bytes, then assert `.len` against `wc -c` of the source file.
// A drifting fixture must fail loudly here, not silently weaken the parity
// claim.
fn assertFixtureIntegrity() !void {
    try testing.expectEqual(@as(usize, 1518), operator_field_src.len); // vaked/examples/operator-field.vaked
    try testing.expectEqual(@as(usize, 4578), golden_flake_nix.len); // vaked/examples/lowering/flake.nix
    try testing.expectEqual(@as(usize, 2703), golden_runtime_md.len); // vaked/examples/lowering/gen/RUNTIME.md
}

test "lower: nix.spine reproduces the frozen flake.nix golden byte-for-byte" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    try assertFixtureIntegrity();
    const result = try lowerSource(a, operator_field_src, fixture_path);
    const got = fileContent(result, "flake.nix") orelse return error.TestUnexpectedResult;
    try std.testing.expectEqualStrings(golden_flake_nix, got);
}

test "lower: docs.runtime reproduces the frozen gen/RUNTIME.md golden byte-for-byte" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    try assertFixtureIntegrity();
    const result = try lowerSource(a, operator_field_src, fixture_path);
    const got = fileContent(result, "gen/RUNTIME.md") orelse return error.TestUnexpectedResult;
    try std.testing.expectEqualStrings(golden_runtime_md, got);
}

test "lower: files are sorted by path (the _write_tree contract)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const result = try lowerSource(a, operator_field_src, fixture_path);
    var i: usize = 1;
    while (i < result.files.len) : (i += 1) {
        try std.testing.expect(std.mem.order(u8, result.files[i - 1].path, result.files[i].path) == .lt);
    }
}

// --------------------------------------------------------------------------
// enrich_graph: the fiber `policy { ... }` sub-block the minimal resolver drops
// must be recovered, or the RUNTIME.md Policy column silently renders as an
// em-dash (and the fiber's inputsHash changes). The golden above already pins
// this end-to-end; this test isolates the mechanism.
// --------------------------------------------------------------------------

test "lower: enrichGraph attaches a fiber's policy config block" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const items = try parseItems(a, operator_field_src);
    var res = try resolve.buildGraph(a, items, fixture_path);

    // Before enrichment the resolver has dropped `policy { ... }` entirely.
    const fiber_id = "operator-field.vaked#operator-field/mediaCompress";
    const before = res.graph.getNode(fiber_id) orelse return error.TestUnexpectedResult;
    try std.testing.expect(propOf(before.props, "policy") == null);

    try lower.enrichGraph(a, &res.graph, items);

    const after = res.graph.getNode(fiber_id) orelse return error.TestUnexpectedResult;
    const policy = propOf(after.props, "policy") orelse return error.TestUnexpectedResult;
    // It lands as a record-carrying app value: {"ref":"policy","record":[...]}
    try std.testing.expect(propOf(policy, "record") != null);

    // Idempotent: a second pass must not duplicate or replace the prop.
    const n_before = countEntries(after.props);
    try lower.enrichGraph(a, &res.graph, items);
    const again = res.graph.getNode(fiber_id) orelse return error.TestUnexpectedResult;
    try std.testing.expectEqual(n_before, countEntries(again.props));
}

fn propOf(v: lib.json.Value, key: []const u8) ?lib.json.Value {
    switch (v) {
        .object => |obj| {
            for (obj) |e| {
                if (std.mem.eql(u8, e.key, key)) return e.value;
            }
            return null;
        },
        else => return null,
    }
}

fn countEntries(v: lib.json.Value) usize {
    return switch (v) {
        .object => |obj| obj.len,
        else => 0,
    };
}

// --------------------------------------------------------------------------
// inputsHash / canonical projection (0012 sec 2.1, sec 6.2): a real sha256 over
// the canonical projection JSON -- sorted keys, compact separators, no
// trailing newline. Pinned against Python:
//   >>> import hashlib, json
//   >>> h = lambda o: "sha256-" + hashlib.sha256(json.dumps(
//   ...     o, separators=(",",":"), ensure_ascii=False, sort_keys=True
//   ... ).encode()).hexdigest()
// --------------------------------------------------------------------------

test "lower: inputsHash is a real sha256 over the canonical projection" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    // _engine_projection("zigDaemon") == {"engine":"zigDaemon","package":"packages.zigDaemon"}
    const obj = try a.alloc(lib.json.Value.Entry, 2);
    obj[0] = .{ .key = "engine", .value = .{ .string = "zigDaemon" } };
    obj[1] = .{ .key = "package", .value = .{ .string = "packages.zigDaemon" } };
    const proj = lib.json.Value{ .object = obj };

    const canonical = try lower.canonicalProjectionJson(a, proj);
    try std.testing.expectEqualStrings(
        "{\"engine\":\"zigDaemon\",\"package\":\"packages.zigDaemon\"}",
        canonical,
    );
    try std.testing.expectEqualStrings("sha256-ea3ddd381b6c461339734b874346552a11db75b660d34c1678f09e9b1ad9005b", try lower.inputsHash(a, proj));
}

test "lower: canonicalValue sorts object keys recursively, preserves array order" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    // {"b":{"z":1,"a":[3,1,2]},"a":true} -> keys sorted, the array untouched.
    const inner = try a.alloc(lib.json.Value.Entry, 2);
    const arr = try a.alloc(lib.json.Value, 3);
    arr[0] = .{ .int = 3 };
    arr[1] = .{ .int = 1 };
    arr[2] = .{ .int = 2 };
    inner[0] = .{ .key = "z", .value = .{ .int = 1 } };
    inner[1] = .{ .key = "a", .value = .{ .array = arr } };
    const outer = try a.alloc(lib.json.Value.Entry, 2);
    outer[0] = .{ .key = "b", .value = .{ .object = inner } };
    outer[1] = .{ .key = "a", .value = .{ .bool = true } };

    try std.testing.expectEqualStrings(
        "{\"a\":true,\"b\":{\"a\":[3,1,2],\"z\":1}}",
        try lower.canonicalProjectionJson(a, .{ .object = outer }),
    );
}

// --------------------------------------------------------------------------
// provenance_json_text: 2-space indent, `span` objects rendered INLINE, one
// trailing newline (the sec 6.2 fixture layout convention).
// --------------------------------------------------------------------------

test "lower: provenanceJsonText inlines span objects at a 2-space indent" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const entries = [_]lower.ProvEntry{.{
        .artifact = "flake.nix",
        .region = "nixosModules.operator-field",
        .source_file = fixture_path,
        .decl = "runtime operator-field",
        .span = .{ .file = fixture_path, .byte_start = 27, .byte_end = 1517, .line = 3, .col = 1 },
        .emitter = "nix.spine",
        .inputs_projection = .{ .object = &.{} },
    }};
    const doc = try lower.buildProvenance(a, fixture_path, &entries);
    const text = try lower.provenanceJsonText(a, doc);

    // sha256 of the canonical projection of `{}` -- json.dumps({}) == "{}".
    const expected =
        \\{
        \\  "version": 1,
        \\  "source": "vaked/examples/operator-field.vaked",
        \\  "artifacts": {
        \\    "flake.nix": [
        \\      {
        \\        "region": "nixosModules.operator-field",
        \\        "sourceFile": "vaked/examples/operator-field.vaked",
        \\        "decl": "runtime operator-field",
        \\        "span": { "file": "vaked/examples/operator-field.vaked", "byteStart": 27, "byteEnd": 1517, "line": 3, "col": 1 },
        \\        "emitter": "nix.spine",
        \\        "inputsHash": "sha256-44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"
        \\      }
        \\    ]
        \\  }
        \\}
        \\
    ;
    try std.testing.expectEqualStrings(expected, text);
}

// --------------------------------------------------------------------------
// _nix_str / _nix_attr_key — the #7 splice class. These are the injection
// guard: a host-controlled name must never be able to break out of a Nix
// string literal or splice into a NESTED attrpath. Python neutralizes the
// three active sequences with CHAINED replaces (backslash FIRST, then `"`,
// then `${`); lower.zig does it in one pass, so the equivalence of the two is
// worth pinning explicitly -- the fixtures never exercise any of it.
//
// Expectations generated from the reference:
//   >>> lower._nix_str(s)
// --------------------------------------------------------------------------

test "lower: nixStr neutralizes backslash, quote and antiquotation" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const cases = [_]struct { in: []const u8, want: []const u8 }{
        .{ .in = "plain", .want = "\"plain\"" },
        .{ .in = "a\\b", .want = "\"a\\\\b\"" },
        .{ .in = "q\"r", .want = "\"q\\\"r\"" },
        .{ .in = "x${y}", .want = "\"x\\${y}\"" },
        // backslash escaped FIRST, so the `${` guard's own backslash survives
        .{ .in = "back\\${z}", .want = "\"back\\\\\\${z}\"" },
        // a bare `$` is only active when followed by `{`
        .{ .in = "$notbrace", .want = "\"$notbrace\"" },
        .{ .in = "trail$", .want = "\"trail$\"" },
    };
    for (cases) |c| {
        try std.testing.expectEqualStrings(c.want, try lower.nixStr(a, c.in));
    }
}

test "lower: nixAttrKey keeps a dotted ref as ONE quoted attribute" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    // bare identifiers pass through verbatim ('-' and '\'' are legal in the tail)
    try std.testing.expectEqualStrings("zigDaemon", try lower.nixAttrKey(a, "zigDaemon"));
    try std.testing.expectEqualStrings("operator-field", try lower.nixAttrKey(a, "operator-field"));
    try std.testing.expectEqualStrings("_x'y-2", try lower.nixAttrKey(a, "_x'y-2"));
    // a dotted ref would otherwise splice into `pkgs = { umami = ...; }` -- the
    // #7 worked-example bug. It must stay exactly one attribute.
    try std.testing.expectEqualStrings("\"pkgs.umami\"", try lower.nixAttrKey(a, "pkgs.umami"));
    // leading digit is not a bare ident
    try std.testing.expectEqualStrings("\"9lives\"", try lower.nixAttrKey(a, "9lives"));
    try std.testing.expectEqualStrings("\"\"", try lower.nixAttrKey(a, ""));
}

// --------------------------------------------------------------------------
// _coerce_number — the number-rendering trap. Props store number literals as
// STRINGS ({"lit":"number","value":"2.0"}); Python coerces to int/float and
// renders with str(), so "2.0" -> 2.0 -> "2.0" and "007" -> 7 -> "7".
//
// This is reachable from docs.runtime TODAY: `fiberPolicy` is an OPEN schema,
// so an undeclared policy field of any literal type reaches renderPolicyValue.
// The lower-diff harness is STRUCTURALLY BLIND to it -- no fixture carries a
// float or a leading zero, so it is green whether this helper is right or
// wrong. THIS TABLE IS THE ONLY GATE.
//
// Every expectation below was DERIVED by running the reference on dev-cx53,
// never hand-written:
//   python3 -c 'from vakedc.lower import _coerce_number; print(str(_coerce_number(s)))'
// Regenerate the same way when extending it. All inputs are grammatical per
//   number = ["-"] digit {digit} ["." digit {digit}]
// (no "+", no "_", no exponent in SOURCE) except the two ValueError probes.
// --------------------------------------------------------------------------

test "lower: coerceNumberStr matches Python's _coerce_number + str()" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const cases = [_]struct { in: []const u8, want: []const u8 }{
        .{ .in = "2.0", .want = "2.0" },
        .{ .in = "-0.0", .want = "-0.0" },
        .{ .in = "0.0", .want = "0.0" },
        .{ .in = "007", .want = "7" },
        .{ .in = "-007", .want = "-7" },
        .{ .in = "000", .want = "0" },
        .{ .in = "-000", .want = "0" },
        .{ .in = "0", .want = "0" },
        .{ .in = "7", .want = "7" },
        .{ .in = "-7", .want = "-7" },
        .{ .in = "0.00001", .want = "1e-05" },
        .{ .in = "0.0001", .want = "0.0001" },
        .{ .in = "1000000000000000.0", .want = "1000000000000000.0" },
        .{ .in = "10000000000000000.0", .want = "1e+16" },
        .{ .in = "1.50", .want = "1.5" },
        .{ .in = "1.5", .want = "1.5" },
        .{ .in = "123.456", .want = "123.456" },
        .{ .in = "-2.5", .want = "-2.5" },
        .{ .in = "10", .want = "10" },
        .{ .in = "99999999999999999999", .want = "99999999999999999999" },
        .{ .in = "-99999999999999999999", .want = "-99999999999999999999" },
        .{ .in = "3.14159", .want = "3.14159" },
        .{ .in = "0.1", .want = "0.1" },
        .{ .in = "100.0", .want = "100.0" },
        .{ .in = "-1.0", .want = "-1.0" },
        .{ .in = "12345678901234567890.0", .want = "1.2345678901234567e+19" },
        .{ .in = "abc", .want = "abc" },
        .{ .in = "", .want = "" },

        // --- runtime plane: trust.score (Float, lower.py L1698) and
        // quorum.min (Int, L1714). This is the family where the original v0.5
        // number bugs lived, and where the coerceNumberStr defect would have
        // propagated. The differential is BLIND here: no fixture carries a
        // float other than 0.9/0.7, so these are the gate. Python-derived on
        // dev-cx53 via vakedc.lower._coerce_number, same as above.
        .{ .in = "0.9", .want = "0.9" }, // runtime-with-trust.vaked, live
        .{ .in = "0.7", .want = "0.7" }, // runtime-with-trust.vaked, live
        .{ .in = "1.0", .want = "1.0" },
        .{ .in = "0.0", .want = "0.0" },
        .{ .in = "0.5", .want = "0.5" },
        .{ .in = "0.1", .want = "0.1" },
        // the classic binary-float artifact must survive VERBATIM
        .{ .in = "0.30000000000000004", .want = "0.30000000000000004" },
        // shortest-round-trip truncates a 30-digit literal to 16 digits
        .{ .in = "0.333333333333333314829616256247", .want = "0.3333333333333333" },
        // rounds up to exactly 1.0 -> forced ".0" (would be bare "1" under {d})
        .{ .in = "0.99999999999999999", .want = "1.0" },
        // 17 significant digits are required to round-trip this one
        .{ .in = "1.0000000000000002", .want = "1.0000000000000002" },
        // quorum.min (Int)
        .{ .in = "2", .want = "2" },
        .{ .in = "1", .want = "1" },
        .{ .in = "0", .want = "0" },
        .{ .in = "10", .want = "10" },
        .{ .in = "3", .want = "3" },
    };
    for (cases) |c| {
        const got = try lower.coerceNumberStr(a, c.in);
        std.testing.expectEqualStrings(c.want, got) catch |e| {
            std.debug.print("coerceNumberStr(\"{s}\"): want \"{s}\", got \"{s}\"\n", .{ c.in, c.want, got });
            return e;
        };
    }
}

// --------------------------------------------------------------------------
// Byte-exact embedded copy of vaked/examples/lowering/gen/zig/mediaCompress.json
// (476 bytes) -- the `zig.daemoncfg` golden (0012 sec 5.2).
//
// test_lowering_fixtures.py independently pins this file's shape: `_generated`
// is the FIRST key, the top-level key order is exactly the sec 5.2 canonical
// order, and no optional is ever null. Note `"fps": 10` -- a JSON NUMBER. Props
// store number literals as STRINGS, so this is the exact spot the v0.5 trust
// emitter got wrong; it round-trips through coerceNumberStr.
// --------------------------------------------------------------------------

const golden_mediacompress_json =
    \\{
    \\  "_generated": "generated by Vaked from operator-field.vaked:fiber mediaCompress — do not edit",
    \\  "engine": "zigDaemon",
    \\  "engine_package": "packages.zigDaemon",
    \\  "input": {
    \\    "stream": "screenrec",
    \\    "source": "agentpipe.screenrec",
    \\    "type": "Media.Frame",
    \\    "fps": 10
    \\  },
    \\  "output": {
    \\    "target": "artifacts.compressedMedia"
    \\  },
    \\  "policy": {
    \\    "strip_metadata": true,
    \\    "max_pixels": "4K",
    \\    "formats": ["png", "webp"]
    \\  },
    \\  "observe": false
    \\}
++ "\n";

test "lower: zig.daemoncfg reproduces the frozen mediaCompress.json golden byte-for-byte" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    try testing.expectEqual(@as(usize, 476), golden_mediacompress_json.len);
    const result = try lowerSource(a, operator_field_src, fixture_path);
    const got = fileContent(result, "gen/zig/mediaCompress.json") orelse return error.TestUnexpectedResult;
    try std.testing.expectEqualStrings(golden_mediacompress_json, got);
}

// --------------------------------------------------------------------------
// Slice 3 goldens: byte-exact embedded copies of the remaining
// vaked/examples/lowering/ artifacts.
//   gen/catalog/zigCorpus.jsonl        (459 bytes) -- catalog.jsonl
//   gen/otp/operator_field_sup.erl     (1297 bytes) -- otp.supervision
//   gen/otp/vaked_fiber_worker.erl     (1087 bytes) -- otp.supervision
// test_lowering_fixtures.py independently pins the jsonl (line 1 is the
// _generated header object; every line is valid JSON).
// --------------------------------------------------------------------------

const golden_catalog_jsonl =
    \\{"_generated":"generated by Vaked from operator-field.vaked:index zigCorpus — do not edit"}
    \\{"id":"zig.guide#0001","source":"github:Sobeston/zig.guide","path":"chapter-1/hello-world.md","chunk":0,"text":"# Hello World\n\nCreate a file `hello.zig` and run it with `zig run hello.zig`."}
    \\{"id":"zigimg#0001","source":"github:zigimg/zigimg","path":"README.md","chunk":0,"text":"# zigimg\n\nZig library for reading and writing images in a variety of formats."}
++ "\n";

const golden_otp_sup_erl =
    \\%% generated by Vaked from operator-field.vaked:runtime operator-field — do not edit
    \\%%
    \\%% otp.supervision (0012 3.4; Track C #19). v0 strategy: one_for_one -
    \\%% downstream consistency is RFC 0004's job (stale_dependency pausing);
    \\%% eager per-chain rest_for_one is the edge-aware follow-up (design
    \\%% 2026-06-12-otp-supervision-lowering-design.md).
    \\-module(operator_field_sup).
    \\-behaviour(supervisor).
    \\
    \\-export([start_link/0, init/1]).
    \\
    \\start_link() ->
    \\    supervisor:start_link({local, ?MODULE}, ?MODULE, []).
    \\
    \\init([]) ->
    \\    SupFlags = #{strategy => one_for_one, intensity => 3, period => 10},
    \\    Children = [
    \\        #{id => 'mediaCompress',
    \\          start => {vaked_fiber_worker, start_link,
    \\                    [#{name => 'mediaCompress', kind => fiber,
    \\                       config => "gen/zig/mediaCompress.json"}]},
    \\          restart => permanent, shutdown => 5000,
    \\          type => worker,
    \\          modules => [vaked_fiber_worker]},
    \\        #{id => 'operatorMap',
    \\          start => {vaked_fiber_worker, start_link,
    \\                    [#{name => 'operatorMap', kind => surface,
    \\                       config => none}]},
    \\          restart => permanent, shutdown => 5000,
    \\          type => worker,
    \\          modules => [vaked_fiber_worker]}
    \\    ],
    \\    {ok, {SupFlags, Children}}.
++ "\n";

const golden_otp_worker_erl =
    \\%% generated by Vaked from operator-field.vaked:runtime operator-field — do not edit
    \\%%
    \\%% Generic placeholder worker: heartbeats until the member's Zig
    \\%% daemon port replaces it. Deliberately does NOT write eventd (the
    \\%% canonical-hash byte contract stays with the Python oracle; the
    \\%% daemon owns the single writer, RFC 0004).
    \\-module(vaked_fiber_worker).
    \\-behaviour(gen_server).
    \\
    \\-export([start_link/1]).
    \\-export([init/1, handle_call/3, handle_cast/2, handle_info/2]).
    \\
    \\-define(TICK_MS, 5000).
    \\
    \\start_link(#{name := Name} = Args) ->
    \\    gen_server:start_link({local, Name}, ?MODULE, Args, []).
    \\
    \\init(#{name := Name, kind := Kind} = Args) ->
    \\    logger:info("vaked ~p ~p up (placeholder; daemon port pending)",
    \\                [Kind, Name]),
    \\    erlang:send_after(?TICK_MS, self(), tick),
    \\    {ok, Args}.
    \\
    \\handle_call(_Req, _From, State) ->
    \\    {reply, ok, State}.
    \\
    \\handle_cast(_Msg, State) ->
    \\    {noreply, State}.
    \\
    \\handle_info(tick, #{name := Name} = State) ->
    \\    logger:debug("vaked heartbeat ~p", [Name]),
    \\    erlang:send_after(?TICK_MS, self(), tick),
    \\    {noreply, State}.
++ "\n";

test "lower: catalog.jsonl reproduces the frozen zigCorpus.jsonl golden byte-for-byte" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    try testing.expectEqual(@as(usize, 459), golden_catalog_jsonl.len);
    const result = try lowerSource(a, operator_field_src, fixture_path);
    const got = fileContent(result, "gen/catalog/zigCorpus.jsonl") orelse return error.TestUnexpectedResult;
    try std.testing.expectEqualStrings(golden_catalog_jsonl, got);
}

test "lower: otp.supervision reproduces both frozen .erl goldens byte-for-byte" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    try testing.expectEqual(@as(usize, 1297), golden_otp_sup_erl.len);
    try testing.expectEqual(@as(usize, 1087), golden_otp_worker_erl.len);
    const result = try lowerSource(a, operator_field_src, fixture_path);

    const sup = fileContent(result, "gen/otp/operator_field_sup.erl") orelse return error.TestUnexpectedResult;
    try std.testing.expectEqualStrings(golden_otp_sup_erl, sup);

    const worker = fileContent(result, "gen/otp/vaked_fiber_worker.erl") orelse return error.TestUnexpectedResult;
    try std.testing.expectEqualStrings(golden_otp_worker_erl, worker);
}

// _otp_slug: "operator-field" -> "operator_field" (the module name MUST match
// the filename). Expectations derived from the reference on dev-cx53:
//   python3 -c 'from vakedc.lower import _otp_slug; print(_otp_slug(s))'
test "lower: otpSlug produces a legal Erlang module atom prefix" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const cases = [_]struct { in: []const u8, want: []const u8 }{
        .{ .in = "operator-field", .want = "operator_field" },
        .{ .in = "OperatorField", .want = "operatorfield" },
        .{ .in = "9lives", .want = "v9lives" },
        .{ .in = "_leading", .want = "v_leading" },
        .{ .in = "", .want = "v" },
        .{ .in = "a.b-c", .want = "a_b_c" },
    };
    for (cases) |c| {
        try std.testing.expectEqualStrings(c.want, try lower.otpSlug(a, c.in));
    }
}

// operator-field is the richest golden: it selects nix.spine, docs.runtime,
// zig.daemoncfg, catalog.jsonl AND otp.supervision, and its frozen tree under
// vaked/examples/lowering/ is what test_vakedc_lower.py pins vakedc against.
// This asserts the emitted SET, so a dropped or stray artifact names itself
// instead of surfacing as a byte diff.
test "lower: operator-field emits exactly the frozen fixture tree" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const result = try lowerSource(a, operator_field_src, fixture_path);
    // The full frozen fixture tree, minus provenance.json (built by the driver).
    const want = [_][]const u8{
        "flake.nix",
        "gen/RUNTIME.md",
        "gen/catalog/zigCorpus.jsonl",
        "gen/otp/operator_field_sup.erl",
        "gen/otp/vaked_fiber_worker.erl",
        "gen/zig/mediaCompress.json",
    };
    try std.testing.expectEqual(want.len, result.files.len);
    for (want, result.files) |w, f| try std.testing.expectEqualStrings(w, f.path);
}

// ==========================================================================
// Slice 4: the NixOS-deployment cohort (#1-#6).
//
// vaked/examples/lowering/ only freezes operator-field, which declares NO
// cohort decls -- so these goldens were DERIVED from LIVE vakedc on dev-cx53
// (`python3 -m vakedc lower <fixture> --out ...`), per the standing rule that
// the tracked .vaked/lower/** is span-drifted and must not be trusted (#385).
// Regenerate the same way.
//
// Coverage (the only two fixtures that exercise the cohort at all):
//   crabcc-umami  -> sops.secrets, host.resources, nixos.service, caddy.ingress
//   browser-pool  -> sops.secrets, oci.containers
// ==========================================================================

const crabcc_umami_src =
    \\# crabcc-umami — dogfood: the umami NixOS service as a Vaked capability graph.
    \\#
    \\# Reference implementation: nix-base/hosts/public-services-host/umami.nix
    \\#
    \\# This is the #1-#6 cohort dogfood, now expressed with the real constructs the
    \\# gaps motivated (was a pile of `# GAP:` stubs). It checks clean: every kind
    \\# exists (service/secret/hostResource/ingress), every value type resolves
    \\# (Bind via loopback(); secret.X.path / hostResource.X.dsn accessors), and the
    \\# closed-world resolver validates the in-runtime refs.
    \\#
    \\#   services.umami.enable                   → service umami
    \\#   createPostgresqlDatabase / DATABASE_URL → hostResource umamiDb (.dsn)
    \\#   APP_SECRET_FILE = sops.secrets.path     → secret umamiAppSecret (.path)
    \\#   HOSTNAME=127.0.0.1 PORT=3003            → bind = loopback(3003)
    \\#   DISABLE_TELEMETRY = true                → options { … }
    \\#   Caddy reverse_proxy                     → ingress umamiIngress
    \\
    \\runtime "crabcc-umami" {
    \\  systems = ["x86_64-linux"]
    \\
    \\  # sops-managed runtime secret (was GAP #3). Consumed via secret.X.path below;
    \\  # lowers to a sops.secrets."umami_app_secret" entry.
    \\  secret umamiAppSecret {
    \\    provider = "sops"
    \\    name = "umami_app_secret"
    \\    owner = "umami"
    \\  }
    \\
    \\  # shared host PostgreSQL (was GAP #2). Exposes hostResource.umamiDb.dsn and
    \\  # provisions the database/user on the box's services.postgresql.
    \\  hostResource umamiDb {
    \\    kind = "postgresql"
    \\    name = "umami"
    \\    create = true
    \\  }
    \\
    \\  # the umami systemd service (was GAP #1 + #4 + #5). nixpkgs-packaged, bound to
    \\  # loopback, with its secret + database wired through the option set.
    \\  service umami {
    \\    package = pkgs.umami
    \\    bind = loopback(3003)
    \\    # → HOSTNAME=127.0.0.1, PORT=3003
    \\    secrets = [umamiAppSecret]
    \\    database = umamiDb
    \\    options {
    \\      DISABLE_TELEMETRY = true
    \\      APP_SECRET_FILE = secret.umamiAppSecret.path
    \\      DATABASE_URL = hostResource.umamiDb.dsn
    \\    }
    \\  }
    \\
    \\  # Caddy HTTP reverse-proxy vhost (was GAP #6, a misused raylib surface).
    \\  ingress umamiIngress {
    \\    domain = "analytics.crabcc.app"
    \\    upstream = loopback(3003)
    \\    tls = "crabcc_sec"
    \\  }
    \\}
++ "\n";

const browser_pool_src =
    \\# browser-pool — dogfood: the public-services-host OCI browser pool as a Vaked graph.
    \\#
    \\# Reference implementation: nix-base/hosts/public-services-host/browser-pool.nix
    \\#
    \\# Exercises the `container` kind (#6) with Bind port mappings (#3, host:container)
    \\# and sops secret-file injection (#2, via secret.X.path). Lowers to
    \\# virtualisation.oci-containers.containers.<name>. Checks clean.
    \\
    \\runtime "browser-pool" {
    \\  systems = ["x86_64-linux"]
    \\
    \\  # sops-managed env files injected into the containers (was inline sops refs).
    \\  secret browserlessEnv {
    \\    provider = "sops"
    \\    name = "browserless_env"
    \\  }
    \\  secret brwsEnv {
    \\    provider = "sops"
    \\    name = "brws_env"
    \\  }
    \\
    \\  container browserless {
    \\    image = "ghcr.io/browserless/chromium:latest"
    \\    ports = [loopback(3030, 3000)]
    \\    # 127.0.0.1:3030:3000
    \\    environment { CONCURRENT = "4" }
    \\    environmentFiles = [secret.browserlessEnv.path]
    \\    memory = 2GB
    \\    healthCmd = "curl -f http://localhost:3000/pressure || exit 1"
    \\    extraOptions = ["--shm-size=1g"]
    \\  }
    \\
    \\  container lightpanda {
    \\    image = "lightpanda/browser:nightly"
    \\    ports = [loopback(9222, 9222)]
    \\    memory = 512MB
    \\  }
    \\
    \\  container brws {
    \\    image = "europe-west2-docker.pkg.dev/example/brws:latest"
    \\    network = "host"
    \\    volumes = ["/etc/browser-pool.json:/etc/browser-pool.json:ro"]
    \\    environmentFiles = [secret.brwsEnv.path]
    \\    memory = 256MB
    \\  }
    \\}
++ "\n";

const golden_sops_nix =
    \\# generated by Vaked from crabcc-umami.vaked:secret umamiAppSecret — do not edit
    \\#
    \\# sops-managed runtime secrets.
    \\# NixOS module fragment imported by nixosModules.<runtime> (0012 §4.3).
    \\{ config, ... }:
    \\{
    \\  sops.secrets."umami_app_secret" = {
    \\    owner = "umami";
    \\  };
    \\}
++ "\n";

const golden_host_resources_nix =
    \\# generated by Vaked from crabcc-umami.vaked:hostResource umamiDb — do not edit
    \\#
    \\# host-managed resources (shared services.postgresql).
    \\# NixOS module fragment imported by nixosModules.<runtime> (0012 §4.3).
    \\{ ... }:
    \\{
    \\  services.postgresql.ensureDatabases = [ "umami" ];
    \\  services.postgresql.ensureUsers = [
    \\    { name = "umami"; ensureDBOwnership = true; }
    \\  ];
    \\}
++ "\n";

const golden_services_nix =
    \\# generated by Vaked from crabcc-umami.vaked:service umami — do not edit
    \\#
    \\# nixpkgs-packaged systemd services.
    \\# NixOS module fragment imported by nixosModules.<runtime> (0012 §4.3).
    \\{ config, pkgs, ... }:
    \\{
    \\  services.umami = {
    \\    enable = true;
    \\    package = pkgs.umami;
    \\    createPostgresqlDatabase = true;
    \\    settings = {
    \\      HOSTNAME = "127.0.0.1";
    \\      PORT = 3003;
    \\      DISABLE_TELEMETRY = true;
    \\      APP_SECRET_FILE = config.sops.secrets."umami_app_secret".path;
    \\      DATABASE_URL = "postgresql:///umami?host=/run/postgresql";
    \\    };
    \\  };
    \\}
++ "\n";

const golden_caddy_ingress_nix =
    \\# generated by Vaked from crabcc-umami.vaked:ingress umamiIngress — do not edit
    \\#
    \\# Caddy HTTP reverse-proxy virtual hosts.
    \\# NixOS module fragment imported by nixosModules.<runtime> (0012 §4.3).
    \\{ ... }:
    \\{
    \\  services.caddy.virtualHosts."analytics.crabcc.app".extraConfig = ''
    \\    import crabcc_sec
    \\    reverse_proxy 127.0.0.1:3003
    \\  '';
    \\}
++ "\n";

const golden_oci_containers_nix =
    \\# generated by Vaked from browser-pool.vaked:container browserless — do not edit
    \\#
    \\# OCI/Docker containers (memory/network/healthCmd → extraOptions).
    \\# NixOS module fragment imported by nixosModules.<runtime> (0012 §4.3).
    \\{ config, ... }:
    \\{
    \\  virtualisation.oci-containers.containers = {
    \\    browserless = {
    \\      image = "ghcr.io/browserless/chromium:latest";
    \\      ports = [ "127.0.0.1:3030:3000" ];
    \\      environment = {
    \\        CONCURRENT = "4";
    \\      };
    \\      environmentFiles = [ config.sops.secrets."browserless_env".path ];
    \\      extraOptions = [ "--memory=2g" "--health-cmd=curl -f http://localhost:3000/pressure || exit 1" "--shm-size=1g" ];
    \\    };
    \\    lightpanda = {
    \\      image = "lightpanda/browser:nightly";
    \\      ports = [ "127.0.0.1:9222:9222" ];
    \\      extraOptions = [ "--memory=512m" ];
    \\    };
    \\    brws = {
    \\      image = "europe-west2-docker.pkg.dev/example/brws:latest";
    \\      environmentFiles = [ config.sops.secrets."brws_env".path ];
    \\      volumes = [ "/etc/browser-pool.json:/etc/browser-pool.json:ro" ];
    \\      extraOptions = [ "--memory=256m" "--network=host" ];
    \\    };
    \\  };
    \\}
++ "\n";

const crabcc_umami_path = "vaked/examples/crabcc-umami.vaked";
const browser_pool_path = "vaked/examples/containers/browser-pool.vaked";

test "lower: NixOS cohort reproduces live vakedc for crabcc-umami byte-for-byte" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    try testing.expectEqual(@as(usize, 2137), crabcc_umami_src.len);
    try testing.expectEqual(@as(usize, 275), golden_sops_nix.len);
    try testing.expectEqual(@as(usize, 371), golden_host_resources_nix.len);
    try testing.expectEqual(@as(usize, 561), golden_services_nix.len);
    try testing.expectEqual(@as(usize, 343), golden_caddy_ingress_nix.len);

    const result = try lowerSource(a, crabcc_umami_src, crabcc_umami_path);
    try expectFile(result, "gen/nixos/sops.nix", golden_sops_nix);
    try expectFile(result, "gen/nixos/host-resources.nix", golden_host_resources_nix);
    try expectFile(result, "gen/nixos/services.nix", golden_services_nix);
    try expectFile(result, "gen/caddy/ingress.nix", golden_caddy_ingress_nix);
}

test "lower: oci.containers reproduces live vakedc for browser-pool byte-for-byte" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    try testing.expectEqual(@as(usize, 1390), browser_pool_src.len);
    try testing.expectEqual(@as(usize, 1106), golden_oci_containers_nix.len);

    const result = try lowerSource(a, browser_pool_src, browser_pool_path);
    // Exercises the whole container vocabulary: memory GB->g and MB->m,
    // --network, --health-cmd, author extraOptions verbatim and LAST, an OCI
    // 3-part loopback bind (127.0.0.1:3030:3000), volumes, and an
    // environmentFiles secret accessor rendered UNQUOTED
    // (config.sops.secrets."...".path).
    try expectFile(result, "gen/nixos/oci-containers.nix", golden_oci_containers_nix);
}

fn expectFile(result: lower.LowerResult, path: []const u8, want: []const u8) !void {
    const got = fileContent(result, path) orelse {
        std.debug.print("emitter produced no {s}\n", .{path});
        return error.TestUnexpectedResult;
    };
    std.testing.expectEqualStrings(want, got) catch |e| {
        std.debug.print("byte mismatch in {s}\n", .{path});
        return e;
    };
}

// The `create = false` hostResource filter (lower.py L1336) is a REPLICATED
// vakedc BUG: `_lit(...) is not False` compares a STRING ("false") against the
// bool False, so it is always true and `create = false` does NOT exclude the
// resource -- contradicting the emitter's own docstring. Verified against the
// reference on dev-cx53:
//   >>> _lit({"lit":"bool","value":"false"})  -> 'false'   (a str)
//   >>> 'false' is not False                  -> True
// Reproduced bug-compatibly by default and reported, NOT fixed.
test "lower: host.resources replicates vakedc's create=false filter bug" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const src =
        \\runtime app {
        \\  systems = ["x86_64-linux"]
        \\  hostResource db {
        \\    kind = "postgresql"
        \\    name = "appdb"
        \\    create = false
        \\  }
        \\}
        \\
    ;
    const result = try lowerSource(a, src, "t.vaked");
    const got = fileContent(result, "gen/nixos/host-resources.nix") orelse {
        std.debug.print("create=false wrongly EXCLUDED the resource -- the vakedc bug was 'fixed'; parity is broken\n", .{});
        return error.TestUnexpectedResult;
    };
    // Bug-compatible: it is still provisioned despite create = false.
    try std.testing.expect(std.mem.indexOf(u8, got, "ensureDatabases = [ \"appdb\" ]") != null);
}

// ==========================================================================
// Slice 5: the runtime plane (#18/#24/#27) + the v0.5 trio.
//
// Goldens DERIVED from LIVE vakedc on dev-cx53 (vaked/examples/lowering/
// freezes only operator-field, which declares none of these):
//   python3 -m vakedc lower <fixture> --out ...
//
// These pin two layout facts that are easy to get valid-but-wrong:
//  * gen/trust.json's trusts/quorums/probes are plain Python DICTS inside a
//    list, so `_emit_zig_value` has no _Ordered branch for them and falls
//    through to json.dumps -> each entry renders INLINE with DEFAULT
//    separators ({"a": 1}). A pretty multi-line tree would be wrong.
//  * gen/workflow/*.json's steps/edges ARE _Ordered inside a list, so they
//    render MULTI-LINE, indented one level deeper, joined by ", ".
// ==========================================================================

const runtime_with_trust_src =
    \\# v0.5 — runtime with trust/quorum/probe integration
    \\#
    \\# Full example showing trust, quorum, and probe declarations inside a
    \\# runtime alongside their consumer (mesh, stream, etc.).
    \\
    \\use "../engines/zig.vaked"
    \\
    \\runtime "v0p5-demo" {
    \\  systems = ["x86_64-linux"]
    \\
    \\  # ---- v0.5 declarations ------------------------------------------------
    \\
    \\  trust primaryScore {
    \\    score = 0.9
    \\    half_life = 12h
    \\  }
    \\
    \\  trust delegateScore {
    \\    score = 0.7
    \\    half_life = 24h
    \\    delegate = primaryScore
    \\    taint_as = false
    \\  }
    \\
    \\  quorum consensus {
    \\    min = 2
    \\    over = [nodeA, nodeB, nodeC]
    \\    timeout = 15s
    \\    on_failure = retry
    \\  }
    \\
    \\  quorum compactionGuard {
    \\    min = 1
    \\    over = [nodeA]
    \\    timeout = 5s
    \\    on_failure = abort
    \\  }
    \\
    \\  probe readinessProbe {
    \\    from = nodeA
    \\    to = nodeB
    \\    via = edgeMain
    \\  }
    \\
    \\  probe preUpgradeProbe {
    \\    from = nodeA
    \\    to = nodeC
    \\    via = edgeMain
    \\    with = capability.process
    \\    on_result = { status = "ok" }
    \\  }
    \\
    \\  # ---- Existing constructs for context ----------------------------------
    \\
    \\  index testCorpus {
    \\    source = github("example/example-repo")
    \\    emit = [catalog.jsonl]
    \\  }
    \\
    \\  mesh testMesh {
    \\    node nodeA {
    \\      role = "producer"
    \\      capabilities = [fs.repo_rw, process.spawn_sandboxed]
    \\    }
    \\
    \\    node nodeB {
    \\      role = "processor"
    \\      capabilities = [fs.repo_ro, process.spawn_sandboxed]
    \\    }
    \\
    \\    node nodeC {
    \\      role = "consumer"
    \\      capabilities = [process.spawn_sandboxed]
    \\    }
    \\
    \\    nodeA -> nodeB : "pipeline"
    \\    nodeB -> nodeC : "delivery"
    \\  }
    \\}
++ "\n";

const sdd_src =
    \\# sdd.vaked — Subagent-Driven Development as a Vaked capability graph.
    \\#
    \\# The companion `.claude/skills/subagent-driven-development` skill is the human/agent
    \\# entrypoint; this file is its FORMAL shape — the SDD mesh (roles + attenuated
    \\# capabilities) and the wave DAG (research → spec → implement → test → integrate),
    \\# expressed the same way agentfield-swe.vaked expresses the swe_af mesh + workflow.
    \\#
    \\#   mesh     — the subagent field: orchestrator DELEGATES attenuated authority (§4.4)
    \\#   workflow — the SDD waves as a checked DAG (0015); each node names its agent
    \\#   budget   — the run bound the supervision plane enforces
    \\
    \\use "./engines/zig.vaked"
    \\
    \\runtime "sdd-field" {
    \\  systems = ["x86_64-linux"]
    \\
    \\  # Ground the agents against the repo corpus (same index swe_af uses).
    \\  index repoCorpus {
    \\    source = [github("peterlodri-sec/vaked-base")]
    \\    normalize = crabcc.markdown
    \\    emit = [catalog.jsonl, catalog.sqlite]
    \\  }
    \\
    \\  # The subagent field. Mesh edges are capability DELEGATIONS: the orchestrator holds
    \\  # the strongest grants; every subagent receives an attenuated subset (POLA). Only the
    \\  # broker may write to GitHub; only the orchestrator may merge.
    \\  mesh field {
    \\    node orchestrator {
    \\      role = "control-plane"
    \\      capabilities = [fs.repo_rw, process.spawn, mcp.github_write, mem.admin]
    \\    }
    \\    node researcher {
    \\      role = "research"
    \\      # one instance per core/adjacent topic (fan-out)
    \\      capabilities = [fs.repo_ro, mem.recall]
    \\      # web access is via the deep-research skill (no `net` cap domain in the schema yet)
    \\    }
    \\    node specAuthor {
    \\      role = "spec"
    \\      capabilities = [fs.repo_rw, mem.recall]
    \\    }
    \\    node coherenceCritic {
    \\      role = "critic"
    \\      capabilities = [fs.repo_ro, mem.recall]
    \\    }
    \\    node coder {
    \\      role = "implement"
    \\      # one instance per component, isolated worktree (fan-out)
    \\      capabilities = [fs.repo_rw, process.spawn_sandboxed, mem.recall]
    \\    }
    \\    node testAuthor {
    \\      role = "test"
    \\      # spec-only; never sees the coder's code (fan-out)
    \\      capabilities = [fs.repo_ro, process.spawn_sandboxed]
    \\    }
    \\    node reviewer {
    \\      role = "review"
    \\      capabilities = [fs.repo_ro, mem.recall]
    \\    }
    \\    node broker {
    \\      role = "mcp-broker"
    \\      capabilities = [mcp.github_write]
    \\    }
    \\    orchestrator -> researcher
    \\    orchestrator -> specAuthor
    \\    orchestrator -> coherenceCritic
    \\    orchestrator -> coder
    \\    orchestrator -> testAuthor
    \\    orchestrator -> reviewer
    \\    orchestrator -> broker
    \\  }
    \\
    \\  budget sddRun {
    \\    tokens = 8000000
    \\    wallClock = 8h
    \\    toolCalls = 2000
    \\    approvals = "destructive"
    \\    # human approves the destructive integration step; never self-merge
    \\    fuel = 20000000000
    \\  }
    \\
    \\  # The SDD waves. Workflow edges are step ORDERING (a checked DAG); research /
    \\  # implement / test are fan-out stages (N agents of that role run in parallel within
    \\  # the stage), each gated before the next stage starts.
    \\  workflow sdd_waves {
    \\    on = "operator.invoke:subagent-driven-development"
    \\    budget = budget.sddRun
    \\    maxDepth = 6
    \\
    \\    node frame {
    \\      agent = field.orchestrator
    \\      output = artifacts.waveDag
    \\      # P0: decompose + acceptance gates
    \\    }
    \\    node research {
    \\      agent = field.researcher
    \\      # fan-out: one per core/adjacent topic
    \\      input = artifacts.waveDag
    \\      output = artifacts.dossier
    \\      # P1: cited, adversarially verified
    \\    }
    \\    node spec {
    \\      agent = field.specAuthor
    \\      input = artifacts.dossier
    \\      output = artifacts.spec
    \\      # P2: RFC/EBNF/tables (gated by the critic)
    \\    }
    \\    node implement {
    \\      agent = field.coder
    \\      # fan-out: one per component, own worktree
    \\      input = artifacts.spec
    \\      output = artifacts.components
    \\      # P3: builds on dev-cx53/GHA, never local
    \\      retries = 2
    \\    }
    \\    node test {
    \\      agent = field.testAuthor
    \\      # fan-out: spec-only, independent of impl
    \\      input = artifacts.spec
    \\      output = artifacts.verdict
    \\      # P4: per-component + integration, ci-gate green
    \\    }
    \\    node integrate {
    \\      agent = field.broker
    \\      input = artifacts.verdict
    \\      # P5: stacked PRs, ready-for-review
    \\    }
    \\
    \\    frame -> research -> spec -> implement -> test -> integrate
    \\  }
    \\}
++ "\n";

const golden_trust_json =
    \\{
    \\  "_generated": "generated by Vaked from runtime-with-trust.vaked:runtime v0p5-demo — do not edit",
    \\  "trusts": [{"name": "primaryScore", "score": 0.9, "half_life": "12h"}, {"name": "delegateScore", "score": 0.7, "half_life": "24h", "delegate": "primaryScore", "taint_as": false}],
    \\  "quorums": [{"name": "consensus", "min": 2, "over": ["nodeA", "nodeB", "nodeC"], "timeout": "15s", "on_failure": "retry"}, {"name": "compactionGuard", "min": 1, "over": ["nodeA"], "timeout": "5s", "on_failure": "abort"}],
    \\  "probes": [{"name": "readinessProbe", "from": "nodeA", "to": "nodeB", "via": "edgeMain"}, {"name": "preUpgradeProbe", "from": "nodeA", "to": "nodeC", "via": "edgeMain", "with": "capability.process"}]
    \\}
++ "\n";

const golden_eventd_json =
    \\{
    \\  "_generated": "generated by Vaked from sdd.vaked:runtime sdd-field — do not edit",
    \\  "log": "var/lib/sdd-field/eventd/log.jsonl",
    \\  "format": "jsonl-hashchain-v1",
    \\  "verify_on_boot": true,
    \\  "writer": "agent-supervisord"
    \\}
++ "\n";

const golden_sdd_waves_json =
    \\{
    \\  "_generated": "generated by Vaked from sdd.vaked:workflow sdd_waves — do not edit",
    \\  "on": "operator.invoke:subagent-driven-development",
    \\  "budget": "budget.sddRun",
    \\  "maxDepth": 6,
    \\  "steps": [{
    \\      "name": "frame",
    \\      "agent": "field.orchestrator",
    \\      "output": "artifacts.waveDag"
    \\    }, {
    \\      "name": "research",
    \\      "agent": "field.researcher",
    \\      "input": "artifacts.waveDag",
    \\      "output": "artifacts.dossier"
    \\    }, {
    \\      "name": "spec",
    \\      "agent": "field.specAuthor",
    \\      "input": "artifacts.dossier",
    \\      "output": "artifacts.spec"
    \\    }, {
    \\      "name": "implement",
    \\      "agent": "field.coder",
    \\      "input": "artifacts.spec",
    \\      "output": "artifacts.components",
    \\      "retries": 2
    \\    }, {
    \\      "name": "test",
    \\      "agent": "field.testAuthor",
    \\      "input": "artifacts.spec",
    \\      "output": "artifacts.verdict"
    \\    }, {
    \\      "name": "integrate",
    \\      "agent": "field.broker",
    \\      "input": "artifacts.verdict"
    \\    }],
    \\  "edges": [{
    \\      "from": "frame",
    \\      "to": "research"
    \\    }, {
    \\      "from": "research",
    \\      "to": "spec"
    \\    }, {
    \\      "from": "spec",
    \\      "to": "implement"
    \\    }, {
    \\      "from": "implement",
    \\      "to": "test"
    \\    }, {
    \\      "from": "test",
    \\      "to": "integrate"
    \\    }],
    \\  "depth": 6,
    \\  "log": "var/lib/sdd-field/eventd/log.jsonl"
    \\}
++ "\n";

test "lower: trust.config reproduces live vakedc byte-for-byte (floats included)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    try testing.expectEqual(@as(usize, 1534), runtime_with_trust_src.len);
    try testing.expectEqual(@as(usize, 714), golden_trust_json.len);

    const result = try lowerSource(a, runtime_with_trust_src, "vaked/examples/v0.5/runtime-with-trust.vaked");
    // score = 0.9 / 0.7 are the only floats ANY fixture carries -- the
    // differential is otherwise blind to the float path.
    try expectFile(result, "gen/trust.json", golden_trust_json);
}

test "lower: workflow.spec + eventd.config reproduce live vakedc byte-for-byte" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    try testing.expectEqual(@as(usize, 4241), sdd_src.len);
    try testing.expectEqual(@as(usize, 1330), golden_sdd_waves_json.len);
    try testing.expectEqual(@as(usize, 230), golden_eventd_json.len);

    const result = try lowerSource(a, sdd_src, "vaked/examples/sdd.vaked");
    try expectFile(result, "gen/workflow/sdd_waves.json", golden_sdd_waves_json);
    try expectFile(result, "gen/eventd.json", golden_eventd_json);
}

// _workflow_depth: the critical path in steps. sdd_waves is a 6-step chain
// (frame -> research -> spec -> implement -> test -> integrate), and its
// maxDepth = 6 -- so depth must be 6. Pinned separately from the golden so a
// depth regression names itself instead of surfacing as a byte diff.
test "lower: workflow.spec depth is the critical path in steps" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const result = try lowerSource(a, sdd_src, "vaked/examples/sdd.vaked");
    const got = fileContent(result, "gen/workflow/sdd_waves.json") orelse return error.TestUnexpectedResult;
    try std.testing.expect(std.mem.indexOf(u8, got, "\"depth\": 6") != null);
}

// ==========================================================================
// _host_cidr — the security-relevant validator. A wrong ACCEPT emits an allow
// rule vakedc would not (traffic permitted that should be denied); a wrong
// REJECT drops a rule vakedc emits. Neither is visible to the differential:
// every fixture uses 127.0.0.1.
//
// Python delegates to the `ipaddress` module, which vakedz cannot (stdlib
// only, and Zig 0.16's std has no ipaddress equivalent), so the rules are
// reimplemented. EVERY expectation below was DERIVED by running
// vakedc.lower._host_cidr on dev-cx53. Regenerate the same way.
//
// The subtle ones this pins:
//   010.0.0.1  -> null  (CPython >=3.9.5 rejects ambiguous leading zeros)
//   127.0.0.1/8 -> verbatim (strict=False permits host bits)
//   1.2.3.4/032 -> verbatim (leading zeros in a PREFIX are fine)
//   1.2.3.4/+32 -> null  (int-like, but _prefix_from_prefix_string is
//                         digits-only, so '+' is rejected)
//   1.2.3.4/1.2.3.4 -> netmask/hostmask STRING form is accepted by ip_network
// ==========================================================================

test "lower: hostCidr matches Python's ipaddress-backed _host_cidr" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const cases = [_]struct { in: []const u8, want: ?[]const u8 }{
        .{ .in = "127.0.0.1", .want = "127.0.0.1/32" },
        .{ .in = "10.0.0.1", .want = "10.0.0.1/32" },
        .{ .in = "0.0.0.0", .want = "0.0.0.0/32" },
        .{ .in = "255.255.255.255", .want = "255.255.255.255/32" },
        .{ .in = "::1", .want = "::1/128" },
        .{ .in = "2001:db8::1", .want = "2001:db8::1/128" },
        .{ .in = "::", .want = "::/128" },
        .{ .in = "::ffff:1.2.3.4", .want = "::ffff:1.2.3.4/128" },
        .{ .in = "fe80::1", .want = "fe80::1/128" },
        .{ .in = "2001:0db8:0000:0000:0000:0000:0000:0001", .want = "2001:0db8:0000:0000:0000:0000:0000:0001/128" },
        .{ .in = "10.0.0.0/8", .want = "10.0.0.0/8" },
        .{ .in = "1.2.3.4/32", .want = "1.2.3.4/32" },
        .{ .in = "::/0", .want = "::/0" },
        .{ .in = "2001:db8::/32", .want = "2001:db8::/32" },
        .{ .in = "127.0.0.1/8", .want = "127.0.0.1/8" },
        .{ .in = "1.2.3.4/032", .want = "1.2.3.4/032" },
        .{ .in = "010.0.0.1", .want = null },
        .{ .in = "1.2.3", .want = null },
        .{ .in = "1.2.3.4.5", .want = null },
        .{ .in = "256.1.1.1", .want = null },
        .{ .in = "example.com", .want = null },
        .{ .in = "", .want = null },
        .{ .in = "1.2.3.4/33", .want = null },
        .{ .in = "1::2::3", .want = null },
        .{ .in = "1.2.3.4/+32", .want = null },
        .{ .in = "1.2.3.4/ 32", .want = null },
        .{ .in = "10.0.0.0/0x8", .want = null },
        .{ .in = "1.2.3.4/", .want = null },
        .{ .in = "/32", .want = null },
        .{ .in = "12345::", .want = null },
        .{ .in = "1:2:3:4:5:6:7:8", .want = "1:2:3:4:5:6:7:8/128" },
        .{ .in = "1:2:3:4:5:6:7:8:9", .want = null },
        .{ .in = "1:2:3:4:5:6:7", .want = null },
        .{ .in = ":1::2", .want = null },
        .{ .in = "1::2:", .want = null },
        .{ .in = "1.2.3.4/1.2.3.4", .want = null },
        .{ .in = "-1.2.3.4", .want = null },
        .{ .in = "1.2.3.-4", .want = null },
    };
    for (cases) |c| {
        const got = try lower.hostCidr(a, c.in);
        if (c.want == null) {
            if (got != null) {
                std.debug.print("hostCidr(\"{s}\"): want null, got \"{s}\" -- a wrong ACCEPT emits an allow rule vakedc would not\n", .{ c.in, got.? });
                return error.TestUnexpectedResult;
            }
        } else {
            if (got == null) {
                std.debug.print("hostCidr(\"{s}\"): want \"{s}\", got null -- a wrong REJECT drops a rule vakedc emits\n", .{ c.in, c.want.? });
                return error.TestUnexpectedResult;
            }
            std.testing.expectEqualStrings(c.want.?, got.?) catch |e| {
                std.debug.print("hostCidr(\"{s}\"): want \"{s}\", got \"{s}\"\n", .{ c.in, c.want.?, got.? });
                return e;
            };
        }
    }
}

// ==========================================================================
// Slice 6 (final): ebpf.policy + colmena.hive. Goldens from LIVE vakedc on
// dev-cx53.
//
// ebpf.policy is NOT a deferred slot, despite three stale docstrings in
// lower.py saying so (L41, emit_deferred's docstring at L1554, and
// test_lowering_fixtures.py's EMITTER_REGISTRY comment at L54). Resolved from
// the code: the registry row carries no `deferred=True` and lower() L2452
// dispatches it. Reported as doc drift, not fixed.
//
// gen/ebpf.policy.json uses a THIRD serializer: json.dumps(indent=2,
// sort_keys=True) -- pretty, keys SORTED (not emit order), and with `indent`
// set the item separator loses its trailing space. Note in the golden that
// "allow" sorts before "default"/"grant"/"membrane"/"principal", and that
// each rule's keys come out cidr/host/port/proto -- emission order is
// proto/host/cidr/port, so a renderer that preserved emit order would be
// visibly wrong.
// ==========================================================================

const agent_egress_src =
    \\# agent-egress — the network-membrane vertical slice (deny-by-default egress).
    \\#
    \\# This is the FULL slice my critique asked for: one .vaked declaring a network
    \\# membrane that lowers to a policy artifact, is enforced by agent-guardd, and is
    \\# testified to over the eventd hash chain — closing Vaked declares → eBPF
    \\# testifies → operator surfaces for the `network` membrane.
    \\#
    \\#   network agentEgress       → gen/ebpf.policy  (compiled allow/deny egress set)
    \\#   default = "deny"          → deny-by-default posture (0012 §7; agent-guardd)
    \\#   allow = [ egress(h, p) ]  → per-destination allow rules (host:port)
    \\#   stream ebpfEvents         → agent-guardd's ringbuf testimony channel
    \\#
    \\# `network` is a top-level kind (grammar §kind) AND a builtin capability domain;
    \\# here we use the kind form to declare a concrete egress membrane. The mesh ties
    \\# the membrane to a named principal whose grant lattice (network.loopback) the
    \\# allow-set refines into host:port rules — exactly the "per-principal allow/deny
    \\# sets for network egress … compiled from the capability grant-sets" of 0012 §7.
    \\
    \\runtime "agent-egress" {
    \\  systems = ["x86_64-linux"]
    \\
    \\  # Daemon-channel namespace declared for this runtime (RFC 0017, D3: runtime-scoped).
    \\  namespace agentGuardd {
    \\    member ringbuf
    \\  }
    \\
    \\  # eBPF testimony channel: agent-guardd publishes one event per egress decision
    \\  # (allow/deny) onto this stream; the events land on the eventd hash chain.
    \\  stream ebpfEvents {
    \\    source = agentGuardd.ringbuf
    \\    type = Event.Ebpf
    \\    retention = 24h
    \\  }
    \\
    \\  # The guarded principal and the grant it holds in the builtin `network` domain
    \\  # (none < loopback < lan < egress). `network.loopback` = "egress to loopback
    \\  # only" — the allow-set below is its host:port refinement.
    \\  mesh agentfield {
    \\    node worker {
    \\      role = "worker"
    \\      capabilities = [network.loopback]
    \\    }
    \\  }
    \\
    \\  # The egress membrane for `worker`: deny-by-default, with an explicit loopback
    \\  # allow-set. agent-guardd compiles this to gen/ebpf.policy, loads it as a real
    \\  # cgroup/skb BPF program, and enforces it (attaching in-kernel on a capable
    \\  # host; a userspace reference datapath with the identical decision elsewhere).
    \\  network agentEgress {
    \\    principal = "worker"
    \\    default = "deny"
    \\    allow = [egress("127.0.0.1", 9), egress("127.0.0.1", 7)]
    \\    observe = stream.ebpfEvents
    \\  }
    \\}
++ "\n";

const agentfield_swe_src =
    \\# agentfield-swe.vaked — the daily-use target system (#27 calibration example):
    \\# a Nix-based agentfield-like runtime running swe_af workflows.
    \\#
    \\# Demonstrates the full composition:
    \\#   index    — the repo corpus the agents ground against
    \\#   stream   — transcripts + eBPF evidence
    \\#   memory   — the MemPalace-shaped palace mined from transcripts (0014)
    \\#   mesh     — the agent field: operator DELEGATES attenuated authority (§4.4)
    \\#   workflow — swe_af: step ORDERING as a checked DAG (0015)
    \\#   fiber/parallel/surface — the runtime plane around them
    \\
    \\use "./engines/zig.vaked"
    \\
    \\runtime "agent-field" {
    \\  systems = ["x86_64-linux"]
    \\
    \\  # Daemon-channel namespaces declared for this runtime (RFC 0017, D3: runtime-scoped).
    \\  # A runtime only sees daemon channels it has explicitly brought into scope (POLA).
    \\  namespace agentpipe {
    \\    member transcripts
    \\    member screenrec
    \\  }
    \\  namespace agentGuardd {
    \\    member ringbuf
    \\  }
    \\
    \\  # The box this runtime deploys to (#28 third slice).
    \\  host vps {
    \\    system = "x86_64-linux"
    \\    deploy = "ssh://root@vps"
    \\  }
    \\
    \\  index repoCorpus {
    \\    source = [github("peterlodri-sec/vaked-base")]
    \\    normalize = crabcc.markdown
    \\    emit = [catalog.jsonl, catalog.sqlite]
    \\  }
    \\
    \\  stream transcripts {
    \\    source = agentpipe.transcripts
    \\    type = Agent.Transcript
    \\    retention = 30d
    \\  }
    \\
    \\  stream ebpfEvents {
    \\    source = agentGuardd.ringbuf
    \\    type = Event.Ebpf
    \\    retention = 24h
    \\  }
    \\
    \\  memory palace {
    \\    source = stream.transcripts
    \\    mine = mempalace.convos
    \\    scope = "agent"
    \\    retention = 90d
    \\    emit = [catalog.sqlite]
    \\  }
    \\
    \\  # The agent field. Mesh edges are capability DELEGATIONS: the operator holds
    \\  # the strongest grants and every agent receives an attenuated subset (POLA).
    \\  mesh field {
    \\    node operator {
    \\      role = "control-plane"
    \\      capabilities = [fs.repo_rw, process.spawn, mcp.github_write, mem.admin]
    \\    }
    \\    node planner {
    \\      role = "plan"
    \\      capabilities = [fs.repo_ro, mem.recall]
    \\    }
    \\    node coder {
    \\      role = "implement"
    \\      capabilities = [fs.repo_rw, process.spawn_sandboxed, mem.recall]
    \\    }
    \\    node reviewer {
    \\      role = "review"
    \\      capabilities = [fs.repo_ro, mem.recall]
    \\    }
    \\    node broker {
    \\      role = "mcp-broker"
    \\      capabilities = [mcp.github_write]
    \\    }
    \\    operator -> planner
    \\    operator -> coder
    \\    operator -> reviewer
    \\    operator -> broker
    \\  }
    \\
    \\  # The run budget the workflow (and its heaviest step) is bounded by,
    \\  # enforced by mcp-brokerd / the supervision plane (#28).
    \\  budget swe {
    \\    tokens = 2000000
    \\    wallClock = 2h
    \\    toolCalls = 400
    \\    approvals = "destructive"
    \\    fuel = 5000000000
    \\  }
    \\
    \\  # The swe_af workflow. Workflow edges are step ORDERING (a checked DAG);
    \\  # each step names its executing agent from the mesh.
    \\  workflow swe_af {
    \\    on = "github.issue.labeled:agent"
    \\    budget = budget.swe
    \\    maxDepth = 6
    \\
    \\    node plan {
    \\      agent = field.planner
    \\      output = artifacts.plan
    \\    }
    \\    node code {
    \\      agent = field.coder
    \\      input = artifacts.plan
    \\      output = artifacts.patch
    \\      retries = 2
    \\    }
    \\    node review {
    \\      agent = field.reviewer
    \\      input = artifacts.patch
    \\      output = artifacts.verdict
    \\    }
    \\    node publish {
    \\      agent = field.broker
    \\      input = artifacts.verdict
    \\    }
    \\
    \\    plan -> code -> review -> publish
    \\  }
    \\
    \\  # The scheduling class interactive agents run under (#28).
    \\  runclass interactive {
    \\    priority = "high"
    \\    interval = 5s
    \\  }
    \\
    \\  fiber transcriptMiner {
    \\    engine = zigDaemon
    \\    input = stream.transcripts
    \\    output = artifacts.palaceEntries
    \\    runclass = runclass.interactive
    \\  }
    \\
    \\  surface fieldView {
    \\    mode = raylib
    \\    fps = 30
    \\    input = [stream.ebpfEvents, graph.swe_af, graph.field]
    \\    views = ["workflow-dag", "mesh-topology", "memory-recall"]
    \\  }
    \\
    \\  parallel "field-runtime" {
    \\    fibers = [transcriptMiner, fieldView]
    \\    strategy = "supervised-dag"
    \\    supervisor = otp
    \\  }
    \\}
++ "\n";

const golden_ebpf_policy_json =
    \\{
    \\  "_generated": "generated by Vaked from agent-egress.vaked:runtime agent-egress — do not edit",
    \\  "membranes": [
    \\    {
    \\      "allow": [
    \\        {
    \\          "cidr": "127.0.0.1/32",
    \\          "host": "127.0.0.1",
    \\          "port": 9,
    \\          "proto": "tcp"
    \\        },
    \\        {
    \\          "cidr": "127.0.0.1/32",
    \\          "host": "127.0.0.1",
    \\          "port": 7,
    \\          "proto": "tcp"
    \\        }
    \\      ],
    \\      "default": "deny",
    \\      "grant": "network.loopback",
    \\      "membrane": "agentEgress",
    \\      "observe": "stream.ebpfEvents",
    \\      "principal": "worker"
    \\    }
    \\  ],
    \\  "runtime": "agent-egress",
    \\  "version": 1
    \\}
++ "\n";

const golden_colmena_hive_nix =
    \\# generated by Vaked from agentfield-swe.vaked:runtime agent-field — do not edit
    \\#
    \\# colmena hive (#51): `colmena apply` deploys nixosModules.agent-field
    \\# to the declared hosts. Standalone form pins nothing itself —
    \\# the flake (the spine) is the pinned entry point; <nixpkgs>
    \\# here is the documented interface-only escape (0012 §4.3).
    \\{
    \\  meta = {
    \\    nixpkgs = <nixpkgs>;
    \\  };
    \\
    \\  "vps" = { ... }: {
    \\    deployment.targetHost = "root@vps";
    \\    nixpkgs.system = "x86_64-linux";
    \\    # interface-only module path, exactly as the spine
    \\    # declares nixosModules.agent-field (0012 §4.3).
    \\    imports = [ ../../nixos/agent-field.nix ];
    \\  };
    \\}
++ "\n";

test "lower: ebpf.policy reproduces live vakedc byte-for-byte" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    try testing.expectEqual(@as(usize, 2389), agent_egress_src.len);
    try testing.expectEqual(@as(usize, 629), golden_ebpf_policy_json.len);

    const result = try lowerSource(a, agent_egress_src, "vaked/examples/membrane/agent-egress.vaked");
    try expectFile(result, "gen/ebpf.policy.json", golden_ebpf_policy_json);
}

test "lower: colmena.hive reproduces live vakedc byte-for-byte" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    try testing.expectEqual(@as(usize, 3934), agentfield_swe_src.len);
    try testing.expectEqual(@as(usize, 648), golden_colmena_hive_nix.len);

    const result = try lowerSource(a, agentfield_swe_src, "vaked/examples/agentfield-swe.vaked");
    try expectFile(result, "gen/colmena/hive.nix", golden_colmena_hive_nix);
}
