#!/usr/bin/env python3
"""gen_scale_fixture — generate a synthetic ``runtime { … }`` with N fibers.

Emits valid Vaked source text (per ``vaked/grammar/vaked-v0-plus.ebnf``) modeled
exactly on the proven ``vaked/examples/operator-field.vaked`` shape so the result
parses, type-checks, and lowers cleanly. Used to benchmark ``vakedc lower``'s
scaling in fiber count (Risk 4 — the ``_children_of`` adjacency-index fix).

Two topologies:

  * ``independent`` — every fiber shares the one screenrec stream as input and
    writes a distinct artifact output; no fiber depends on another.
  * ``chained``     — ``fiber_k.input`` is ``fiber_{k-1}.output`` (an
    ``artifacts.stageN`` ref), so the fibers form a single linear data chain;
    ``fiber_0`` reads the screenrec stream.

Both keep one ``engine`` (``zigimg``, imported from ./engines/zig.vaked relative
to the fixture's location — the generator writes alongside that path convention)
and the same ``policy { … }`` block as operator-field, so each fiber selects the
``zig.daemoncfg`` emitter (the per-fiber O(deg) lookup under test).

CLI::

    python3 tests/spec/gen_scale_fixture.py --n 1000 --topology independent
    python3 tests/spec/gen_scale_fixture.py --n 5000 --topology chained --out /tmp/x.vaked

Prints to stdout unless ``--out PATH`` is given. The fixture references the
``zigimg`` engine via a bare ``engine = zigimg`` (resolved as external — the
checker treats unknown engine refs leniently, exactly as operator-field's
``mediaCompress`` does when the ./engines import is absent), so the emitted file
is standalone and needs no sibling files to lower.
"""

from __future__ import annotations

import argparse
import sys


def _fiber_block(k: int, topology: str) -> str:
    """One ``fiber fiber_k { … }`` block, indented two spaces (runtime body)."""
    if topology == "chained" and k > 0:
        # fiber_k reads the previous fiber's artifact output.
        input_ref = "artifacts.stage%d" % (k - 1)
    else:
        # independent (or the chain head): read the shared screenrec stream.
        input_ref = "stream.screenrec"
    output_ref = "artifacts.stage%d" % k
    return "\n".join([
        "  fiber fiber_%d {" % k,
        "    engine = zigimg",
        "    input = %s" % input_ref,
        "    output = %s" % output_ref,
        "",
        "    policy {",
        "      strip_metadata = true",
        "      max_pixels = \"4K\"",
        "      formats = [\"png\", \"webp\"]",
        "    }",
        "  }",
    ])


def generate(n: int, topology: str) -> str:
    """The full ``.vaked`` source text for a runtime with ``n`` fibers."""
    if n < 0:
        raise ValueError("n must be >= 0")
    if topology not in ("independent", "chained"):
        raise ValueError("topology must be 'independent' or 'chained'")

    lines = []
    lines.append("# generated by gen_scale_fixture.py — n=%d topology=%s" % (n, topology))
    lines.append("runtime \"scale-bench\" {")
    lines.append("  systems = [\"x86_64-linux\", \"aarch64-linux\"]")
    lines.append("")
    # One stream the fibers read from (matches operator-field's screenrec).
    lines.append("  stream screenrec {")
    lines.append("    source = agentpipe.screenrec")
    lines.append("    type = Media.Frame")
    lines.append("    fps = 10")
    lines.append("  }")
    lines.append("")
    for k in range(n):
        lines.append(_fiber_block(k, topology))
        lines.append("")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Generate a scale-benchmark .vaked fixture.")
    ap.add_argument("--n", type=int, required=True, help="number of fibers")
    ap.add_argument("--topology", choices=("independent", "chained"),
                    default="independent", help="fiber wiring topology")
    ap.add_argument("--out", default=None,
                    help="write to PATH (default: stdout)")
    args = ap.parse_args(argv)

    text = generate(args.n, args.topology)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
