# generated by Vaked from operator-field.vaked:runtime operator-field — do not edit
#
# Expected-output fixture (no compiler exists yet) — see ./README.md and
# docs/language/0012-lowering.md §4 (the Nix spine). Edits belong in the source
# .vaked file, not here.
{
  description = "operator-field — generated by Vaked";

  inputs = {
    # nixpkgs is emitted pinned to the toolchain's baseline rev (0012 §4.1): an
    # explicit rev, never a moving channel ref. The 40-hex value below is a
    # disclosed placeholder (all-`b` = "baseline"; see ./README.md); the
    # committed flake.lock (produced at first build) records the real resolution.
    nixpkgs.url = "github:NixOS/nixpkgs/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";

    # index zigCorpus — sources (unpinned; flake.lock records the resolved rev).
    # 0012 §4.2: each index source becomes a flake input.
    zigCorpus-src-zig-guide = { url = "github:Sobeston/zig.guide"; flake = false; };
    zigCorpus-src-awesome-zig = { url = "github:C-BJ/awesome-zig"; flake = false; };
    zigCorpus-src-raylib-zig = { url = "github:raylib-zig/raylib-zig"; flake = false; };
    zigCorpus-src-zigimg = { url = "github:zigimg/zigimg"; flake = false; };

    # index zigbeeFirmware — trust = pinned { commit, sha256 } (0012 §4.2):
    # commit pins the rev; sha256 is recorded as the lock entry's narHash so the
    # build verifies the fetch. raw.github(...) => flake = false.
    zigbeeFirmware-src = {
      url = "github:Koenkk/zigbee-OTA/<commit>"; # trust.pinned.commit
      flake = false;
    };
  };

  outputs = { self, nixpkgs, ... }@inputs:
    let
      # runtime operator-field — systems = ["x86_64-linux", "aarch64-linux"]
      systems = [ "x86_64-linux" "aarch64-linux" ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f system);
    in
    {
      # nixosModules.<runtime> — wires the OTP/Zig daemons and references the
      # gen/ artifacts as installed files (0012 §4.3).
      nixosModules.operator-field = import ./nixos/operator-field.nix {
        # NixOS module fixture is described in 0012 §4.3; not emitted as a
        # separate file in this fixture set (interface only).
        inherit self;
      };

      packages = forAllSystems (system:
        let pkgs = nixpkgs.legacyPackages.${system};
        in {
          # engine zigDaemon (fiber mediaCompress: engine = zigDaemon) — built Zig pkg.
          zigDaemon = pkgs.callPackage ./pkgs/zigDaemon.nix { };

          # index zigCorpus, emit ∋ nix.derivation (0012 §5.3a) — CrabCC index
          # derivation; runs crabcc at build time over the pinned sources with
          # normalize = crabcc.markdown.
          zigCorpus-crabcc-index = pkgs.stdenv.mkDerivation {
            pname = "zigCorpus-crabcc-index";
            version = "0";
            srcs = [
              inputs.zigCorpus-src-zig-guide
              inputs.zigCorpus-src-awesome-zig
              inputs.zigCorpus-src-raylib-zig
              inputs.zigCorpus-src-zigimg
            ];
            nativeBuildInputs = [ pkgs.crabcc ];
            buildPhase = ''
              # normalize = crabcc.markdown ; emit = catalog.jsonl, catalog.sqlite
              crabcc index build --normalize markdown \
                --emit jsonl --emit sqlite \
                --out $out
            '';
          };
        });

      apps = forAllSystems (system:
        let pkgs = nixpkgs.legacyPackages.${system};
        in {
          # surface operatorMap (mode = raylib) — launcher app.
          # 0012 §7: surface launcher body is DEFERRED (no-op today). The slot
          # exists so the registry test stays honest, but the mapping (raylib
          # host integration) is not yet specified. The deferred body is derived
          # from NOTHING but the surface decl name: a stub that exits non-zero
          # with the standard deferral message — no real launcher is wired, and
          # it does not route through any engine/fiber package.
          operatorMap = {
            type = "app";
            program = "${pkgs.writeShellScript "operatorMap-launcher-deferred" ''
              echo "vaked: surface launcher lowering deferred (0012 §7)" >&2
              exit 1
            ''}";
          };
        });

      devShells = forAllSystems (system:
        let pkgs = nixpkgs.legacyPackages.${system};
        in {
          default = pkgs.mkShell {
            # toolchains the runtime needs: zig (engines), crabcc (index).
            packages = [ pkgs.zig pkgs.crabcc ];
          };
        });
    };
}
