# generated by Vaked from experiment-seal.vaked:runtime experiment-seal — do not edit
#
# Expected-output fixture (no compiler exists yet) — see ./README.md and
# docs/language/0012-lowering.md §4 (the Nix spine). Edits belong in the source
# .vaked file, not here.
{
  description = "experiment-seal — generated by Vaked";

  inputs = {
    # nixpkgs is emitted pinned to the toolchain's baseline rev (0012 §4.1): an
    # explicit rev, never a moving channel ref. The 40-hex value below is a
    # disclosed placeholder (all-`b` = "baseline"; see ./README.md); the
    # committed flake.lock (produced at first build) records the real resolution.
    nixpkgs.url = "github:NixOS/nixpkgs/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
  };

  outputs = { self, nixpkgs, ... }@inputs:
    let
      # runtime experiment-seal — systems = ["x86_64-linux", "aarch64-darwin"]
      systems = [ "x86_64-linux" "aarch64-darwin" ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f system);
    in
    {
      # nixosModules.<runtime> — wires the OTP/Zig daemons and references the
      # gen/ artifacts as installed files (0012 §4.3).
      nixosModules.experiment-seal = import ./nixos/experiment-seal.nix {
        # NixOS module fixture is described in 0012 §4.3; not emitted as a
        # separate file in this fixture set (interface only).
        inherit self;
      };

      packages = forAllSystems (system:
        let pkgs = nixpkgs.legacyPackages.${system};
        in {
        });

      apps = forAllSystems (system:
        let pkgs = nixpkgs.legacyPackages.${system};
        in {
        });

      devShells = forAllSystems (system:
        let pkgs = nixpkgs.legacyPackages.${system};
        in {
          default = pkgs.mkShell {
            # toolchains the runtime needs: .
            packages = [  ];
          };
        });
    };
}
